### ISSUE TITLE
App Manager: Crash report while clicking on app icon on list quickly

### ISSUE THREAD

**Issue by Wojtaz0w** [MuntashirAkon/AppManager#1110] opened 2023-06-26 11:01 UTC
java.lang.RuntimeException: java.lang.IllegalArgumentException: ApkFile not found for key 982887276
    at io.github.muntashirakon.AppManager.details.info.AppInfoViewModel.lambda$loadAppInfo$1(AppInfoViewModel.java:330)
    at io.github.muntashirakon.AppManager.details.info.AppInfoViewModel$$ExternalSyntheticLambda1.run(Unknown Source:2)
    at android.os.Handler.handleCallback(Handler.java:942)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7919)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:859)
 Caused by: java.lang.IllegalArgumentException: ApkFile not found for key 982887276
   at io.github.muntashirakon.AppManager.apk.ApkFile.getInstance(ApkFile.java:105)
   at io.github.muntashirakon.AppManager.details.info.AppInfoViewModel.loadAppInfo(AppInfoViewModel.java:261)
   at io.github.muntashirakon.AppManager.details.info.AppInfoFragment.loadPackageInfo(AppInfoFragment.java:1610)
   at io.github.muntashirakon.AppManager.details.info.AppInfoFragment.$r8$lambda$oxlKbqiAsxIkEG69gntC-jrgnXk(Unknown Source:0)
   at io.github.muntashirakon.AppManager.details.info.AppInfoFragment$$ExternalSyntheticLambda63.run(Unknown Source:2)
   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
   at java.util.concurrent.FutureTask.run(FutureTask.java:264)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
   at java.lang.Thread.run(Thread.java:1012)

Device Info:
App version: 3.1.1
App version code: 424
Android build version: eng.nobody.20230323.031518
Android release version: 13
Android SDK version: 33
Android build ID: lineage_lancelot-userdebug 13 TQ1A.230205.002 
Device brand: Redmi
Device manufacturer: Xiaomi
Device name: lancelot
Device model: Redmi 9
Device product name: lineage_lancelot
Device hardware name: mt6768
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: pl-PL
In-App Language: auto
Mode: auto
Inferred Mode: root

**Comment by MuntashirAkon** [comment] 2023-06-27 16:13
Duplicate of #658

**Closed by MuntashirAkon** 2023-06-27 16:13 UTC
