### ISSUE TITLE
Crash Report 

### ISSUE THREAD

**Issue by shuvashish76** [MuntashirAkon/AppManager#697] opened 2022-03-07 07:21 UTC
- [x] I know what my device, OS and App Manager versions are
- [x] I know how to take logs
- [ ] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**
Crashed while updated an app from Aurora store then closed the updated app. Not sure if it's related to this crash. 1 time crash.

**Crash logs**

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{io.github.muntashirakon.AppManager/io.github.muntashirakon.AppManager.main.MainActivity}: java.lang.RuntimeException: Parcel android.os.Parcel@94be18: Unmarshalling unknown type code 6881399 at offset 1612
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2781)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2859)
    at android.app.ActivityThread.-wrap11(Unknown Source:0)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1592)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6518)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
 Caused by: java.lang.RuntimeException: Parcel android.os.Parcel@94be18: Unmarshalling unknown type code 6881399 at offset 1612
   at android.os.Parcel.readValue(Parcel.java:2833)
   at android.os.Parcel.readSparseArrayInternal(Parcel.java:3204)
   at android.os.Parcel.readSparseArray(Parcel.java:2416)
   at android.os.Parcel.readValue(Parcel.java:2811)
   at android.os.Parcel.readArrayMapInternal(Parcel.java:3123)
   at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:273)
   at android.os.BaseBundle.unparcel(BaseBundle.java:226)
   at android.os.Bundle.getSparseParcelableArray(Bundle.java:1009)
   at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2134)
   at android.app.Activity.onRestoreInstanceState(Activity.java:1102)
   at android.app.Activity.performRestoreInstanceState(Activity.java:1057)
   at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1261)
   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2754)
   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2859)
   at android.app.ActivityThread.-wrap11(Unknown Source:0)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1592)
   at android.os.Handler.dispatchMessage(Handler.java:106)
   at android.os.Looper.loop(Looper.java:164)
   at android.app.ActivityThread.main(ActivityThread.java:6518)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

```

**Device info**
App version: 3.0.0-alpha01
App version code: 400
Android build version: 8704X_S001025_190606_ROW
Android release version: 8.1.0
Android SDK version: 27
Android build ID: TB-8704X_S001025_190606_ROW
Device brand: Lenovo
Device manufacturer: LENOVO
Device name: TB-8704X
Device model: Lenovo TB-8704X
Device product name: TB-8704X
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-IN
In-App Language: auto
Mode: auto

**Additional context**
_Please change the title of this issue from your side._

**Comment by MuntashirAkon** [comment] 2022-03-07 08:38
Duplicate of #656

**Closed by MuntashirAkon** 2022-03-07 08:38 UTC
Labels: bug, S3, P3
