### ISSUE TITLE
App crashing when given root rights

### ISSUE THREAD

**Issue by Matrix-sudo** [MuntashirAkon/AppManager#1272] opened 2024-01-12 07:51 UTC
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

When enabling root rights the app crashes.
When revoking rights the app works (but without all root options)
I tried this on both 3.1.4 and 4 alpha - same outcome.
All permissions are given to the app. 

### Logs

java.lang.IllegalStateException: External directory unavailable.
    at io.github.muntashirakon.AppManager.ipc.RootServiceManager.startRootProcess(RootServiceManager.java:161)
    at io.github.muntashirakon.AppManager.ipc.RootServiceManager.createBindTask(RootServiceManager.java:285)
    at io.github.muntashirakon.AppManager.ipc.RootService.bindOrTask(RootService.java:146)
    at io.github.muntashirakon.AppManager.ipc.RootService.bind(RootService.java:110)
    at io.github.muntashirakon.AppManager.ipc.RootService.bind(RootService.java:125)
    at io.github.muntashirakon.AppManager.ipc.ServiceConnectionWrapper.lambda$startDaemon$0$io-github-muntashirakon-AppManager-ipc-ServiceConnectionWrapper(ServiceConnectionWrapper.java:117)
    at io.github.muntashirakon.AppManager.ipc.ServiceConnectionWrapper$$ExternalSyntheticLambda0.run(Unknown Source:4)
    at android.os.Handler.handleCallback(Handler.java:958)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:230)
    at android.os.Looper.loop(Looper.java:319)
    at android.app.ActivityThread.main(ActivityThread.java:8893)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
 Caused by: java.io.FileNotFoundException: No available shared storage found.
   at io.github.muntashirakon.AppManager.utils.FileUtils.getExternalCachePath(FileUtils.java:210)
   at io.github.muntashirakon.AppManager.ipc.RootServiceManager.startRootProcess(RootServiceManager.java:159)
   at io.github.muntashirakon.AppManager.ipc.RootServiceManager.createBindTask(RootServiceManager.java:285)
   at io.github.muntashirakon.AppManager.ipc.RootService.bindOrTask(RootService.java:146)
   at io.github.muntashirakon.AppManager.ipc.RootService.bind(RootService.java:110)
   at io.github.muntashirakon.AppManager.ipc.RootService.bind(RootService.java:125)
   at io.github.muntashirakon.AppManager.ipc.ServiceConnectionWrapper.lambda$startDaemon$0$io-github-muntashirakon-AppManager-ipc-ServiceConnectionWrapper(ServiceConnectionWrapper.java:117)
   at io.github.muntashirakon.AppManager.ipc.ServiceConnectionWrapper$$ExternalSyntheticLambda0.run(Unknown Source:4)
   at android.os.Handler.handleCallback(Handler.java:958)
   at android.os.Handler.dispatchMessage(Handler.java:99)
   at android.os.Looper.loopOnce(Looper.java:230)
   at android.os.Looper.loop(Looper.java:319)
   at android.app.ActivityThread.main(ActivityThread.java:8893)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

Device Info:
App version: 3.1.4
App version code: 427
Android build version: S916BXXS3BWKC
Android release version: 14
Android SDK version: 34
Android build ID: UP1A.231005.007.S916BXXS3BWKC
Device brand: samsung
Device manufacturer: samsung
Device name: dm2q
Device model: SM-S916B
Device product name: dm2qxxx
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: he-IL
In-App Language: auto
Mode: auto
Inferred Mode: root

### Device info

- Device: s23+
- OS Version: 14
- App Manager Version: 3.1.4 / 4 alpha
- Mode: Root/ADB/NonRoot

**Comment by MuntashirAkon** [comment] 2024-01-21 07:21
Duplicate of #948

**Closed by MuntashirAkon** 2024-01-21 07:21 UTC
Labels: Bug, Duplicate

**Comment by Matrix-sudo** [comment] 2024-01-21 07:31
Hey
After reading issue 948 I understand the cause is a faulty data format?
So theoretically after doing a device reset it should work?

**Comment by MuntashirAkon** [comment] 2024-01-21 07:35
> Hey After reading issue 948 I understand the cause is a faulty data format? So theoretically after doing a device reset it should work?

It's all speculations, at this point. It would be helpful, though, if you could reply to the last comment in that issue with the requested tasks.
