### ISSUE TITLE
Brief summary Tracking

### ISSUE THREAD

**Issue by NSTAdventure** [MuntashirAkon/AppManager#219] opened 2021-01-08 05:53 UTC
Tracker Component Actually Removable Without Root
We Still Able To Do It
Manualy Using Mt Manager (VIP Acc Needed)
First Get Apk File
Open It Search For Classes.dex 
here We Can Open It And Edit It:
Search For corresponding folder for example:
Com> Android.gms> Analytics 
This is usually where the tracker lives :)

And Usually too i always remove the folder entirely without any leftover 
But 
App crashed once i remove it 
I guess it security exception again 

This happend on plant vs zombie 2 V 6.8.5
Hermit browser v 10.0.0

Decompiling method:
Note:
For This Test Currently I Using Mt Manager Which Required VIP Account To Proccedd 
(Bruh just use modded mt manager it's work)

1. Mt Manager Could Able To Extract The Content First Instead Of Viewing only⬇️
(Well if you choose view we still can edit the Component but do not forgot to merge it first and Sign the apk)
2. After Decompile We Edit The String Inside Classes.dex Or AndroidManifest.xml
3. After We Finish Edit In 
Let's Compile Again To Apk And Sign Apk File
4. Instal And Launch To Test

Additional Info:
I Success Attempt to remove tracker such as com.parse inside App Called Midori Browser

Warning:
No Modded Apk Will Share Here include midori browser due to copyright and legal law!

Best Regards
NST_Adventure

**Comment by MuntashirAkon** [comment] 2021-01-08 07:13
What does it have anything to do with App Manager? MT Manager itself is flagged as virus by many anti-virus software.

**Comment by NSTAdventure** [comment] 2021-01-08 07:37
> What does it have anything to do with App Manager? MT Manager itself is flagged as virus by many anti-virus software.


1. for Refference How I Tried To Removing Tracker Using Simple Method Available
2. The connection with the app manager application?
You may add the Simple method to removing tracker
3. Flagged as virus?
Because how MT Manager Work 
Mt Manager Is Tool To:
-Decompile Compile And Edit Apk 

Because Of This Purpose Of Course AV Flag It As Virus :-)

**Comment by MuntashirAkon** [comment] 2021-01-08 08:01
> * You may add the Simple method to removing tracker

Duplicate of #138

> Because Of This Purpose Of Course AV Flag It As Virus :-)

No, because it contains _trojan_.

**Closed by MuntashirAkon** 2021-01-08 08:01 UTC
Labels: P3, feature

**Comment by NSTAdventure** [comment] 2021-01-08 08:03
> No, because it contains _trojan_.

Trojan?
Hmm i check it later
