### ISSUE TITLE
AppManager broken for secondary users (user 10) even despite full root support (magisk)

### ISSUE THREAD

**Issue by Aleximal** [MuntashirAkon/AppManager#1342] opened 2024-04-11 18:40 UTC
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

AppManager fails to initialize in Secondary user (stalls forever)

### To Reproduce

Have stock  or Calyx (or any other os/ROM)

Have root/magisk
Have multiuser enabled 
Have magisk configured for multiuser

Install AppManager 3.1.5 (latest Fdroid) in secondary user (user 10)

Launch appmanager

Grant root

The AppManager never finishes initialization

### Expected behavior

AppManager to initialize and start managing User 10 (secondary user's) apps

### Device info

- Device: redfin / pixel 5
- OS Version: android 14 (any flavor)
- App Manager Version: 3.1.5 (latest Fdroid)
- Mode: Root (magisk)

**Comment by MuntashirAkon** [comment] 2024-04-13 05:59
Duplicate of #834

**Closed by MuntashirAkon** 2024-04-13 05:59 UTC
Labels: Bug, Duplicate
