### ISSUE TITLE
Can't install another app if one app is already installing

### ISSUE THREAD

**Issue by Cyberavater** [MuntashirAkon/AppManager#479] opened 2021-06-14 05:44 UTC
Possible workaround: Add the app to queue to install next, after the current one.

**Comment by MuntashirAkon** [comment] 2021-06-14 05:54
Duplicate of #230

**Comment by MuntashirAkon** [comment] 2021-06-14 05:54
> Possible workaround: Add the app to queue to install next, after the current one.

This is actually the only sane workaround.

**Closed by MuntashirAkon** 2021-06-14 05:54 UTC
Labels: P3, S3, bug
