### ISSUE TITLE
can not backup data for org.mozilla.fenix

### ISSUE THREAD

**Issue by ale82to** [MuntashirAkon/AppManager#170] opened 2020-11-29 15:10 UTC
app manager is NOT able to backup Firefox (well new fenix org.mozilla.fenix) app DATA log says Cannot backup app as it has keystore items but others backup  app like titanium have not any problems at all.
since I ve got both root and exposed I wasn not expecting suck problems such a pity!
if that matters I M on lineage OS 7.1.2 and I ve got root

**Comment by MuntashirAkon** [comment] 2020-11-29 15:14
Duplicate of #139. Most apps with keystore items will not restore as expected.

**Closed by MuntashirAkon** 2020-11-29 15:14 UTC
Labels: P3, S3, bug, duplicate
