### ISSUE TITLE
Work Profile - Root granted but doesn't load, needs USB Debugging perms

### ISSUE THREAD

**Issue by szymonj99** [MuntashirAkon/AppManager#1078] opened 2023-05-28 00:11 UTC
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

After installing App Manager in a work profile managed by Shelter on an AOSP 13 ROM, the `Initializing` screen remains open for a long time. It asks for root permissions which are granted with Magisk. After a while, it asks for USB Debugging permissions which I have granted. The initialize screen remains open for a few more minutes. If ADB perms aren't granted, the initialize screen remains opened indefinitely. If ADB perms are granted, the app screen is shown after a few minutes.

### To Reproduce

- 1. Install Shelter
- 2. Create a work profile
- 4. Install Magisk in work profile
- 5. Configure Magisk so that each profile has its own independent root rules (might not be relevant)
- 6. Install App Manager in the work profile
- 7. Open App Manager
- 8. Grant Root permissions

### Expected behavior

After granting root permissions, the app should function normally.

### Device info

- Device: POCO F3 (Alioth)
- OS Version: PixelOS 13 (12th of May build)
- App Manager Version: 3.1.0 (423) from F-Droid
- Mode: Root / USB Debugging

**Comment by MuntashirAkon** [comment] 2023-05-28 08:39
Duplicate of #834

**Closed by MuntashirAkon** 2023-05-28 08:39 UTC
Labels: Bug, Duplicate
