### ISSUE TITLE
Screen time widget

### ISSUE THREAD

**Issue by funnysith** [MuntashirAkon/AppManager#1049] opened 2023-04-22 09:28 UTC
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Text does not fit in the widget. Changing the scale and font size does not solve the problem.

### Screenshots

![Screenshot_20230422-141234-01](https://user-images.githubusercontent.com/121553039/233775553-f3bf2297-33c2-4e24-8a58-20ceaae2c13f.jpeg)

### Device info

- Device: Redmi 7A
- OS Version: 13
- App Manager Version: 3.1.0 (423)

**Comment by MuntashirAkon** [comment] 2023-04-22 09:35
Duplicate of #812

**Closed by MuntashirAkon** 2023-04-22 09:35 UTC
Labels: Bug, Duplicate
