### ISSUE TITLE
Anyone success to build it into lineageOS as system APP?

### ISSUE THREAD

**Issue by tufeigunchu** [MuntashirAkon/AppManager#1298] opened 2024-02-29 15:27 UTC
### Describe the existing feature/documentation

I wonder if it works with platform process

**Comment by MuntashirAkon** [comment] 2024-03-02 11:53
You can't use this as a system app right now.

**Comment by MuntashirAkon** [comment] 2024-03-02 11:54
Duplicate of #477

**Closed by MuntashirAkon** 2024-03-02 11:54 UTC
Labels: Duplicate, Help Wanted
