### ISSUE TITLE
Installer | DEX optimization crash

### ISSUE THREAD

**Issue by shuvashish76** [MuntashirAkon/AppManager#1136] opened 2023-07-28 16:43 UTC
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

App crashes with Installer - DEX optimization.

### To Reproduce

1. Install any app (in my case from Aurora Store)
2. Choose AM > Install
3. Immediately perform DEX optimization > ok > Install

### Logs

```
java.lang.IllegalArgumentException: reason -1 invalid
    at android.os.Parcel.createExceptionOrNull(Parcel.java:2430)
    at android.os.Parcel.createException(Parcel.java:2410)
    at android.os.Parcel.readException(Parcel.java:2393)
    at android.os.Parcel.readException(Parcel.java:2335)
    at android.content.pm.IPackageManager$Stub$Proxy.forceDexOpt(IPackageManager.java:8133)
    at io.github.muntashirakon.AppManager.apk.behavior.DexOptimizer.forceDexOpt(DexOptimizer.java:84)
    at io.github.muntashirakon.AppManager.apk.installer.PackageInstallerService$1.onFinishedInstall(PackageInstallerService.java:137)
    at io.github.muntashirakon.AppManager.apk.installer.PackageInstallerCompat.installCompleted(PackageInstallerCompat.java:971)
    at io.github.muntashirakon.AppManager.apk.installer.PackageInstallerCompat.commit(PackageInstallerCompat.java:724)
    at io.github.muntashirakon.AppManager.apk.installer.PackageInstallerCompat.install(PackageInstallerCompat.java:612)
    at io.github.muntashirakon.AppManager.apk.installer.PackageInstallerService.onHandleIntent(PackageInstallerService.java:175)
    at io.github.muntashirakon.AppManager.types.ForegroundService$ServiceHandler.handleMessage(ForegroundService.java:54)
    at android.os.Handler.dispatchMessage(Handler.java:111)
    at android.os.Looper.loopOnce(Looper.java:238)
    at android.os.Looper.loop(Looper.java:357)
    at android.os.HandlerThread.run(HandlerThread.java:67)
 Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.pm.PackageManagerServiceCompilerMapping.getReasonName(PackageManagerServiceCompilerMapping.java:146)
	at com.android.server.pm.PackageDexOptimizer.getAugmentedReasonName(PackageDexOptimizer.java:412)
	at com.android.server.pm.PackageDexOptimizer.dexOptPath(PackageDexOptimizer.java:347)
	at com.android.server.pm.PackageDexOptimizer.performDexOptLI(PackageDexOptimizer.java:268)
	at com.android.server.pm.PackageDexOptimizer.performDexOpt(PackageDexOptimizer.java:164)
```

### Device info

App version: 4.0.0-alpha01
App version code: 434
Android build version: 8049b-fa5cf
Android release version: 12
Android SDK version: 31
Android build ID: S2RUBS32.51-15-9-7
Device brand: motorola
Device manufacturer: motorola
Device name: corfur
Device model: moto g71 5G
Device product name: corfur_g
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-IN
In-App Language: auto
Mode: auto
Inferred Mode: Root

### Additional context

App installed but AM crashed at the same time.

**Comment by MuntashirAkon** [comment] 2023-07-29 07:35
Duplicate of #1131

**Closed by MuntashirAkon** 2023-07-29 07:35 UTC
Labels: Bug, Duplicate
