### ISSUE TITLE
no apps are found

### ISSUE THREAD

**Issue by ANN-MB** [MuntashirAkon/AppManager#686] opened 2022-02-25 22:40 UTC
**Bug description**
Since last update (3.3.0-alpha01), no apps are found at all. Looping search progress bar.

**To Reproduce**
Main screen of the app. 
Try different filters.
Try keywords.

**Expected behavior**
The apps are detected ans displayed on the main screen

**Device info**
Samsung Galaxy A3 2017
Lineage OS 17 (a3y17lte)
App Manager v. 3.3.0-alpha01
Mode: root

**Comment by gnuhead-chieb** [comment] 2022-02-26 00:10
seems duplicate:https://github.com/MuntashirAkon/AppManager/issues/685

Force-stop and Clear AM data from Settings->Apps->AppManager

then try again.

**Comment by MuntashirAkon** [comment] 2022-02-26 06:53
Duplicate of #865

**Closed by MuntashirAkon** 2022-02-26 06:53 UTC
Labels: bug, S3, P3
