### ISSUE TITLE
local ADB Shell

### ISSUE THREAD

**Issue by NSTAdventure** [MuntashirAkon/AppManager#344] opened 2021-03-30 21:50 UTC
**Is your feature request related to a problem? Please describe.**
1. i hate to crack apps like LADB
it's a paid app to access shell on android (so i can use command like pm and so on)

**Describe the solution you'd like**
Add LADB Feature so i can access shell locally

**Describe alternatives you've considered**
no alternative

**Additional context**
1. i want to make an app to device owner easily 
2. i want to use adb shell command via phone but without crack any paids app like com.draco.ladb (LADB)
3. if confused or something else please do not close this issues i will try to explain later 
Thanks
 @MuntashirAkon

**Comment by MuntashirAkon** [comment] 2021-03-31 00:48
Duplicate of #23

**Closed by MuntashirAkon** 2021-03-31 00:48 UTC
Labels: P3, feature
