### ISSUE TITLE
Exception after cleaning the cache

### ISSUE THREAD

**Issue by SolncevNiki** [MuntashirAkon/AppManager#809] opened 2022-07-19 20:52 UTC
Hi,

1-Click Ops -> Trim caches in all apps -> OK

android.database.sqlite.SQLiteException: no such table: app (code 1 SQLITE_ERROR): , while compiling: SELECT * FROM app WHERE package_name = ?
    at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
    at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1047)
    at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:654)
    at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:590)
    at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:62)
    at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
    at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:46)
    at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1546)
    at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1521)
    at androidx.sqlite.db.framework.FrameworkSQLiteDatabase.query(FrameworkSQLiteDatabase.java:183)
    at androidx.room.RoomDatabase.query(RoomDatabase.java:530)
    at androidx.room.util.DBUtil.query(DBUtil.java:86)
    at io.github.muntashirakon.AppManager.db.dao.AppDao_Impl.getAll(AppDao_Impl.java:367)
    at io.github.muntashirakon.AppManager.main.MainViewModel.updateInfoForPackages(MainViewModel.java:506)
    at io.github.muntashirakon.AppManager.main.MainViewModel.access$100(MainViewModel.java:62)
    at io.github.muntashirakon.AppManager.main.MainViewModel$PackageIntentReceiver.onPackageChanged(MainViewModel.java:757)
    at io.github.muntashirakon.AppManager.types.PackageChangeReceiver$ReceiverHandler.handleMessage(PackageChangeReceiver.java:103)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:210)
    at android.os.Looper.loop(Looper.java:299)
    at android.os.HandlerThread.run(HandlerThread.java:67)

Device Info:
App version: 3.0.0-rc04
App version code: 406
Android build version: V13.0.6.0.SKLMIXM
Android release version: 12
Android SDK version: 31
Android build ID: SP1A.210812.016
Device brand: Redmi
Device manufacturer: Xiaomi
Device name: rosemary
Device model: M2101K7BNY
Device product name: rosemary_global
Device hardware name: mt6785
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: ru-RU
In-App Language: ru-RU
Mode: root

**Comment by MuntashirAkon** [comment] 2022-07-20 02:07
Duplicate of #783

**Closed by MuntashirAkon** 2022-07-20 02:07 UTC
Labels: Bug, Duplicate, Severity: 1, Priority: 1
