### ISSUE TITLE
Detecting  App is Very Slow

### ISSUE THREAD

**Issue by Raif1** [MuntashirAkon/AppManager#694] opened 2022-03-06 08:51 UTC
- [x] I know what my device, OS and App Manager versions are
- [] I know how to take logs
- [x] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**
Takes unhumanely long to detect an installed app

**To Reproduce**
Steps to reproduce the behaviour:
1. Download and install app
2. Click on AppMamager
3. Cant see my newly installed app.

**Expected behavior**
I should find my newly installed app

**Screenshots**

**Crash logs**
If applicable, add crash logs to help us figure out the problem.

**Device info**
 - OS Version: [11]
 - App Manager Version: [latest Fdroid]
 - Mode: root

**Additional context**
It takes nearly a minute to detect newly installed apps any way to fix or make it quick ?

**Comment by MuntashirAkon** [comment] 2022-03-06 17:58
Duplicate of #430

**Closed by MuntashirAkon** 2022-03-06 17:58 UTC
Labels: bug, S3, P3
