### ISSUE TITLE
See which trackers are blocked or set on

### ISSUE THREAD

**Issue by Yoannjap** [MuntashirAkon/AppManager#719] opened 2022-04-01 12:40 UTC
- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

Hey,

It would be great to see, for each app, which trackers are set on, and which ones are set off.
This would let the user far more easily check and switch trackers on back one by one, when an app crashes after all trackers have been switched off.

Thanks in advance for having read my request,
Hope to see it considered ;)

Yoannjap

**Comment by MuntashirAkon** [comment] 2022-04-01 16:29
Duplicate of #699

**Comment by MuntashirAkon** [comment] 2022-04-01 16:29
Related issue #695

**Closed by MuntashirAkon** 2022-04-01 16:29 UTC
Labels: Duplicate, Feature, P3
