### ISSUE TITLE
Empty App Usage

### ISSUE THREAD

**Issue by metronightly** [MuntashirAkon/AppManager#800] opened 2022-07-11 09:04 UTC
- [x] I know what my device, OS and App Manager versions are
- [x] I know how to take logs
- [x] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**
I have given all necessary permission to AM, like usage access and accessibility permission but AM still returning no information on App Usage section 

**To Reproduce**
Steps to reproduce the behaviour:
1. Open App Manager
2. Click on 3 dot button
3. Select App Usage

**Expected behavior**
It should display app usage, like SoT etc

**Screenshots**
![Screenshot_2022-07-11-14-28-00-79_718a221d6c53e9d44e23988b91117061](https://user-images.githubusercontent.com/75716685/178228344-0edae55b-f1a7-41cf-bf01-c3848d9aa913.jpg)

**Device info**
 - Device: Realme C3
 - OS Version: Android 11
 - App Manager Version: 3.0.0-rc04 (406)
 - Mode: no-root

**Comment by MuntashirAkon** [comment] 2022-07-11 10:18
You have to install a debug build and send some logs before I can figure out what went wrong here.

**Comment by metronightly** [comment] 2022-07-11 10:23
I have no idea what that is, but I'm willing to help in whatever way I can.

**Comment by metronightly** [comment] 2022-07-11 10:38
Downloaded the latest apk from the telegram channel, here's the log file: 
[2022-07-11-16-05-57.am.log](https://github.com/MuntashirAkon/AppManager/files/9083204/2022-07-11-16-05-57.am.log)

**Comment by S7venLights** [comment] 2022-12-15 07:44
App Ussage widget is crashing on the latest App Manager Github version 3.10 alpha02

Crash report: 

java.lang.RuntimeException: Unable to start receiver io.github.muntashirakon.AppManager.usage.ScreenTimeAppWidget: java.lang.SecurityException: No permission to query usage stats for this user: uid 10102 does not have android.permission.INTERACT_ACROSS_USERS_FULL.
    at android.app.ActivityThread.handleReceiver(ActivityThread.java:4385)
    at android.app.ActivityThread.access$1600(ActivityThread.java:257)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2103)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7876)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ExecInit.main(ExecInit.java:48)
    at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
    at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
 Caused by: java.lang.SecurityException: No permission to query usage stats for this user: uid 10102 does not have android.permission.INTERACT_ACROSS_USERS_FULL.
   at android.os.Parcel.createExceptionOrNull(Parcel.java:2427)
   at android.os.Parcel.createException(Parcel.java:2411)
   at android.os.Parcel.readException(Parcel.java:2394)
   at android.os.Parcel.readException(Parcel.java:2336)
   at android.app.usage.IUsageStatsManager$Stub$Proxy.queryEventsForUser(IUsageStatsManager.java:931)
   at io.github.muntashirakon.AppManager.compat.UsageStatsManagerCompat.queryEvents(UsageStatsManagerCompat.java:32)
   at io.github.muntashirakon.AppManager.usage.AppUsageStatsManager.getUsageStats(AppUsageStatsManager.java:185)
   at io.github.muntashirakon.AppManager.usage.ScreenTimeAppWidget.updateAppWidget(ScreenTimeAppWidget.java:41)
   at io.github.muntashirakon.AppManager.usage.ScreenTimeAppWidget.onUpdate(ScreenTimeAppWidget.java:96)
   at android.appwidget.AppWidgetProvider.onReceive(AppWidgetProvider.java:66)
   at android.app.ActivityThread.handleReceiver(ActivityThread.java:4376)
   at android.app.ActivityThread.access$1600(ActivityThread.java:257)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2103)
   at android.os.Handler.dispatchMessage(Handler.java:106)
   at android.os.Looper.loopOnce(Looper.java:201)
   at android.os.Looper.loop(Looper.java:288)
   at android.app.ActivityThread.main(ActivityThread.java:7876)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
   at com.android.internal.os.ExecInit.main(ExecInit.java:48)
   at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
   at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)

Device Info:
App version: 3.1.0-alpha02
App version code: 415
Android build version: 2022112800
Android release version: 12
Android SDK version: 32
Android build ID: SP1A.210812.016.C2.2022112800
Device brand: google
Device manufacturer: Google
Device name: blueline
Device model: Pixel 3
Device product name: blueline
Device hardware name: blueline
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-US
In-App Language: auto
Mode: auto
Inferred Mode: no_root

**Comment by MuntashirAkon** [comment] 2022-12-16 00:16
> App Ussage widget is crashing on the latest App Manager Github version 3.10 alpha02

This is a different issue and fixed in 5ced904a7225f79985bd1a55095bba23126b619c

**Comment by MuntashirAkon** [comment] 2023-03-08 07:12
@metronightly: Can you take logs again from the latest debug?

**Comment by metronightly** [comment] 2023-03-08 07:43
> @metronightly: Can you take logs again from the latest debug?

On the latest debug version from telegram, app usage shows up perfectly.
![Screenshot_2023-03-08-13-13-19-25_7036e97d057c640af5e19886b605c25a](https://user-images.githubusercontent.com/75716685/223651817-24e5d490-6e2b-4813-8177-31c36f6d2038.jpg)


Here's the log anyway: 
[2023-03-08-13-07-05.am.log](https://github.com/MuntashirAkon/AppManager/files/10918325/2023-03-08-13-07-05.am.log)

**Comment by metronightly** [comment] 2023-03-08 07:48
> @metronightly: Can you take logs again from the latest debug?

Hey I also updated to 3.0.4 from github release and app usage shows up there too. Seems like the issue has been fixed.

**Closed** 2023-03-08 15:26 UTC
Labels: Bug, Status: Pending, More Info Needed, Priority: 3
