### ISSUE TITLE
Show Actions in the Receivers tab

### ISSUE THREAD

**Issue by Nill53** [MuntashirAkon/AppManager#901] opened 2022-10-23 23:02 UTC
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

Show a list of Actions for each Receiver in the receivers tab. Such as
android.intent.action.BOOT_COMPLETED
android.net.conn.CONNECTIVITY_CHANGE
etc.

**Comment by MuntashirAkon** [comment] 2022-10-24 02:38
Duplicate of #309

**Closed by MuntashirAkon** 2022-10-24 02:38 UTC
Labels: Duplicate, Feature
