### ISSUE TITLE
Work profile apps not shown in Profile seection

### ISSUE THREAD

**Issue by DreadedLama** [MuntashirAkon/AppManager#626] opened 2021-11-16 11:11 UTC
I want to create a profile to disable a few apps in my work profile. Though I can disable these apps directly by searching them in AM but I'm unable to find them in the profile section of AM. No work profile app is shown in AM profile.

**Comment by MuntashirAkon** [comment] 2021-11-16 14:36
Thanks for informing. I thought I added sufficient flags to display all the apps installed in the system. I will look into this. In the mean time, you can select and add them to your desired profile from the main page using the batch operation/selection mode.

**Comment by DreadedLama** [comment] 2021-11-16 15:22
Thanks for the workaround. Also is there any way to rename profiles, can't seem to find one.

**Comment by MuntashirAkon** [comment] 2021-11-24 16:25
> Also is there any way to rename profiles, can't seem to find one. My current workaround is to create a duplicate of the profile and set the name to my desired name.

That's the intended behaviour.

**Comment by MuntashirAkon** [comment] 2021-11-24 16:25
Fixed in 3c20599d

**Closed by MuntashirAkon** 2021-11-24 16:25 UTC
Labels: bug, S3, P3
