### ISSUE TITLE
Prevent app at start up

### ISSUE THREAD

**Issue by fusionneur** [MuntashirAkon/AppManager#478] opened 2021-06-13 21:19 UTC
Is it possible to prevent an app from starting at phone startup via AM? For example to prevent spotify running in background (also a notification appears)

**Comment by MuntashirAkon** [comment] 2021-06-14 05:07
Currently, AM doesn't provide an option to see which app _broadcast_ components run at startup (#309). However, you can look at the broadcasts tab and block any component there. It's usually called startup receiver or something similar.

**Comment by MuntashirAkon** [comment] 2021-06-14 05:08
Duplicate of #316

**Closed by MuntashirAkon** 2021-06-14 05:08 UTC
Labels: help wanted

**Comment by fusionneur** [comment] 2021-06-14 10:00
For broadcast tab, you mean the receivers tab ? thanks

**Comment by MuntashirAkon** [comment] 2021-06-14 10:18
> For broadcast tab, you mean the receivers tab ?

Yes.
