### ISSUE TITLE
Cannot open via root

### ISSUE THREAD

**Issue by anurag565** [MuntashirAkon/AppManager#1360] opened 2024-04-21 12:12 UTC
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

After clicking on Root mode of operation, it says unable to use current mode of operation. Even Magisk popup wont show. But next time when i tried to restart app, its stuck on front page as shown in image but this time magisk popup came and after giving permission, it said same thing, unable to use current mode of operation. On another restart, well this time it opens but in non root condition and when tried again to open as root, same error message. 
![Screenshot_20240421_173031_App Manager](https://github.com/MuntashirAkon/AppManager/assets/143786347/2c65e8db-ab23-42fc-9652-bd65f702a06f)
![Screenshot_20240421_173152_App Manager](https://github.com/MuntashirAkon/AppManager/assets/143786347/e0964571-c308-4216-88e2-17d7dcabf7c0)

### To Reproduce

Go to settings 
Then mode of operation 
Then tap root and it shows error in my phone.

### Device info

- Device: M13 5G
- OS Version: A14, One UI 6.0
- App Manager Version: 3.1.6
- Mode: Root/ADB/NonRoot: Root

### Additional context

Even previous version had this bug and i think One UI 6.0 is too buggy

**Comment by username-is-not** [comment] 2024-05-14 13:30
> 
> Even previous version had this bug and i think One UI 6.0 is too buggy

Seems to local issue, as you seem know. ^^ It may not even be a program issue?.. aanyway

**Comment by MuntashirAkon** [comment] 2024-07-11 19:17
Duplicate of #1312

**Closed by MuntashirAkon** 2024-07-11 19:17 UTC
Labels: Bug

**Comment by anurag565** [comment] 2024-08-14 03:50
> > 
> > Even previous version had this bug and i think One UI 6.0 is too buggy
> 
> Seems to local issue, as you seem know. ^^ It may not even be a program issue?.. aanyway
> 
> **EDIT**: Ugh, you should add a logcat, right

Only if i knew how to

**Comment by MuntashirAkon** [comment] 2024-09-02 05:19
> > > Even previous version had this bug and i think One UI 6.0 is too buggy
> > 
> > 
> > Seems to local issue, as you seem know. ^^ It may not even be a program issue?.. aanyway
> > **EDIT**: Ugh, you should add a logcat, right
> 
> Only if i knew how to

But you checked “I know how to take logs”.

**Comment by anurag565** [comment] 2024-09-02 07:07
> > > > Even previous version had this bug and i think One UI 6.0 is too buggy
> > > 
> > > 
> > > Seems to local issue, as you seem know. ^^ It may not even be a program issue?.. aanyway
> > > **EDIT**: Ugh, you should add a logcat, right
> > 
> > Only if i knew how to
> 
> But you checked “I know how to take logs”.
Maybe it didn't allow me to post without checking it✅️
