### ISSUE TITLE
App info Page

### ISSUE THREAD

**Issue by ParryShah** [MuntashirAkon/AppManager#1206] opened 2023-09-29 15:59 UTC
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

App info page are got slow in loading...
Take more to load info and all other storage details and lagging on info page.

### Device info

- Device:
- OS Version:
- App Manager Version:
- Mode: Root/ADB/NonRoot

**Comment by ParryShah** [comment] 2023-09-30 06:31
![Screenshot_2023-09-30-11-59-09-04](https://github.com/MuntashirAkon/AppManager/assets/42093168/49e620c0-1956-4b0f-a208-1a951396f385)

Showing double option

**Comment by MuntashirAkon** [comment] 2023-09-30 07:37
> Showing double option

Duplicate of #1187

**Comment by ParryShah** [comment] 2023-09-30 12:16
> > Showing double option
> 
> Duplicate of #1187

There is some glitch in UI also..
While scrolling, progress bar also stuck sometimes..
Before this can see smooth scroll and in other operation also...

**Comment by MuntashirAkon** [comment] 2023-09-30 16:45
> There is some glitch in UI also..
> While scrolling, progress bar also stuck sometimes..
> Before this can see smooth scroll and in other operation also...

Not sure what you're talking about. But it appears there might be some glitch in A12+ (don't know why because older versions work fine). The thing about App Details page is that it loads hundreds of information and there are a lot of processing needs to be done in the main thread which might be causing the glitch and freezing issues. These issues will be gradually fixed in the upcoming testing releases.

**Comment by MuntashirAkon** [comment] 2023-09-30 23:14
> I have exactly the same problem, but with A11

This is part of #1187, not this issue. As I commented somewhere, it's caused by a bug in the Android framework and a workaround is needed.

**Comment by ParryShah** [comment] 2023-10-01 05:30
> > I have exactly the same problem, but with A11
> 
> This is part of #1187, not this issue. As I commented somewhere, it's caused by a bug in the Android framework and a workaround is needed.

I think Fixed after latest debug update...

**Comment by MuntashirAkon** [comment] 2023-10-01 06:00
> I think Fixed after latest debug update...

That's v3.1.x, not v4.x.x.

**Comment by ParryShah** [comment] 2023-10-01 10:38
> > I think Fixed after latest debug update...
> 
> That's v3.1.x, not v4.x.x.

Oohhh Sorry my bad...

**Comment by ParryShah** [comment] 2023-10-06 20:23
> > I think Fixed after latest debug update...
> 
> That's v3.1.x, not v4.x.x.

Why there is UI smoothness difference between released 3.1.3 buid and 3.1.3 debug builds??

I feel 3.1.3 released buid is much smoother in UI animations and load faster pages..
Like app info, app list, profile, Running apps..

**Comment by MuntashirAkon** [comment] 2023-10-07 01:45
> Why there is UI smoothness difference between released 3.1.3 buid and 3.1.3 debug builds??

This is expected. Debug builds contain debug symbols and write a lot of logs.

**Comment by MuntashirAkon** [comment] 2024-07-08 20:13
I am unable to reproduce it anymore in the latest builds. @ParryShah: Can you still reproduce it?

**Comment by MuntashirAkon** [comment] 2024-07-08 22:18
Fixed via bb8dd18ad7db1bb8bec76bca49b1b755f03036bb

**Closed by MuntashirAkon** 2024-07-08 22:18 UTC
Labels: Bug
