### ISSUE TITLE
Runnings Apps showing only AppManager and reporting erronous scrollbars

### ISSUE THREAD

**Issue by Porkepix** [MuntashirAkon/AppManager#1263] opened 2023-12-29 22:53 UTC
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Runnings Apps section only shows AppManager itself. This could be normal as, according to the doc, "If root or ADB is not available to App Manager, it only displays itself in the recent versions of Android.".
I'll guess Android Oreo (8.0) despite quite old is recent enough for that part, despite being quite old now. The phone use unrooted stock ROM. However I'm not sure what I should understand by "if ADB is not available": developer mode is enabled, and I quite often use `adb logcat` to provide debug information to application developers.

Anyhow, even if what I see under these circumstances is considered as normal, the states of scrollbars there certainly isn't, see screenshot below.

### To Reproduce

Just go to Running Apps

### Expected behavior

I should see more (and if the Android version and circumstances doesn't allow for more, I think an information message would be welcome).

### Screenshots

<details>
<summary>
Screenshot
</summary>

![Screenshot_20231229-231823](https://github.com/MuntashirAkon/AppManager/assets/709500/80d07d6d-6a53-4592-8502-b5a79014a031)

</details>
See how the scrollbars are; I'm scrolled at the most I can at the bottom, I can't go below that. Scrollbars shouldn't be in that state.

### Device info

- Device: Sony Xperia XZ
- OS Version: Android Oreo (8.0)
- App Manager Version: 3.1.4
- Mode: NonRoot

### Additional context

I've seen a couple of issues that could be related/the same, but considering I was quite unsure, and there was the scrollbars issue beside it, I opted for opening that one; feel free to dupe if needed.

EDIT: Toggling "Apps" of "User Apps" from the flag icon doesn't change anything (it's also unclear what's the use for these, maybe this could be made more obvious, I don't know?)

**Comment by MuntashirAkon** [comment] 2023-12-30 04:46
> However I'm not sure what I should understand by "if ADB is not available": developer mode is enabled, and I quite often use `adb logcat` to provide debug information to application developers.

In this case, it means "If App Manager is not running in ADB over TCP mode". The reason we used “if” and not “when” was because this is not always correct. Some choose to modify the SELinux context to allow third-party app access those files.

> Toggling "Apps" of "User Apps" from the flag icon doesn't change anything (it's also unclear what's the use for these, maybe this could be made more obvious, I don't know?)

It would be clear if you could see the list. Although it says “Running apps”, it actually lists all the running processes, not just the Android apps. We choose “apps” instead of “processes” as most people are familiar with the former than the latter.

> I've seen a couple of issues that could be related/the same, but considering I was quite unsure, and there was the scrollbars issue beside it, I opted for opening that one; feel free to dupe if needed.

Duplicate of #428

Unfortunately, fast scrollers do not work as expected if the height of the items in a list are uneven. You have only Android to blame for it though.

> Note that the Log Viewer contains many many E/W/I/V and so on messages from AppManager, many of which I can't link to an issue I'm experiencing at first sight, but that should nonetheless taken care of I think. Should an issue be reported for all of them?

Ideally, when you report an issue, you should include everything you can accumulate. It should be the job of the developers to find the needle(s) they're looking for in the haystack. Now, a user familiar with the technology may be able to come up with a more specific set of data. But we do not expect it from most users.

> For this purpose, some "de-dupe" feature would also be nice where log viewer would discard any duplicate error message and show a single copy of any different ones, to have an overview.

It can log duplicate messages for different reasons. Attempting to reduce it may also reduce the info gain, and potentially making it impossible to detect the issue in first place. Developers usually have specific filters or apps that allows them figure out the issue from the log file even if it contains thousands of log entries.

**Closed by MuntashirAkon** 2023-12-30 04:46 UTC
Labels: Bug, Duplicate

**Comment by MuntashirAkon** [comment] 2023-12-30 19:45
> I've no real issues (as in, I encounter a problem) for most of this, but I also think most of these logs shouldn't be there, so do I open an issue for these, one issue for any different log entry?

Again, it should be up to the developer, not the user. In my own experience, a mere timestamp once solved an intermittent issue. Unless you know what you're doing, you should not insert or delete anything from the logs, other than masking potentially private information (App Manager has an option to enable that). Since you are not a developer, the way you process the data may not be the same as a developer. So, what may be useless to you could be useful to the developer. Also, developers do not usually log useless stuff (unless they're really bad developers).
