### ISSUE TITLE
if in the poor network, APP launch will consumes very very long time. and other crash.

### ISSUE THREAD

**Issue by lshilshi** [MuntashirAkon/AppManager#370] opened 2021-04-12 05:17 UTC
Device info

Device: One Plus 7 Pro
OS Version: Android 9（H2OS）
App Manager Version: v2.5.21-pre~v2.5.24-pre
Mode: root
Additional context
if in the poor network,
APP launch will consumes very very long time.

Crashes randomly during use, especially when applying component/rule operations
Attached below are saved Logs.

[Log_1617409729636.txt](https://github.com/MuntashirAkon/AppManager/files/6294092/Log_1617409729636.txt)
[Log_1617663803655.txt](https://github.com/MuntashirAkon/AppManager/files/6294093/Log_1617663803655.txt)
[Log_1618029703464.txt](https://github.com/MuntashirAkon/AppManager/files/6294094/Log_1618029703464.txt)
[logcat_04-08-2021_21-42-47.txt](https://github.com/MuntashirAkon/AppManager/files/6294095/logcat_04-08-2021_21-42-47.txt)
[Log_1617889701095.txt](https://github.com/MuntashirAkon/AppManager/files/6294096/Log_1617889701095.txt)

**Comment by MuntashirAkon** [comment] 2021-04-12 13:43
Thanks for reporting, the first issue should be fixed in a previous version. The last 4 logs represent the same issue which hasn't been fixed yet.

**Comment by MuntashirAkon** [comment] 2021-04-21 08:56
The last 4 logs (which represent the same issue) aren't reproducible. It would be better if you shared how to reproduce them or use one of the debug builds to take logs.

**Comment by lshilshi** [comment] 2021-04-24 04:49
> The last 4 logs (which represent the same issue) aren't reproducible. It would be better if you shared how to reproduce them or use one of the debug builds to take logs.

Crashes randomly when applying component/rule operations.

e.g.  app XXXX runs exceptions after applying rules
so I need to revoke component/rule operations
or
batch apply component/rule operations

both of the above，highly susceptible to the crash logs above.

**Comment by MuntashirAkon** [comment] 2021-04-24 05:12
> Crashes randomly when applying component/rule operations.
> 
> e.g. app XXXX runs exceptions after applying rules
> so I need to revoke component/rule operations
> or
> batch apply component/rule operations
> 
> both of the above，highly susceptible to the crash logs above.

You've already said that above. But I cannot reproduce the issue on my device, so I need additional logs, current mode of operation, etc. in order to figure out the actual problem.

**Comment by lshilshi** [comment] 2021-04-29 14:33
> > Crashes randomly when applying component/rule operations.
> > e.g. app XXXX runs exceptions after applying rules
> > so I need to revoke component/rule operations
> > or
> > batch apply component/rule operations
> > both of the above，highly susceptible to the crash logs above.
> 
> You've already said that above. But I cannot reproduce the issue on my device, so I need additional logs, current mode of operation, etc. in order to figure out the actual problem.

[logcat_04-29-2021_07-36-32.txt](https://github.com/MuntashirAkon/AppManager/files/6399401/logcat_04-29-2021_07-36-32.txt)
Are these log helpful？

**Comment by MuntashirAkon** [comment] 2021-04-29 15:03
> [logcat_04-29-2021_07-36-32.txt](https://github.com/MuntashirAkon/AppManager/files/6399401/logcat_04-29-2021_07-36-32.txt)

Which version of AM is this?

> Are these log helpful？

Don't use any filter. Not even PID filter.

**Comment by lshilshi** [comment] 2021-05-06 01:33
> Which version of AM is this?

The AM version at that time was 2.5.24.



> Don't use any filter. Not even PID filter.

ok！Wait for me next time.

**Comment by MuntashirAkon** [comment] 2021-05-31 15:52
Closed due to lack of response. Feel free to open it again if you're still facing the issue.

**Closed by MuntashirAkon** 2021-05-31 15:52 UTC
Labels: P3, S3, bug, info-needed
