### ISSUE TITLE
Shizuku API

### ISSUE THREAD

**Issue by Dantoza** [MuntashirAkon/AppManager#1468] opened 2024-11-15 06:44 UTC
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

It would be really nice to get a shizuku mode working.

**Comment by MuntashirAkon** [comment] 2024-11-16 17:21
Duplicate of #55

**Closed by MuntashirAkon** 2024-11-16 17:21 UTC
Labels: Duplicate, Feature
