### ISSUE TITLE
App crash on Chinese programs

### ISSUE THREAD

**Issue by odkate** [MuntashirAkon/AppManager#1007] opened 2023-02-22 21:54 UTC
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

The application crashes when you click on a program with Chinese characters in the name
This program is NP Manager

### Logs

`java.lang.RuntimeException: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean io.github.muntashirakon.AppManager.apk.ApkFile.isSplit()' on a null object reference
    at io.github.muntashirakon.AppManager.details.info.AppInfoViewModel.lambda$loadTagCloud$0(AppInfoViewModel.java:216)
    at io.github.muntashirakon.AppManager.details.info.AppInfoViewModel$$ExternalSyntheticLambda0.run(Unknown Source:2)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:193)
    at android.app.ActivityThread.main(ActivityThread.java:6739)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:859)
 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean io.github.muntashirakon.AppManager.apk.ApkFile.isSplit()' on a null object reference
   at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.getSplitCount(AppDetailsViewModel.java:978)
   at io.github.muntashirakon.AppManager.details.info.AppInfoViewModel.loadTagCloud(AppInfoViewModel.java:135)
   at io.github.muntashirakon.AppManager.details.info.AppInfoFragment.loadPackageInfo(AppInfoFragment.java:1531)
   at io.github.muntashirakon.AppManager.details.info.AppInfoFragment.$r8$lambda$oxlKbqiAsxIkEG69gntC-jrgnXk(Unknown Source:0)
   at io.github.muntashirakon.AppManager.details.info.AppInfoFragment$$ExternalSyntheticLambda104.run(Unknown Source:2)
   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
   at java.lang.Thread.run(Thread.java:764)`

### Device info

Device Info:
App version: 3.0.4
App version code: 416
Android build version: d8b732e824
Android release version: 9
Android SDK version: 28
Android build ID: PQ1A.190105.004
Device brand: samsung
Device manufacturer: samsung
Device name: ks01lte
Device model: GT-I9506
Device product name: ks01ltexx
Device hardware name: qcom
ABIs: [armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): []
System language: uk-UA
In-App Language: auto
Mode: root
Inferred Mode: root

**Comment by gnuhead-chieb** [comment] 2023-02-23 06:31
https://github.com/MuntashirAkon/AppManager/issues/951

**Comment by MuntashirAkon** [comment] 2023-02-23 08:45
Duplicate of #951

**Closed by MuntashirAkon** 2023-02-23 08:45 UTC
Labels: Bug
