### ISSUE TITLE
SSAID  not shown up in Android 12

### ISSUE THREAD

**Issue by RanitalD** [MuntashirAkon/AppManager#631] opened 2021-11-19 18:00 UTC
- [x] I know what my device, OS and App Manager versions are
- [ ] I know how to take logs
- [ ] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behavior**

**Screenshots**

**Crash logs**
If applicable, add crash logs to help us figure out the problem.

**Device info**
 - Device: [e.g. One Plus 8 Pro]
 - OS Version: [e.g. Android 10]
 - App Manager Version: [e.g. v2.5.13]
 - Mode: root/adb/no-root

**Additional context**

**Comment by MuntashirAkon** [comment] 2021-11-20 15:33
Duplicate of #457

**Closed by MuntashirAkon** 2021-11-20 15:33 UTC
Labels: bug, S3, P3
