### ISSUE TITLE
App list crash on Android 13 beta 4

### ISSUE THREAD

**Issue by craigacgomez** [MuntashirAkon/AppManager#811] opened 2022-07-23 00:19 UTC
**Describe the bug**
The initial app list screen in App Manager is unable to populate the list of applications on Android 13 beta 4, and after a few seconds, the app crashes.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open AppManager
2. Wait for AppManager to attempt to populate the app list
3. Notice that it takes longer than usual, and crashes after a few seconds 

**Expected behavior**
App list is populated and populated and the application does not crash

**Crash logs**
```
java.lang.NoSuchMethodError: No interface method getPackageInfo(Ljava/lang/String;II)Landroid/content/pm/PackageInfo; in class Landroid/content/pm/IPackageManager; or its super classes (declaration of 'android.content.pm.IPackageManager' appears in /system/framework/framework.jar)
    at io.github.muntashirakon.AppManager.servermanager.PackageManagerCompat.getPackageInfo(PackageManagerCompat.java:105)
    at io.github.muntashirakon.AppManager.main.MainViewModel.getNewApplicationItem(MainViewModel.java:582)
    at io.github.muntashirakon.AppManager.main.MainViewModel.updateInfoForPackages(MainViewModel.java:499)
    at io.github.muntashirakon.AppManager.main.MainViewModel.updateInfoForUid(MainViewModel.java:459)
    at io.github.muntashirakon.AppManager.main.MainViewModel.access$000(MainViewModel.java:60)
    at io.github.muntashirakon.AppManager.main.MainViewModel$PackageIntentReceiver.onPackageChanged(MainViewModel.java:722)
    at io.github.muntashirakon.AppManager.types.PackageChangeReceiver$ReceiverHandler.handleMessage(PackageChangeReceiver.java:94)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.os.HandlerThread.run(HandlerThread.java:67)

Device Info:
App version: 2.6.5.1
App version code: 397
Android build version: 8812298
Android release version: 13
Android SDK version: 33
Android build ID: TPB4.220624.005
Device brand: google
Device manufacturer: Google
Device name: raven
Device model: Pixel 6 Pro
Device product name: raven
Device hardware name: raven
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-US
In-App Language: auto
Mode: auto
```

**Device info**
 - Device: Google Pixel 6 Pro
 - OS Version: Android 13 beta 4
 - App Manager Version: 2.6.5.1 up to 3.0.0rc4
 - Mode: root (Magisk 25.2)

**Additional context**
I have not tested this with earlier pre-releases of Android 13

**Comment by MuntashirAkon** [comment] 2022-07-23 00:47
Duplicate of #738

**Closed by MuntashirAkon** 2022-07-23 00:47 UTC
Labels: Bug, Duplicate
