### ISSUE TITLE
[Feature] Per-app ability to clear-cache within App Manager

### ISSUE THREAD

**Issue by Coldblackice** [MuntashirAkon/AppManager#1219] opened 2023-10-09 00:48 UTC
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

I often need to close apps and clear their caches individually, and presently am only able to do so via apps' system-info OS pages (i.e. "App Info -> Storage -> Clear Cache").

### Describe the solution you'd like

It would be **phenomenal** if app manager could add the ability to clear-cache of apps individually _from within App Manager_, without needing to switch out to apps' OS info pages, tabbing away from App Manager.

I know App Manager has the "1-click Ops" function to "Trim all caches", but obviously this nukes all app caches at once.

Having this ability to do so in App Manager would be extremely useful, and/or with an API/intent to trigger externally by Tasker, for example. Though primary interest would be something like a "Clear Cache" button in App Manager next to the "Clear Data" buttons on app pages, for example, and/or accessible via the app list triple-dot menu, unlocking a batch-select ability to clear caches without nuking all of them.

(No complaints, either: App Manager is easily one of my most utilized, relied upon apps!)

### Describe alternatives you've considered

The only other alternative that comes close to this is SD Maid, however that app does this via accessibility input automation, switching in and out of each app's OS info page, scripting the input actions to clear-cache for each.

### Additional context

Currently using AppManager v4.0.0-alpha02 on Android 13 / Samsung OneUI 5.1, unrooted, using ADB/wireless debug mode

**Comment by shuvashish76** [comment] 2023-10-09 03:13
1. 1-Click Ops Page > [Trim Caches in All Apps](https://muntashirakon.github.io/AppManager/en/#subsec:trim-caches-in-all-apps) - only works in root or ADB mode
2. - App Details Page > App Info Tab > [Horizontal Action Panel](https://muntashirakon.github.io/AppManager/en/#subsubsec:horizontal-action-panel) > Clear Cache
   - Main Page > [Batch Operations](https://muntashirakon.github.io/AppManager/en/#subsec:batch-operations) > Clear Cache (both data/cache operations in a single "clear" option)
   Both works in root or ADB mode, also no-root mode (_experimental_) with accessibility service.

**Comment by MuntashirAkon** [comment] 2023-10-10 06:27
Duplicate of #962

**Comment by MuntashirAkon** [comment] 2023-10-10 06:28
See https://github.com/MuntashirAkon/AppManager/issues/962#issuecomment-1720739335 for details

**Closed by MuntashirAkon** 2023-10-10 06:28 UTC
Labels: Feature
