### ISSUE TITLE
can you add features to rekove dangerous permission

### ISSUE THREAD

**Issue by 1alexman1** [MuntashirAkon/AppManager#1287] opened 2024-02-03 11:14 UTC
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

App Manager is amazing and I am glad you have given us this marvelous app.
I tried to remove from my samsung, dangerous "android permission to gets my accounts", but it fails:
PS C:\Users\pc> adb shell pm revoke com.samsung.accessibility android.permission.GET_ACCOUNTS
Exception occurred while executing 'revoke':
java.lang.SecurityException: Non-System UID cannot revoke system fixed permission android.permission.GET_ACCOUNTS for package com.samsung.accessibility
        at com.android.server.pm.permission.PermissionManagerService.revokeRuntimePermissionInternal(PermissionManagerService.java:1740)
        at com.android.server.pm.permission.PermissionManagerService.revokeRuntimePermission(PermissionManagerService.java:1678)
        at com.android.server.pm.PackageManagerShellCommand.runGrantRevokePermission(PackageManagerShellCommand.java:2341)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:263)
        at android.os.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:98)
        at android.os.ShellCommand.exec(ShellCommand.java:44)
        at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:26739)
        at android.os.Binder.shellCommand(Binder.java:965)
        at android.os.Binder.onTransact(Binder.java:839)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:5206)
        at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:5332)
        at android.os.Binder.execTransactInternal(Binder.java:1195)
        at android.os.Binder.execTransact(Binder.java:1159)
Is it any other way to do it? Can you create a feature to allow or revoke these dangerous permissions detected by your app?
Thx

**Comment by MuntashirAkon** [comment] 2024-02-03 12:55
Duplicate of #1248

**Comment by MuntashirAkon** [comment] 2024-02-03 12:56
Please take a look at the linked issue for details regarding the revocation of permissions from the system applications. Thanks.

**Closed by MuntashirAkon** 2024-02-03 12:55 UTC
Labels: Duplicate, Feature
