### ISSUE TITLE
Make a test-only mod of app manager

### ISSUE THREAD

**Issue by sobaee** [MuntashirAkon/AppManager#689] opened 2022-03-01 23:07 UTC
- [x] I am using the latest version of App Manager
- [x] I have searched the issues and haven't found anything relevant

Hello dear developer

**Is your feature request related to a problem? Please describe.**
I suggest you make a test-only version of app manager with the ability to block trackers, activities and services of the apps and to do other non allowed actions for non rooted devices (blocker app "com.merxury.blocker" does that)

**Comment by gnuhead-chieb** [comment] 2022-03-12 02:51
seems duplicate of https://github.com/MuntashirAkon/AppManager/issues/511

already implemented on latest version

**Closed** 2022-03-14 18:19 UTC
Labels: Duplicate, Feature, P3

**Comment by sobaee** [comment] 2022-03-18 15:26
Nope
It's not duplicated with #511 
(Allow disabling components of test-only apps on ADB mode)

I need the app manager itself to be test-only app so I can install it by adb install -t. And then I can block activities or services of any other app using app manager (blocker app does that)


They are different things bro

**Comment by gnuhead-chieb** [comment] 2022-03-19 01:41
I read blocker's documentation, and it seems doesn't do such thing. I think you made misunderstanding.
Their documentation said you have to modify **apk of you want block component** to make it test-only **NOT apk of blocker app itself**.
https://github-com.translate.goog/lihenggui/blocker/wiki/%5B%E5%AE%9E%E9%AA%8C%E6%80%A7%E5%8A%9F%E8%83%BD%5D-%5B%E5%BC%80%E5%8F%91%E8%80%85%E5%90%91%5D%E5%A6%82%E4%BD%95%E5%85%8DRoot%E6%8E%A7%E5%88%B6%E5%BA%94%E7%94%A8%E7%A8%8B%E5%BA%8F%E7%BB%84%E4%BB%B6?_x_tr_sl=zh-CN&_x_tr_tl=en&_x_tr_hl=ja&_x_tr_pto=wapp

**Comment by sobaee** [comment] 2022-03-19 07:20
> I read blocker's documentation, and it seems doesn't do such thing. I think you made misunderstanding. Their documentation said you have to modify **apk of you want block component** to make it test-only **NOT apk of blocker app itself**. https://github-com.translate.goog/lihenggui/blocker/wiki/%5B%E5%AE%9E%E9%AA%8C%E6%80%A7%E5%8A%9F%E8%83%BD%5D-%5B%E5%BC%80%E5%8F%91%E8%80%85%E5%90%91%5D%E5%A6%82%E4%BD%95%E5%85%8DRoot%E6%8E%A7%E5%88%B6%E5%BA%94%E7%94%A8%E7%A8%8B%E5%BA%8F%E7%BB%84%E4%BB%B6?_x_tr_sl=zh-CN&_x_tr_tl=en&_x_tr_hl=ja&_x_tr_pto=wapp

I understand that we have to convert the blocker app first to test-only app (simply I did that with app cloner app) then install it, but after I did that I am able to disable activities and services

I tried to do the same with app manager (converted it to test-only app) then install it, but here I am not able to disable anything.

**Comment by gnuhead-chieb** [comment] 2022-03-19 08:32
The documentation doesn't require convert blocker app itself to test-only. Need to convert only target apps.
I tried with blocker app that converted to test-only but it wasn't worked at all.
so,I think you have granted root to blocker or it just bug.

**Comment by sobaee** [comment] 2022-03-19 09:05
No, sir, I don't have root.
I have blocker app with Shizuko (wireless ADB), and everything worked well after I converted blocker itself to a test-only app (not the target apps) and then install it by "adb install -t"
But before that it refused to work

![Screenshot_20220319120143](https://user-images.githubusercontent.com/65910585/159114844-203b6c01-8d59-4fb4-8047-d8d3f08e2f82.jpg)

This is an example (2nd line app) with ad service disabled (2nd line is not a test-only app, it just downloaded from Google play)
![Screenshot_20220319120125](https://user-images.githubusercontent.com/65910585/159114862-301f2de6-a857-4fbf-8220-2ac474f887c9.jpg)

**Comment by sobaee** [comment] 2022-03-19 09:18
What I need from AM is to be able to toggle (on, off) services and activities of other apps like blocker app does.

Blocker wouldn't be able to do that in non-rooted devices if there's no Shizuko and test-only version of blocker app itself installed.

This is the summary bro
