### ISSUE TITLE
can't uninstall

### ISSUE THREAD

**Issue by jawaaj** [MuntashirAkon/AppManager#465] opened 2021-06-02 19:07 UTC
**Describe your problem(s)**
I tried App Manager because it seems that it is a good App. But i don't really need it, so i wanted to uninstall App Manager. But every time i try this, the package installation crashes.

The App has no Admin and no permissions or anything. I already restarted my phone and tried to uninstall App Manager through Fdroid. Nothing worked.

Specs: 
Samsung S21 
Android 11
App Version 2.6.0 installed from Fdroid
I use the pre-installed package Installation
Device is not rooted 

PS: Sorry when my english is not the best. It's not my native language.

**Comment by Mtkmanjaro** [comment] 2021-06-02 23:26
you tried to uninstalling "AM aka app manager" from settings, i means setting/app search AM uninstall

**Comment by MuntashirAkon** [comment] 2021-06-02 23:29
Duplicate of #159

**Closed by MuntashirAkon** 2021-06-02 23:29 UTC
Labels: 3rd-party-issue, help wanted

**Comment by MuntashirAkon** [comment] 2021-06-02 23:31
It's an issue with your ROM. Contact your ROM developer so that they can fix it. In the mean time, you can use the instructions provided in the linked issue.
