### ISSUE TITLE
When executing block component on an application, it keeps crashing.

### ISSUE THREAD

**Issue by lshilshi** [MuntashirAkon/AppManager#569] opened 2021-09-02 14:02 UTC
- [ ] I know what my device, OS and App Manager versions are
- [ ] I know how to take logs
- [ ] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behavior**

**Screenshots**

**Crash logs**
If applicable, add crash logs to help us figure out the problem.

**Device info**
 - Device: [e.g. One Plus 8 Pro]
 - OS Version: [e.g. Android 10]
 - App Manager Version: [e.g. v2.5.13]
 - Mode: root/adb/no-root

**Additional context**

When executing  block component on an application, it keeps crashing and does not display the component disable status correctly. At the same time, the related /ifw and AM's own conf files are fine.
Please see the log for details.
[2021-09-02-21-38-38.log](https://github.com/MuntashirAkon/AppManager/files/7099451/2021-09-02-21-38-38.log)

**Comment by lshilshi** [comment] 2021-09-07 05:52
and the log of crash when install apks.
[fooViewSaveText_1630854344141.txt](https://github.com/MuntashirAkon/AppManager/files/7119207/fooViewSaveText_1630854344141.txt)

**Comment by MuntashirAkon** [comment] 2021-09-09 13:27
> and the log of crash when install apks.

Could be fixed in a80634f2

**Comment by MuntashirAkon** [comment] 2021-09-09 13:31
> When executing block component on an application, it keeps crashing and does not display the component disable status correctly. At the same time, the related /ifw and AM's own conf files are fine.

Could be fixed in 8ac3de4b.

**Comment by lshilshi** [comment] 2021-09-28 06:43
@MuntashirAkon until the newest version（v2.6.4）,it keeps crashing or does not display the component disable status correctly.
see the attachments
[fooViewSaveText_1632387003841.txt](https://github.com/MuntashirAkon/AppManager/files/7241629/fooViewSaveText_1632387003841.txt)

https://user-images.githubusercontent.com/36767310/135035421-e797e5bc-810b-45e8-9866-88086801e4f3.mp4

.

**Comment by lshilshi** [comment] 2021-11-06 14:12
@MuntashirAkon I hope these are helpful for bug debugging.

After installation, the bug information after clicking the shortcut button of AMM
[fooViewSaveText_1635687650222.txt](https://github.com/MuntashirAkon/AppManager/files/7490519/fooViewSaveText_1635687650222.txt)

UID changes after refresh，Why？
https://user-images.githubusercontent.com/36767310/140611522-db084d70-5edb-4bb0-aae4-a6cad5c99ce6.mp4

**Comment by lshilshi** [comment] 2021-11-06 14:44
@MuntashirAkon Components cannot be displayed and operated correctly.
https://user-images.githubusercontent.com/36767310/140613335-7a2635ba-73fc-4171-9a06-cfed51e63c5c.mp4

**Comment by MuntashirAkon** [comment] 2021-11-06 15:35
> After installation, the bug information after clicking the shortcut button of AMM
> [fooViewSaveText_1635687650222.txt](https://github.com/MuntashirAkon/AppManager/files/7490519/fooViewSaveText_1635687650222.txt)

> Components cannot be displayed and operated correctly.

These logs/videos won't do it. You have to take logs using logcat as I've stated in the earlier comments. I have to figure out precisely what happened here. Note that none of your reported issues are reproducible on my device on both v2.6.4 and v2.7.0 (debug).

> UID changes after refresh，Why？

No idea. Never reported by anyone before, and never happened on my side. The only way I can think of is to run Android 9 on a VM and check this out myself.

**Comment by lshilshi** [comment] 2021-11-07 14:31
> These logs/videos won't do it. You have to take logs using logcat as I've stated in the earlier comments. I have to figure out precisely what happened here. Note that none of your reported issues are reproducible on my device on both v2.6.4 and v2.7.0 (debug).

how to logcat? Is enough or not by system logcat? need AM filter?


> No idea. Never reported by anyone before, and never happened on my side. The only way I can think of is to run Android 9 on a VM and check this out myself.

Is it related to the parallel apps of oneplus? and It‘s none now.

**Comment by MuntashirAkon** [comment] 2021-11-08 02:14
> Is it related to the parallel apps of oneplus? and It‘s none now.

Could be. Parallel apps have different UID's. So, AM got confused.

> how to logcat? Is enough or not by system logcat? need AM filter?

You can use any logcat viewr (AM also has a viewer but since AM crashes, it won't work). No need to filter anything. However, some viewer (matlog/catlog) is able to delete phone numbers and urls. You may want to try them instead.

**Comment by lshilshi** [comment] 2021-11-08 05:28
> Could be. Parallel apps have different UID's. So, AM got confused.

Click the app  in onboard packages interface, the select user pop-up window will appear mostly.
But my Parallel apps list is empty now.

**Closed** 2022-04-04 11:00 UTC
Labels: Bug, More Info Needed, S3, P3
