### ISSUE TITLE
Run simple adb commands?

### ISSUE THREAD

**Issue by orschiro** [MuntashirAkon/AppManager#704] opened 2022-03-14 12:47 UTC
Hi all, 

Given that AppManager operates in adb mode, can it maybe have a feature to run simple adb commands, such as:

    adb tcpip 5555

What do you think?

Thanks!

**Comment by MuntashirAkon** [comment] 2022-03-14 14:52
Duplicate of #23

**Closed by MuntashirAkon** 2022-03-14 14:52 UTC
Labels: feature, P3
