### ISSUE TITLE
App Crashing a lot 

### ISSUE THREAD

**Issue by Raif1** [MuntashirAkon/AppManager#690] opened 2022-03-03 13:47 UTC
- [x] I know what my device, OS and App Manager versions are
- [x] I know how to take logs
- [x] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**

App Crashes very often when i try to unlock or do something .

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Open app manager and unlock'
2. Click on '..Trying type my pass ..'
3. Scroll down to '..Carshed ..'

**Expected behavior**

I was supposed to enter app manager and do my things 

**Screenshots**
None 
**Crash logs**
If applicable, add crash logs to help us figure out the problem.

java.lang.RuntimeException: Parcel android.os.Parcel@6ebe5bd: Unmarshalling unknown type code 6881399 at offset 1612
    at android.os.Parcel.readValue(Parcel.java:3253)
    at android.os.Parcel.readSparseArrayInternal(Parcel.java:3650)
    at android.os.Parcel.readSparseArray(Parcel.java:2792)
    at android.os.Parcel.readValue(Parcel.java:3231)
    at android.os.Parcel.readArrayMapInternal(Parcel.java:3567)
    at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
    at android.os.BaseBundle.unparcel(BaseBundle.java:236)
    at android.os.Bundle.getSparseParcelableArray(Bundle.java:1079)
    at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2181)
    at android.app.Activity.onRestoreInstanceState(Activity.java:1679)
    at android.app.Activity.performRestoreInstanceState(Activity.java:1632)
    at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1356)
    at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3473)
    at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
    at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:223)
    at android.app.ActivityThread.main(ActivityThread.java:7664)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

Device Info:
App version: 3.0.0-alpha01
App version code: 400
Android build version: eng.crossg.20220120.182016
Android release version: 11
Android SDK version: 30
Android build ID: lineage_treble_a64_bvS-userdebug 11 RQ3A.211001.001 eng.crossg.20220120.182016 test-keys
Device brand: Phh
Device manufacturer: unknown
Device name: phhgsi_a64_ab
Device model: Phh-Treble vanilla
Device product name: lineage_treble_a64_bvS
Device hardware name: exynos7904
ABIs: [armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): []
System language: en-GB
In-App Language: auto
Mode: auto.

**_Guess im doxing myself_**

**Additional context**
One  thing this was not happening before . But when i gave the app internet access it started crashing......

**Comment by MuntashirAkon** [comment] 2022-03-03 14:56
Duplicate of #656

**Closed by MuntashirAkon** 2022-03-03 14:56 UTC
Labels: bug, S3, P3
