### ISSUE TITLE
AppManager crashes when wireless debugging mode when selecting apps

### ISSUE THREAD

**Issue by ghost** [MuntashirAkon/AppManager#884] opened 2022-09-30 12:57 UTC
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Installed AppManager from F-Droid, I was trying to disable or uninstall apps using this tool through wireless debugging but it crashes when I tap specific app to perform operations. However if normal mode was used then I was able to see app's details without crashes.

### To Reproduce

- 1. Open AppManager 
- 2. Change the mode of operation to "Wireless debugging" in settings
- 3. Select any app after connection 
- 4. Possible crash may happen 

### Expected behavior

It shouldn't crash and should get into app details

### Screenshots

Some video recording:

https://user-images.githubusercontent.com/113356647/193273737-e9c3a56d-280d-49ab-88e5-e6f9c47cbb9d.mp4

### Logs

Additional logs reported by the app:
<details>
<summary>Logs:</summary>
java.lang.RuntimeException: Unable to start activity ComponentInfo{io.github.muntashirakon.AppManager/io.github.muntashirakon.AppManager.details.AppDetailsActivity}: java.lang.RuntimeException: Cannot create an instance of class io.github.muntashirakon.AppManager.details.AppDetailsViewModel
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3720)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3887)
    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:140)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:100)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2317)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:263)
    at android.app.ActivityThread.main(ActivityThread.java:8292)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
 Caused by: java.lang.RuntimeException: Cannot create an instance of class io.github.muntashirakon.AppManager.details.AppDetailsViewModel
   at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:320)
   at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:304)
   at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:278)
   at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.kt:128)
   at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:187)
   at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:153)
   at io.github.muntashirakon.AppManager.details.AppDetailsActivity.onAuthenticated(AppDetailsActivity.java:93)
   at io.github.muntashirakon.AppManager.BaseActivity.onCreate(BaseActivity.java:65)
   at android.app.Activity.performCreate(Activity.java:8146)
   at android.app.Activity.performCreate(Activity.java:8130)
   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1310)
   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3689)
   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3887)
   at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
   at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:140)
   at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:100)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2317)
   at android.os.Handler.dispatchMessage(Handler.java:106)
   at android.os.Looper.loop(Looper.java:263)
   at android.app.ActivityThread.main(ActivityThread.java:8292)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
 Caused by: java.lang.reflect.InvocationTargetException
   at java.lang.reflect.Constructor.newInstance0(Native Method)
   at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
   at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:312)
   at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:304)
   at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:278)
   at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.kt:128)
   at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:187)
   at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:153)
   at io.github.muntashirakon.AppManager.details.AppDetailsActivity.onAuthenticated(AppDetailsActivity.java:93)
   at io.github.muntashirakon.AppManager.BaseActivity.onCreate(BaseActivity.java:65)
   at android.app.Activity.performCreate(Activity.java:8146)
   at android.app.Activity.performCreate(Activity.java:8130)
   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1310)
   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3689)
   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3887)
   at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
   at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:140)
   at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:100)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2317)
   at android.os.Handler.dispatchMessage(Handler.java:106)
   at android.os.Looper.loop(Looper.java:263)
   at android.app.ActivityThread.main(ActivityThread.java:8292)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
 Caused by: java.lang.SecurityException: grantRuntimePermission: Neither user 2000 nor current process has android.permission.GRANT_RUNTIME_PERMISSIONS.
   at android.os.Parcel.createExceptionOrNull(Parcel.java:2389)
   at android.os.Parcel.createException(Parcel.java:2373)
   at android.os.Parcel.readException(Parcel.java:2356)
   at android.os.Parcel.readException(Parcel.java:2298)
   at android.permission.IPermissionManager$Stub$Proxy.grantRuntimePermission(IPermissionManager.java:1351)
   at io.github.muntashirakon.AppManager.compat.PermissionCompat.grantPermission(PermissionCompat.java:314)
   at io.github.muntashirakon.AppManager.appops.AppOpsService.<init>(AppOpsService.java:36)
   at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.<init>(AppDetailsViewModel.java:660)
   at java.lang.reflect.Constructor.newInstance0(Native Method)
   at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
   at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:312)
   at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:304)
   at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:278)
   at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.kt:128)
   at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:187)
   at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:153)
   at io.github.muntashirakon.AppManager.details.AppDetailsActivity.onAuthenticated(AppDetailsActivity.java:93)
   at io.github.muntashirakon.AppManager.BaseActivity.onCreate(BaseActivity.java:65)
   at android.app.Activity.performCreate(Activity.java:8146)
   at android.app.Activity.performCreate(Activity.java:8130)
   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1310)
   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3689)
   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3887)
   at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
   at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:140)
   at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:100)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2317)
   at android.os.Handler.dispatchMessage(Handler.java:106)
   at android.os.Looper.loop(Looper.java:263)
   at android.app.ActivityThread.main(ActivityThread.java:8292)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
 Caused by: android.os.RemoteException: Remote stack trace:
	at android.app.ContextImpl.enforce(ContextImpl.java:2073)
	at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:2101)
	at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermissionInternal(PermissionManagerService.java:1468)
	at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(PermissionManagerService.java:1449)
	at android.permission.IPermissionManager$Stub.onTransact(IPermissionManager.java:648)

Device Info:
App version: 3.0.2
App version code: 413
Android build version: 1656498236709
Android release version: 11
Android SDK version: 30
Android build ID: CPH1933_11_F.15
Device brand: OPPO
Device manufacturer: OPPO
Device name: OP4B79L1
Device model: CPH1933
Device product name: CPH1933
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-US
In-App Language: auto
Mode: adb_wifi
Inferred Mode: ADB
</details>

### Device info

- Device: Oppo A5 2020
- OS Version: 11
- App Manager Version: 3.0.2 (413)
- Mode: ADB

**Comment by MuntashirAkon** [comment] 2022-09-30 18:01
> ```
> java.lang.SecurityException: grantRuntimePermission: Neither user 2000 nor current process has android.permission.GRANT_RUNTIME_PERMISSIONS.
> ```

It appears that you have to disable permission monitoring similar to Realms.

**Comment by wmc3000** [comment] 2022-10-01 11:26
It works after disabling permission monitoring, but maybe add some warning system instead of crashing because of it?

**Comment by MuntashirAkon** [comment] 2023-01-15 18:14
Should be fixed in aba5b57df4717e67f0ebbd4bf18b42ae29f06494. Not verified because I cannot reproduce the issue.

**Closed by MuntashirAkon** 2023-01-15 18:14 UTC
Labels: Bug, Documentation, Priority: 3, Severity: 2
