### ISSUE TITLE
Added the installation lock function

### ISSUE THREAD

**Issue by Keeperorowner** [MuntashirAkon/AppManager#1447] opened 2024-09-18 06:33 UTC
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

It is recommended to lock AM as the system default installer, after all, AM installers are much more beautiful and practical than system installers

**Comment by Tharow** [comment] 2024-09-27 04:23
Duplicate of https://github.com/MuntashirAkon/AppManager/issues/1404

This could be done separately  by disabling the associated activity of PackageInstaller  -- InstallStart iirc

**Closed as not planned** 2024-10-12 16:39 UTC
Labels: Duplicate, Feature
