### ISSUE TITLE
Usage monitor and history

### ISSUE THREAD

**Issue by Cyberavater** [MuntashirAkon/AppManager#382] opened 2021-04-20 19:34 UTC
Show an alerting notification when an app is using location, camera, microphone.
History would contain this usage record.

This feature is part of an app called App Ops: https://play.google.com/store/apps/details?id=rikka.appops&hl=en&gl=US
[Only added for reference, the app is closed soured, afaik.]

Also, if it's possible I'd request the dev to check this app's "Permissions View" listing if something similar can be implemented on AM too.

**Comment by MuntashirAkon** [comment] 2021-04-20 23:08
Duplicate of #143

**Closed by MuntashirAkon** 2021-04-20 23:08 UTC
Labels: P3, duplicate, feature
