### ISSUE TITLE
Unable to manually install apps in Miui 12.5 China beta A12

### ISSUE THREAD

**Issue by OAJJAIN** [MuntashirAkon/AppManager#624] opened 2021-11-14 05:51 UTC
I am currently using miui 12.5 china beta A12 21.11.11 in mi 11 ultra. I am unable to install apps using app manager and app manager debug app. When I click on an app, it automatically open miui package installer without giving at menu to choose package installer or app manager install option. On ther other hand, same version of xiaomi.eu beta of same version for mi 11 ultra, I was able to install app using app manager/debug. Anyone has any solution for this? I am using app manager/debug as root

**Comment by MuntashirAkon** [comment] 2021-11-15 09:19
This occurred due to API changes in the Android framework in A12 and has already been fixed. (I was about to make a new release but then I've become too sick to look at the screen.)

**Comment by MuntashirAkon** [comment] 2021-11-15 09:21
Duplicate of #600

**Closed by MuntashirAkon** 2021-11-15 09:21 UTC
Labels: help wanted

**Comment by OAJJAIN** [comment] 2021-11-15 10:39
I forgot to mention that this issue I faced was in stable app manager as well app manager debug version 2.6.4-1592-DEBUG (395). When I click to apk file, it automatically goes to miui packet manager without even showing a menu to select an app to choose from. Didn't face this issue in Xiaomi.eu A12 beta for same device and version

**Comment by MuntashirAkon** [comment] 2021-11-16 04:59
So far as I know, sharing (instead of opening) the APK file through App Manager works.

Disclaimer: I do not use MIUI. I have heard this from another user.

**Comment by OAJJAIN** [comment] 2021-11-16 05:13
You are correct. I used the latest App manager debug build AM Debug v2.6.4 Run#1592. Had the same issue with it. Sharing instead of opening will give an option of install through the app manager in the menu. 
However, this issue seems to only be in China beta A12 12.5 21.11.11 and its not there in Xiaomi.eu A12 12.5 21.11.11 and hasnt even been in EU beta.

**Comment by MuntashirAkon** [comment] 2021-11-16 05:16
According to the Xiaomi.eu developer, they have patched the framework to remove this limitation.
