### ISSUE TITLE
ADB activation using notification

### ISSUE THREAD

**Issue by jcfyre** [MuntashirAkon/AppManager#1419] opened 2024-07-29 21:38 UTC
### Please check before submitting an issue

- [x] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

Have the activation for ADB use a notification to enter pairing code and port number (usually automatic port number) instead of relying on split screen, miniaturization, or other mode. Shizuku does this and it works flawlessly.

### Additional context

Notifications are nice because usually one can tap the arrow to expand the notification onto the screen without opening it which is nice as that eliminates clunky slower methods like split screen and others. A bonus is when the box pops up for pairing info it actually pushes it up into view when the keyboard pops up allowing one to see both the pairing notification as well as wifi-debugging pairing info box as they type it in, making the pairing process seamless.

**Comment by shuvashish76** [comment] 2024-07-30 12:55
Already available for v4.0.0-beta01
Duplicate of #892

**Comment by MuntashirAkon** [comment] 2024-08-09 14:05
Duplicate of #892

**Closed by MuntashirAkon** 2024-08-09 14:05 UTC
Labels: Duplicate, Feature
