### ISSUE TITLE
cannot clear cache

### ISSUE THREAD

**Issue by Kimphunh** [MuntashirAkon/AppManager#911] opened 2022-10-31 14:53 UTC
Is me again
So It can still delete all data but not only the cache
Did you change anything in adb mode?
More info

Android 11
Mode:Wireless Adb
Lastest AM debug

**Comment by MuntashirAkon** [comment] 2022-11-07 18:59
I don't remember changing anything. I'll look into this.

**Comment by Efreak** [comment] 2023-01-18 21:37
I've noticed this too. Clearing cache via system settings is annoying, since you can't clear cache until the system finishes checking storage usage; some apps with large storage and cache directories take *minutes* to check. Termux is the worst offender, since there's an entire operating system in there, as well as multiple caches for apt, pip, cargo, etc; Firefox and other browsers are next. Trying to check storage usage for either of these on my phone is futile, the screen shuts off before it finishes. Fortunately I can access termux's cache from inside termux (`apt-cache autoclean` or `rm -rf /data/data/com.termux/cache/*`), and run an adb command to clean Firefox. Unfortunately, my small internal storage means this has to be done somewhat frequently.

**Comment by MuntashirAkon** [comment] 2023-01-19 04:22
Clearing cache for the entire system works faster than clearing cache for individual apps.

**Comment by MuntashirAkon** [comment] 2023-01-19 04:23
Duplicate of #962

**Closed by MuntashirAkon** 2023-01-19 04:23 UTC
Labels: Duplicate
