### ISSUE TITLE
AM Crashes when backing up an app whose App Info page hasn't loaded yet

### ISSUE THREAD

**Issue by Atrate** [MuntashirAkon/AppManager#232] opened 2021-01-16 12:31 UTC
Partially related: #135, #224

**Describe the bug**
AM Crashes when backing up an app whose App Info page hasn't loaded yet.

**To Reproduce**
Steps to reproduce the behaviour:
1. Close AM (bug only happens on a cold start)
2. Open AM and open an app's info page
3. Close the info page quickly before it loads completely
4. Try to back-up that app
5. AM Crashes

**Expected behavior**
AM should not crash

**Crash logs**
```
java.lang.IllegalStateException: onGetLayoutInflater() cannot be executed until the Fragment is attached to the FragmentManager.
    at androidx.fragment.app.Fragment.getLayoutInflater(Fragment.java:1658)
    at androidx.fragment.app.Fragment.onGetLayoutInflater(Fragment.java:1607)
    at androidx.fragment.app.Fragment.performGetLayoutInflater(Fragment.java:1639)
    at androidx.fragment.app.Fragment.getLayoutInflater(Fragment.java:1624)
    at io.github.muntashirakon.AppManager.details.info.AppInfoFragment.addToHorizontalLayout(AppInfoFragment.java:1158)
    at io.github.muntashirakon.AppManager.details.info.AppInfoFragment.setHorizontalActions(AppInfoFragment.java:601)
    at io.github.muntashirakon.AppManager.details.info.AppInfoFragment.lambda$xWz9vTnm3z1QcBRHbhFt47G9O3M(Unknown Source:0)
    at io.github.muntashirakon.AppManager.details.info.-$$Lambda$AppInfoFragment$xWz9vTnm3z1QcBRHbhFt47G9O3M.run(Unknown Source:2)
    at android.os.Handler.handleCallback(Handler.java:883)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:7356)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:915)
```

**Device info**
App version: 2.5.22-PRE
Android release version: 10
Android SDK version: 29
Device brand: lge
Device manufacturer: LGE
Device name: lucye
Device model: LG-H870
Device product name: lucye_global_com
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-US
In-App Language: auto
Mode: root

**Comment by MuntashirAkon** [comment] 2021-01-16 12:42
This should be a duplicate of #224. The issue here is that by the time it tries to set the horizontal action buttons, the activity (thus the App Info fragment) no longer exists.

**Comment by MuntashirAkon** [comment] 2021-01-16 12:43
The solution is to load all items in a ViewModel (in MVVM pattern) and then load them all at once in the fragment.

**Closed by MuntashirAkon** 2021-01-16 12:42 UTC
Labels: P3, S3, bug
