### ISSUE TITLE
Allow user to select whether to restore app on work or personal profile

### ISSUE THREAD

**Issue by tadekdudek** [MuntashirAkon/AppManager#1249] opened 2023-12-04 09:48 UTC
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

When restoring a backup, it always restores it on both personal and work profile. It should allow user to choose where the backup should be restored.

### Describe the solution you'd like

There should be a dialog when clicking the restore button where to restore backup like that shown when clicking on app installed on both profiles.

**Comment by shuvashish76** [comment] 2023-12-05 06:09
I've mentioned my suggestions in #1220

**Comment by MuntashirAkon** [comment] 2024-07-10 04:42
Duplicate of #1220

**Closed by MuntashirAkon** 2024-07-10 04:42 UTC
Labels: Duplicate, Feature
