### ISSUE TITLE
If you get stuck at "Initializing" or if install hangs

### ISSUE THREAD

**Issue by schbrns** [MuntashirAkon/AppManager#1482] opened 2024-12-04 10:15 UTC
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

If you get stuck, force close the app. 

Before re-opening it:

1. AppManager needs both Accessibility and Notification permissions enabled. These both auto-disable, not sure of cause.
2. If you cleared cache/data, you need to perform step 1, then go to Wireless Debugging and forget the old AppManager pairing
4. If you're still getting stuck, forget the old pairing anyway

I think it has less to do with data/cache and more to do with the previous wireless debugging pairing and resetting permissions.

### Device info

- Device: Samsung Galaxy S23
- OS Version: 6.1
- App Manager Version: 4.0.0-beta2
- Mode: ADB

**Comment by MuntashirAkon** [comment] 2024-12-23 08:49
Fixed by 51f107fa2632e42eea030e0f91e48fe39d8f5836. Please read the commit description to get an idea of how the issue is addressed. More improvements will be made in the future depending on how it affects the user experience.

**Closed** 2024-12-23 09:00 UTC
Labels: Bug
