### ISSUE TITLE
Providers/Apps ops/ Uses permissions crash

### ISSUE THREAD

**Issue by HoboVidens** [MuntashirAkon/AppManager#287] opened 2021-02-17 21:42 UTC
I have recently clean installed latest arrowos 11.0 on my curtana device. The app manager app runs ok, but crashes when I go to the Providers/ App ops or Uses permissions tablets. I tried clean installation twice, I have no password and I turned on any permission I could find about the app. Any fixes?

**Comment by MuntashirAkon** [comment] 2021-02-18 00:04
You've failed to mention AM version. Is it v2.5.20?

**Comment by HoboVidens** [comment] 2021-02-18 01:45
Sorry. It is v2.5.17. Latest on f-droid.

**Comment by MuntashirAkon** [comment] 2021-02-18 02:04
Duplicate of #194

**Closed by MuntashirAkon** 2021-02-18 02:04 UTC
