### ISSUE TITLE
AppManager as a System app

### ISSUE THREAD

**Issue by bolbolfolfol** [MuntashirAkon/AppManager#1226] opened 2023-10-16 03:29 UTC
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

Hi
i want to use AppManager as a system app but the problem is the system don't boot if i do that directly
it work only if i install it as a normal app then reboot to recovery and MOVE it's folder from DATA/APP to SYSTEM/APP (or priv-app)

do you know why that work ?
or what files should i edit for it to work on an empty data
and thank you

### Describe the solution you'd like

install normally then move the folder to system

**Comment by MuntashirAkon** [comment] 2023-10-16 07:40
You can't use App Manager as a system app. See #603.

**Comment by MuntashirAkon** [comment] 2023-10-16 07:41
Duplicate of #477

**Closed by MuntashirAkon** 2023-10-16 07:41 UTC
Labels: Feature

**Comment by bolbolfolfol** [comment] 2023-10-16 16:17
> You can't use App Manager as a system app. See #603.

i already do
please read what i wrote (fully)
"please"

**Comment by MuntashirAkon** [comment] 2023-10-18 06:22
> i already do
> please read what i wrote (fully)
> "please"

Not sure if it's a language gap. What I meant from the statement above is that App Manager cannot be installed as a system app, and it's an intended behaviour. Installing App Manager to the system does not automatically enable all the required permissions and privileges, it has to be signed with the same signature as the system itself which is impossible. So, even if you install App Manager in the system, it will not be any more beneficial than it already is. The alternative is to whitelist the required permissions which is what #477 is all about.
