### ISSUE TITLE
App list is blank.

### ISSUE THREAD

**Issue by BloodReleasesPain** [MuntashirAkon/AppManager#502] opened 2021-07-02 06:45 UTC
- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

When first opening the app, the app list is blank. A refresh of the app list only results in a constant loading loop.

![Screenshot_20210701-233851_AM Debug.jpg](https://user-images.githubusercontent.com/43686736/124232092-107ded00-dac6-11eb-96aa-67c58032be54.jpg)

Logs:
```
2021-07-01 23:37:54.594 D/IPC: Init: Local server
2021-07-01 23:37:54.640 D/LocalServerManager: useAdbStartServer: Connecting using host=::1, port=5555
2021-07-01 23:37:54.649 W/KSManager: Using keystore BKS
2021-07-01 23:37:54.660 I/CompatUtil: Loading local protection key
2021-07-01 23:37:54.666 I/CompatUtil: AES local protection key found in keystore
2021-07-01 23:37:55.167 E/ModeOfOps
java.io.IOException: java.io.IOException: Could not create session
	at io.github.muntashirakon.AppManager.servermanager.LocalServer.checkConnect(LocalServer.java:133)
	at io.github.muntashirakon.AppManager.servermanager.LocalServer.
<init>(LocalServer.java:103)
	at io.github.muntashirakon.AppManager.servermanager.LocalServer.getInstance(LocalServer.java:46)
	at io.github.muntashirakon.AppManager.servermanager.LocalServer.restart(LocalServer.java:187)
	at io.github.muntashirakon.AppManager.runner.RunnerUtils.setModeOfOps(RunnerUtils.java:220)
	at io.github.muntashirakon.AppManager.crypto.AuthenticationActivity.lambda$handleModeOfOps$1$AuthenticationActivity(AuthenticationActivity.java:63)
	at io.github.muntashirakon.AppManager.crypto.-$$Lambda$AuthenticationActivity$93HUeU6yW43f6Muu5s9-PlJQrSc.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.io.IOException: Could not create session
	at io.github.muntashirakon.AppManager.servermanager.LocalServerManager.getSession(LocalServerManager.java:95)
	at io.github.muntashirakon.AppManager.servermanager.LocalServerManager.start(LocalServerManager.java:129)
	at io.github.muntashirakon.AppManager.servermanager.LocalServer.checkConnect(LocalServer.java:128)
	... 7 more
Caused by: java.net.ConnectException: failed to connect to /::1 (port 5555) from /:: (port 53506): connect failed: ECONNREFUSED (Connection refused)
	at libcore.io.IoBridge.connect(IoBridge.java:138)
	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:129)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:356)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
	at java.net.Socket.connect(Socket.java:616)
	at java.net.Socket.connect(Socket.java:565)
	at java.net.Socket.
<init>(Socket.java:445)
	at java.net.Socket.
<init>(Socket.java:217)
	at io.github.muntashirakon.AppManager.adb.AdbConnection.
<init>(AdbConnection.java:136)
	at io.github.muntashirakon.AppManager.adb.AdbConnection.create(AdbConnection.java:158)
	at io.github.muntashirakon.AppManager.adb.AdbConnectionManager.connect(AdbConnectionManager.java:37)
	at io.github.muntashirakon.AppManager.servermanager.LocalServerManager.useAdbStartServer(LocalServerManager.java:206)
	at io.github.muntashirakon.AppManager.servermanager.LocalServerManager.startServer(LocalServerManager.java:269)
	at io.github.muntashirakon.AppManager.servermanager.LocalServerManager.getSession(LocalServerManager.java:93)
	... 9 more
Caused by: android.system.ErrnoException: connect failed: ECONNREFUSED (Connection refused)
	at libcore.io.Linux.connect(Native Method)
	at libcore.io.BlockGuardOs.connect(BlockGuardOs.java:126)
	at libcore.io.IoBridge.connectErrno(IoBridge.java:152)
	at libcore.io.IoBridge.connect(IoBridge.java:130)
	... 24 more
2021-07-01 23:37:57.517 D/MVM: New instance created
2021-07-01 23:38:29.293 D/updateInfoForUid: Uid: 5009
2021-07-01 23:38:29.314 D/updateInfoForPackages: packages: [com.samsung.android.scloud]
2021-07-01 23:38:29.337 E/Users: Could not get list of users
java.lang.SecurityException: You either need MANAGE_USERS or CREATE_USERS permission to: query users
	at android.os.Parcel.readException(Parcel.java:1967)
	at android.os.Parcel.readException(Parcel.java:1913)
	at android.os.IUserManager$Stub$Proxy.getUsers(IUserManager.java:1056)
	at io.github.muntashirakon.AppManager.users.Users.getUsers(Users.java:68)
	at io.github.muntashirakon.AppManager.users.Users.getUsersIds(Users.java:85)
	at io.github.muntashirakon.AppManager.main.MainViewModel.getNewApplicationItem(MainViewModel.java:571)
	at io.github.muntashirakon.AppManager.main.MainViewModel.updateInfoForPackages(MainViewModel.java:493)
	at io.github.muntashirakon.AppManager.main.MainViewModel.updateInfoForUid(MainViewModel.java:453)
	at io.github.muntashirakon.AppManager.main.MainViewModel.access$000(MainViewModel.java:57)
	at io.github.muntashirakon.AppManager.main.MainViewModel$PackageIntentReceiver.onPackageChanged(MainViewModel.java:716)
	at io.github.muntashirakon.AppManager.types.PackageChangeReceiver$ReceiverHandler.handleMessage(PackageChangeReceiver.java:94)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.os.HandlerThread.run(HandlerThread.java:65)
```
Galaxy S7 edge
8.0.0
Debug 1374
ADB

**Comment by MuntashirAkon** [comment] 2021-07-02 07:13
Logs suggested that it failed to connect to the ADB and a “fallback to no-root mode” alter prompt has been displayed. I don't know whether you've clicked **yes** or **no**. However, if you clicked **no**, it would have unknown behaviour such as blank app list or infinite loading.

**Comment by BloodReleasesPain** [comment] 2021-07-02 07:22
> Logs suggested that it failed to connect to the ADB and a “fallback to no-root mode” alert prompt has been displayed. I don't know whether you've clicked **yes** or **no**. However, if you clicked **no**, it would have unknown behaviour such as blank app list or infinite loading.

after rebooting, I now see the prompt trying to connect through adb again and the app can't seem to sense the connection despite a working connection with other apps. 

2021-07-02 00:15:23.344 D/IPC: Init: Local server
2021-07-02 00:15:23.372 E/ModeOfOps
android.os.RemoteException: AMService not running.
	at io.github.muntashirakon.AppManager.ipc.IPCUtils$AMServiceConnectionWrapper.getServiceSafe(IPCUtils.java:185)
	at io.github.muntashirakon.AppManager.ipc.IPCUtils$AMServiceConnectionWrapper.getAmService(IPCUtils.java:171)
	at io.github.muntashirakon.AppManager.ipc.IPCUtils.getAmService(IPCUtils.java:44)
	at io.github.muntashirakon.AppManager.servermanager.LocalServer.launchAmService(LocalServer.java:60)
	at io.github.muntashirakon.AppManager.servermanager.LocalServer.getInstance(LocalServer.java:49)
	at io.github.muntashirakon.AppManager.servermanager.LocalServer.restart(LocalServer.java:187)
	at io.github.muntashirakon.AppManager.runner.RunnerUtils.setModeOfOps(RunnerUtils.java:220)
	at io.github.muntashirakon.AppManager.crypto.AuthenticationActivity.lambda$handleModeOfOps$1$AuthenticationActivity(AuthenticationActivity.java:63)
	at io.github.muntashirakon.AppManager.crypto.-$$Lambda$AuthenticationActivity$93HUeU6yW43f6Muu5s9-PlJQrSc.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:764)
2021-07-02 00:15:30.304 D/MVM: New instance created
2021-07-02 00:15:30.786 E/Users: Could not get list of users
java.lang.SecurityException: You either need MANAGE_USERS or CREATE_USERS permission to: query users
	at android.os.Parcel.readException(Parcel.java:1967)
	at android.os.Parcel.readException(Parcel.java:1913)
	at android.os.IUserManager$Stub$Proxy.getUsers(IUserManager.java:1056)
	at io.github.muntashirakon.AppManager.users.Users.getAllUsers(Users.java:69)
	at io.github.muntashirakon.AppManager.users.Users.getUsersIds(Users.java:101)
	at io.github.muntashirakon.AppManager.utils.PackageUtils.updateInstalledOrBackedUpApplications(PackageUtils.java:248)
	at io.github.muntashirakon.AppManager.utils.PackageUtils.lambda$getInstalledOrBackedUpApplicationsFromDb$0(PackageUtils.java:161)
	at io.github.muntashirakon.AppManager.utils.-$$Lambda$PackageUtils$lQaPt-sS9Llm_I9c5WeeA5MEQDs.run(Unknown Source:4)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
2021-07-02 00:15:54.395 W/KSManager: Using keystore BKS
2021-07-02 00:15:54.405 I/CompatUtil: Loading local protection key
2021-07-02 00:15:54.420 I/CompatUtil: AES local protection key found in keystore
2021-07-02 00:15:54.962 E/ADB: ADB available
2021-07-02 00:15:54.978 E/ADB
java.io.IOException: ADB not available
	at io.github.muntashirakon.AppManager.runner.RunnerUtils.autoDetectRootOrAdb(RunnerUtils.java:155)
	at io.github.muntashirakon.AppManager.runner.RunnerUtils.setModeOfOps(RunnerUtils.java:189)
	at io.github.muntashirakon.AppManager.settings.MainPreferences.lambda$onCreatePreferences$10$MainPreferences(MainPreferences.java:203)
	at io.github.muntashirakon.AppManager.settings.-$$Lambda$MainPreferences$xdw6wl_zqP7zSL-K-Yo95mkMSNg.run(Unknown Source:2)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
2021-07-02 00:15:58.264 D/Cache: Deleted 0 images.

**Comment by MuntashirAkon** [comment] 2021-07-02 08:04
Latest logs suggest that the app is unable to connect to AM Service (ADB has been detected). I need a full system log in order to figure out the issue.

**Comment by BloodReleasesPain** [comment] 2021-07-03 11:42
how do I do that?

**Comment by MuntashirAkon** [comment] 2021-07-03 14:56
> how do I do that?

Take logs using logcat without using any filters.

**Comment by BloodReleasesPain** [comment] 2021-07-05 23:53
> > how do I do that?
> 
> Take logs using logcat without using any filters.

may I do you on telegram a txt file? there's too many characters so clipboard won't copy.

**Comment by MuntashirAkon** [comment] 2021-07-06 00:11
> may I do you on telegram a txt file? there's too many characters so clipboard won't copy.

OK. You can also send me the logs via an email.

**Comment by BloodReleasesPain** [comment] 2021-07-06 00:23
> > may I do you on telegram a txt file? there's too many characters so clipboard won't copy.
> 
> OK. You can also send me the logs via an email.

Okay I will by email.

**Comment by MuntashirAkon** [comment] 2021-07-06 07:53
Hmmm, the issue looks quite odd, ADB is detected but it couldn't run the server. Could you find the exact build where it started failing?

**Comment by BloodReleasesPain** [comment] 2021-07-06 09:08
> Hmmm, the issue looks quite odd, ADB is detected but it couldn't run the server. Could you find the exact build where it started failing?

I'll try. One thing I noticed is that this issue only seems to happen when you have explicitly "ADB over TCP" chosen in mode of operation, while "auto" works just fine. It's as if "ADB over TCP" is behaving like it's "No root" mode and therefore doesn't even bother establishing a connection and gives an error anyway.

**Comment by BloodReleasesPain** [comment] 2021-07-06 09:37
I can confirm this will always happen if the app ever enters no root mode. If I have a successful connection with adb in auto mode and then go to adb over TCP, everything is fine. however if I go from auto or TCP with a successful connection and go to no root operation, then back to TCP, OR ever receive the "fallback to no root mode?" prompt it will always fail no matter what you do whether you choose "yes" or "no". the app will forever be stuck in no root mode until you go back to "auto" and the adb mode toast and functionality works again seamlessly without even needing to restart the app or reboot the device. so far this issue is persistent through all the way to #1322 and I'm still downgrading to see how far this issue goes, which ALSO means this problem occurs with the latest stable version and I have successfully replicated this issue on there as well.

**Comment by MuntashirAkon** [comment] 2021-07-06 09:39
Yeah, it seems to be reproducible on my side too. So, you don't need to go through the debug builds anymore.

**Comment by MuntashirAkon** [comment] 2021-07-06 13:55
Fixed in 4afa0054 and cebf24a5.

**Closed by MuntashirAkon** 2021-07-06 13:55 UTC
Labels: P3, S3, bug

**Comment by BigNdets** [comment] 2021-08-02 20:20
> Fixed in 4afa0054 and cebf24a5.

I don't understand what I'm supposed to do to solve this. Please explain in simple language.

**Comment by MuntashirAkon** [comment] 2021-08-03 00:52
> I don't understand what I'm supposed to do to solve this. @MuntashirAkon Please explain in simple language.

You don't have to anything. Just wait for the next release (as described in the milestone section).

**Comment by BigNdets** [comment] 2021-08-06 13:40
> > I don't understand what I'm supposed to do to solve this. @MuntashirAkon Please explain in simple language.
> 
> You don't have to anything. Just wait for the next release (as described in the milestone section).

Thank you. I hope it gets released soon.
