### ISSUE TITLE
Crash on installer (split apks) - Android 12

### ISSUE THREAD

**Issue by 0xlne** [MuntashirAkon/AppManager#633] opened 2021-11-26 00:15 UTC
App Manager in itself launches & works in Android 12, but some features cause a crash.
One such features is the Installer module.

Steps to Reproduce:
1: select a split apk (*.apks) - tested with a few of them, via the "open with" Android menu
2: install - App Manager will proceed to optimize the packages, but will fail/crash on triggering the system package manager.

Tested on:
Galaxy Fold 3 on Android 12 Beta 3

**Comment by MuntashirAkon** [comment] 2021-11-26 00:17
Steps to reproduce won't work because I do not have A12 installed. Share crashlogs instead.

**Comment by 0xlne** [comment] 2021-11-26 00:26
java.lang.NoSuchMethodError: No interface method createSession(Landroid/content/pm/PackageInstaller$SessionParams;Ljava/lang/String;I)I in class Landroid/content/pm/IPackageInstaller; or its super classes (declaration of 'android.content.pm.IPackageInstaller' appears in /system/framework/framework.jar)
at io.github.muntashirakon.AppManager.apk.installer.PackageInstallerCompat.openSession(PackageInstallerCompat.java:665)
at io.github.muntashirakon.AppManager.apk.installer.PackageInstallerCompat.install(PackageInstallerCompat.java:527)
at io.github.muntashirakon.AppManager.apk.installer.PackageInstallerService.onHandleIntent(PackageInstallerService.java:122)
at io.github.muntashirakon.AppManager.types.ForegroundService$ServiceHandler.handleMessage(ForegroundService.java:40)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:226)
at android.os.Looper.loop(Looper.java:313)
at android.os.HandlerThread.run(HandlerThread.java:67)

Device Info:
App version: 2.6.4
App version code: 394
Android build version: F926BXXU1ZUKG
Android release version: 12
Android SDK version: 31
Android build ID: SP1A.210812.016.F926BXXU1ZUKG
Device brand: samsung
Device manufacturer: samsung
Device name: q2q
Device model: SM-F926B
Device product name: q2qxeea
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-GB
In-App Language: auto
Mode: auto

**Comment by MuntashirAkon** [comment] 2021-11-26 00:34
Duplicate of #600

**Closed by MuntashirAkon** 2021-11-26 00:34 UTC
Labels: bug, info-needed, S3, P3
