### ISSUE TITLE
App list never loads, refresh does nothing

### ISSUE THREAD

**Issue by misterjmw** [MuntashirAkon/AppManager#746] opened 2022-05-07 03:07 UTC
Android 12, Pixel 6, root

App manager launches and begins scanning and never stops. Refresh does nothing and the app list never loads. I have tried clearing the search box. Other items from the "three dots" are accessible, but not the app list. If I revert and install version 2.# the app manager list loads near immediately.

I have tried the other alphas and they all have the same issue. I have also tried different modes of operation, root, adb, auto does not affect the list either.

The logs don't appear helpful, but I see an entry:
"W/pkx     (2752): Infinite Data has no result for io.github.muntashirakon.AppManager [CONTEXTservice_id=177 ]"

**Comment by MuntashirAkon** [comment] 2022-05-07 03:55
In order get helpful logs, debug version of the app has to be installed. When you switch between versions, you have to restart or use App Manager in no-root mode.

**Comment by Sami32** [comment] 2022-05-07 22:55
Same with non rooted Android 7.0 on Xiaomi with the latest 3.0.0 alpha01(400).
Applications was listed before this App Manager version.
[App-manager_logs-2022-05-08-00-49-59.zip](https://github.com/MuntashirAkon/AppManager/files/8646069/App-manager_logs-2022-05-08-00-49-59.zip)

**Comment by MuntashirAkon** [comment] 2022-05-10 09:46
> Where are debug versions released? I only see the two apks on Github, neither states 'debug'.

See https://muntashirakon.github.io/AppManager/en/#subsec:binary-distribution-sources

**Comment by misterjmw** [comment] 2022-05-10 14:26
> > Where are debug versions released? I only see the two apks on Github, neither states 'debug'.
> 
> See https://muntashirakon.github.io/AppManager/en/#subsec:binary-distribution-sources

Telegram? It's a service I do not have.

**Comment by MuntashirAkon** [comment] 2022-05-11 05:42
> > > Where are debug versions released? I only see the two apks on Github, neither states 'debug'.
> > 
> > 
> > See https://muntashirakon.github.io/AppManager/en/#subsec:binary-distribution-sources
> 
> Telegram? It's a service I do not have.

You've skipped the GitHub part. Goto https://github.com/MuntashirAkon/AppManager/actions and click on any items with **Debug build** tag.

**Comment by MuntashirAkon** [comment] 2022-05-11 10:49
Duplicate of #685

**Closed by MuntashirAkon** 2022-05-11 10:49 UTC
Labels: Bug, Status: Pending, S3, P3
