### ISSUE TITLE
AppManager crashes when uninstalling system app

### ISSUE THREAD

**Issue by 2011** [MuntashirAkon/AppManager#868] opened 2022-09-16 00:09 UTC
- [x] I know what my device, OS and App Manager versions are
- [x] I know how to take logs
- [x] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**

Every time I uninstall a system app, AppManager crashes (have run out of those I wish to uninstall on this device, though :) ).

**To Reproduce**
Steps to reproduce the behaviour:
1. Select any system app.
2. Click on Uninstall.
3. AppManager crashes (it does remove data before the crash, though).

**Expected behavior**

Uninstall the app, and keep running.

**Crash logs**

```
<<< log_count = 240 >>>
[09-15 23:25:46.500 657:667 I/ActivityManager]
START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10300000 cmp=io.github.muntashirakon.AppManager/.main.SplashActivity} from uid 10097 on display 0

[09-15 23:25:46.539 657:32047 I/ActivityManager]
Start proc 12827:io.github.muntashirakon.AppManager/u0a97 for activity io.github.muntashirakon.AppManager/.main.SplashActivity

[09-15 23:25:46.841 12827:12848 D/RootServiceManager]
( [ -d  /data/local/tmp ] || ( rm /data/local/tmp; mkdir /data/local/tmp && chmod 771 /data/local/tmp && chown 2000:2000 /data/local/tmp ) ) && cp /storage/emulated/0/Android/data/io.github.muntashirakon.AppManager/cache/main.jar /data/local/tmp && chmod 755 /data/local/tmp/main.jar && chown shell:shell /data/local/tmp/main.jar && (CLASSPATH=/data/local/tmp/main.jar  /proc/12827/exe  /system/bin --nice-name=io.github.muntashirakon.AppManager:root io.github.muntashirakon.AppManager.server.RootServiceMain io.github.muntashirakon.AppManager/io.github.muntashirakon.AppManager.ipc.AMService 10097 d37536c0-486c-43ce-acf2-a38347ecb95e start)&

[09-15 23:25:46.891 657:8116 I/WindowManager]
Switching to real app window: Window{139229 u0 io.github.muntashirakon.AppManager/io.github.muntashirakon.AppManager.main.SplashActivity}

[09-15 23:25:46.921 657:677 I/WindowManager]
Destroying surface Surface(name=io.github.muntashirakon.AppManager/io.github.muntashirakon.AppManager.main.SplashActivity) called by com.android.server.wm.WindowStateAnimator.destroySurface:2014 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:881 com.android.server.wm.WindowState.removeLocked:1449 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2482 com.android.server.wm.WindowState.maybeRemoveReplacedWindow:1618 com.android.server.wm.WindowAnimator.removeReplacedWindowsLocked:812 com.android.server.wm.WindowAnimator.animateLocked:788 com.android.server.wm.WindowAnimator.-wrap0:-1 

[09-15 23:25:46.925 657:677 I/ActivityManager]
Displayed io.github.muntashirakon.AppManager/.main.SplashActivity: +397ms

[09-15 23:25:46.929 657:677 I/WindowManager]
Destroying surface Surface(name=Starting io.github.muntashirakon.AppManager) called by com.android.server.wm.WindowStateAnimator.destroySurface:2014 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:881 com.android.server.wm.WindowState.destroyOrSaveSurface:2073 com.android.server.wm.AppWindowToken.destroySurfaces:363 com.android.server.wm.WindowStateAnimator.finishExit:565 com.android.server.wm.WindowStateAnimator.stepAnimationLocked:491 com.android.server.wm.WindowAnimator.updateWindowsLocked:303 com.android.server.wm.WindowAnimator.animateLocked:704 

[09-15 23:25:47.296 12870:12870 D/AndroidRuntime]
Calling main entry io.github.muntashirakon.AppManager.server.RootServiceMain

[09-15 23:25:47.373 657:32046 I/ActivityManager]
START u0 {cmp=io.github.muntashirakon.AppManager/.main.MainActivity} from uid 10097 on display 0

[09-15 23:25:47.667 657:677 I/ActivityManager]
Displayed io.github.muntashirakon.AppManager/.main.MainActivity: +285ms

[09-15 23:25:47.912 657:667 I/WindowManager]
Destroying surface Surface(name=io.github.muntashirakon.AppManager/io.github.muntashirakon.AppManager.main.SplashActivity) called by com.android.server.wm.WindowStateAnimator.destroySurface:2014 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:881 com.android.server.wm.WindowState.destroyOrSaveSurface:2073 com.android.server.wm.WindowManagerService.tryStartExitingAnimation:3021 com.android.server.wm.WindowManagerService.relayoutWindow:2901 com.android.server.wm.Session.relayout:215 android.view.IWindowSession$Stub.onTransact:286 com.android.server.wm.Session.onTransact:136 

[09-15 23:25:48.892 12870:12884 W/JavaBinder]
BinderProxy is being destroyed but the application did not call unlinkToDeath to unlink all of its death recipients beforehand.  Releasing leaked death recipient: io.github.muntashirakon.io.FileSystemService$$ExternalSyntheticLambda0

[skipping 203 additional messages identical to the ones immediately above and below (except for timestamps), all of which occurred within approximately 0.7 seconds]

[09-15 23:25:49.598 12870:12884 W/JavaBinder]
BinderProxy is being destroyed but the application did not call unlinkToDeath to unlink all of its death recipients beforehand.  Releasing leaked death recipient: io.github.muntashirakon.io.FileSystemService$$ExternalSyntheticLambda0

[09-15 23:26:11.017 657:32040 I/ActivityManager]
START u0 {cmp=io.github.muntashirakon.AppManager/.details.AppDetailsActivity (has extras)} from uid 10097 on display 0

[09-15 23:26:12.017 657:677 I/ActivityManager]
Displayed io.github.muntashirakon.AppManager/.details.AppDetailsActivity: +986ms

[09-15 23:26:12.205 657:1140 I/WindowManager]
Destroying surface Surface(name=io.github.muntashirakon.AppManager/io.github.muntashirakon.AppManager.main.MainActivity) called by com.android.server.wm.WindowStateAnimator.destroySurface:2014 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:881 com.android.server.wm.WindowState.destroyOrSaveSurface:2073 com.android.server.wm.WindowManagerService.tryStartExitingAnimation:3021 com.android.server.wm.WindowManagerService.relayoutWindow:2901 com.android.server.wm.Session.relayout:215 android.view.IWindowSession$Stub.onTransact:286 com.android.server.wm.Session.onTransact:136 

[09-15 23:26:24.671 657:677 I/WindowManager]
Destroying surface Surface(name=io.github.muntashirakon.AppManager/io.github.muntashirakon.AppManager.details.AppDetailsActivity) called by com.android.server.wm.WindowStateAnimator.destroySurface:2014 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:881 com.android.server.wm.WindowState.destroyOrSaveSurface:2073 com.android.server.wm.AppWindowToken.destroySurfaces:363 com.android.server.wm.WindowStateAnimator.finishExit:565 com.android.server.wm.WindowStateAnimator.stepAnimationLocked:491 com.android.server.wm.WindowAnimator.updateWindowsLocked:303 com.android.server.wm.WindowAnimator.animateLocked:704 

[09-15 23:26:24.831 657:1007 W/InputDispatcher]
channel '5444ed3 io.github.muntashirakon.AppManager/io.github.muntashirakon.AppManager.main.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9

[09-15 23:26:24.831 657:1007 E/InputDispatcher]
channel '5444ed3 io.github.muntashirakon.AppManager/io.github.muntashirakon.AppManager.main.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!

[09-15 23:26:24.831 657:1007 W/InputDispatcher]
channel 'e92c3 io.github.muntashirakon.AppManager/io.github.muntashirakon.AppManager.details.AppDetailsActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9

[09-15 23:26:24.831 657:1007 E/InputDispatcher]
channel 'e92c3 io.github.muntashirakon.AppManager/io.github.muntashirakon.AppManager.details.AppDetailsActivity (server)' ~ Channel is unrecoverably broken and will be disposed!

[09-15 23:26:24.848 657:32047 I/WindowManager]
WIN DEATH: Window{e92c3 u0 io.github.muntashirakon.AppManager/io.github.muntashirakon.AppManager.details.AppDetailsActivity}

[09-15 23:26:24.848 657:32047 W/InputDispatcher]
Attempted to unregister already unregistered input channel 'e92c3 io.github.muntashirakon.AppManager/io.github.muntashirakon.AppManager.details.AppDetailsActivity (server)'

[09-15 23:26:24.848 657:32047 I/WindowManager]
Destroying surface Surface(name=io.github.muntashirakon.AppManager/io.github.muntashirakon.AppManager.details.AppDetailsActivity) called by com.android.server.wm.WindowStateAnimator.destroySurface:2014 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:881 com.android.server.wm.WindowState.removeLocked:1449 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2482 com.android.server.wm.WindowManagerService.removeWindowLocked:2440 com.android.server.wm.WindowState$DeathRecipient.binderDied:1780 android.os.BinderProxy.sendDeathNotice:688 <bottom of call stack> 

[09-15 23:26:24.850 657:667 I/WindowManager]
WIN DEATH: Window{5444ed3 u0 io.github.muntashirakon.AppManager/io.github.muntashirakon.AppManager.main.MainActivity}

[09-15 23:26:24.850 657:667 W/InputDispatcher]
Attempted to unregister already unregistered input channel '5444ed3 io.github.muntashirakon.AppManager/io.github.muntashirakon.AppManager.main.MainActivity (server)'

[09-15 23:26:24.854 657:4994 I/ActivityManager]
Process io.github.muntashirakon.AppManager (pid 12827) has died

[09-15 23:26:24.855 657:4994 W/ActivityManager]
Force removing ActivityRecord{4bcc54b u0 io.github.muntashirakon.AppManager/.details.AppDetailsActivity t349}: app died, no saved state

[09-15 23:26:24.875 657:4994 I/ActivityManager]
Start proc 12959:io.github.muntashirakon.AppManager/u0a97 for activity io.github.muntashirakon.AppManager/.main.MainActivity

[09-15 23:26:25.156 12959:12959 E/AndroidRuntime]
FATAL EXCEPTION: main
Process: io.github.muntashirakon.AppManager, PID: 12959
java.lang.RuntimeException: Unable to start activity ComponentInfo{io.github.muntashirakon.AppManager/io.github.muntashirakon.AppManager.main.MainActivity}: java.lang.RuntimeException: Parcel android.os.Parcel@afaa393: Unmarshalling unknown type code 6619244 at offset 1612
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
Caused by: java.lang.RuntimeException: Parcel android.os.Parcel@afaa393: Unmarshalling unknown type code 6619244 at offset 1612
        at android.os.Parcel.readValue(Parcel.java:2443)
        at android.os.Parcel.readSparseArrayInternal(Parcel.java:2798)
        at android.os.Parcel.readSparseArray(Parcel.java:2067)
        at android.os.Parcel.readValue(Parcel.java:2421)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:2717)
        at android.os.BaseBundle.unparcel(BaseBundle.java:269)
        at android.os.Bundle.getSparseParcelableArray(Bundle.java:910)
        at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2129)
        at android.app.Activity.onRestoreInstanceState(Activity.java:1047)
        at android.app.Activity.performRestoreInstanceState(Activity.java:1002)
        at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1174)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2619)
        ... 9 more

[09-15 23:26:25.158 657:1771 W/ActivityManager]
  Force finishing activity io.github.muntashirakon.AppManager/.main.MainActivity

[09-15 23:26:25.660 657:670 W/ActivityManager]
Activity pause timeout for ActivityRecord{d03730c u0 io.github.muntashirakon.AppManager/.main.MainActivity t349 f}

[09-15 23:26:25.698 657:670 I/WindowManager]
Failed to capture screenshot of Token{ecdd455 ActivityRecord{d03730c u0 io.github.muntashirakon.AppManager/.main.MainActivity t349 f}} appWin=Window{481fe8 u0 Starting io.github.muntashirakon.AppManager} drawState=4

[09-15 23:26:28.541 657:1771 W/ActivityManager]
  Force finishing activity io.github.muntashirakon.AppManager/.main.MainActivity

[09-15 23:26:28.575 657:1771 I/ActivityManager]
Killing 12959:io.github.muntashirakon.AppManager/u0a97 (adj 199): crash

[09-15 23:26:28.595 657:677 I/WindowManager]
Destroying surface Surface(name=Starting io.github.muntashirakon.AppManager) called by com.android.server.wm.WindowStateAnimator.destroySurface:2014 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:881 com.android.server.wm.WindowState.removeLocked:1449 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2482 com.android.server.wm.WindowManagerService.removeWindowLocked:2440 com.android.server.wm.WindowManagerService.removeWindowLocked:2309 com.android.server.wm.WindowManagerService.removeWindow:2304 com.android.server.wm.Session.remove:193 

[09-15 23:26:28.615 657:677 I/WindowManager]
Destroying surface Surface(name=Application Error: io.github.muntashirakon.AppManager) called by com.android.server.wm.WindowStateAnimator.destroySurface:2014 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:881 com.android.server.wm.WindowState.destroyOrSaveSurface:2073 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementInner:429 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementLoop:232 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement:180 com.android.server.wm.WindowManagerService$H.handleMessage:8115 android.os.Handler.dispatchMessage:102
```

**Device info**
 - Device: Teclast T10
 - OS Version: Android 7.0
 - App Manager Version: 3.0.1
 - Mode: root

**Comment by MuntashirAkon** [comment] 2022-09-16 03:31
Duplicate of #656

**Closed by MuntashirAkon** 2022-09-16 03:31 UTC
Labels: Bug, Duplicate
