### ISSUE TITLE
App Manager stuck at initialize 

### ISSUE THREAD

**Issue by Yoongdeer** [MuntashirAkon/AppManager#1234] opened 2023-10-22 04:30 UTC
### Describe the existing feature/documentation

Installed then given su right it just hangs at initializing

### Describe your problem(s)

Installed then given su right it just hangs at initializing

**Comment by Yoongdeer** [comment] 2023-10-22 04:30
https://imgbox.com/Vchl2KGS

**Comment by H3XDaemon** [comment] 2023-10-22 05:08
In case you're using latest Magisk Alpha. #1231

**Comment by Yoongdeer** [comment] 2023-10-22 05:12
> In case you're using latest Magisk Alpha. #1231

Yes i just commented there hopefully there's a fix else i try magisk delta , thx

**Comment by MuntashirAkon** [comment] 2023-10-22 16:15
Ah, 1234, interesting issue number albeit a duplicate one

**Comment by MuntashirAkon** [comment] 2023-10-22 16:15
Duplicate of #1231

**Closed by MuntashirAkon** 2023-10-22 16:15 UTC
Labels: Duplicate, Help Wanted
