### ISSUE TITLE
Android 14 root mode issue

### ISSUE THREAD

**Issue by vhtlandroid** [MuntashirAkon/AppManager#1250] opened 2023-12-07 11:47 UTC
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

granting root permission in android 14 will cause the app crash instantly, regardless of any way to grant (e.g deny first then grant later, grant like normal. etc)

### To Reproduce

1. install app in android 14
2. open the app, and will appear a root permission request prompt
3. grant

### Expected behavior

crash instantly

### Logs

java.lang.IllegalStateException: External directory unavailable.
    at io.github.muntashirakon.AppManager.ipc.RootServiceManager.startRootProcess(RootServiceManager.java:161)
    at io.github.muntashirakon.AppManager.ipc.RootServiceManager.createBindTask(RootServiceManager.java:285)
    at io.github.muntashirakon.AppManager.ipc.RootService.bindOrTask(RootService.java:146)
    at io.github.muntashirakon.AppManager.ipc.RootService.bind(RootService.java:110)
    at io.github.muntashirakon.AppManager.ipc.RootService.bind(RootService.java:125)
    at io.github.muntashirakon.AppManager.ipc.ServiceConnectionWrapper.lambda$startDaemon$0$io-github-muntashirakon-AppManager-ipc-ServiceConnectionWrapper(ServiceConnectionWrapper.java:117)
    at io.github.muntashirakon.AppManager.ipc.ServiceConnectionWrapper$$ExternalSyntheticLambda0.run(Unknown Source:4)
    at android.os.Handler.handleCallback(Handler.java:958)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:205)
    at android.os.Looper.loop(Looper.java:294)
    at android.app.ActivityThread.main(ActivityThread.java:8173)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:554)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
 Caused by: java.io.FileNotFoundException: No available shared storage found.
   at io.github.muntashirakon.AppManager.utils.FileUtils.getExternalCachePath(FileUtils.java:210)
   at io.github.muntashirakon.AppManager.ipc.RootServiceManager.startRootProcess(RootServiceManager.java:159)
   at io.github.muntashirakon.AppManager.ipc.RootServiceManager.createBindTask(RootServiceManager.java:285)
   at io.github.muntashirakon.AppManager.ipc.RootService.bindOrTask(RootService.java:146)
   at io.github.muntashirakon.AppManager.ipc.RootService.bind(RootService.java:110)
   at io.github.muntashirakon.AppManager.ipc.RootService.bind(RootService.java:125)
   at io.github.muntashirakon.AppManager.ipc.ServiceConnectionWrapper.lambda$startDaemon$0$io-github-muntashirakon-AppManager-ipc-ServiceConnectionWrapper(ServiceConnectionWrapper.java:117)
   at io.github.muntashirakon.AppManager.ipc.ServiceConnectionWrapper$$ExternalSyntheticLambda0.run(Unknown Source:4)
   at android.os.Handler.handleCallback(Handler.java:958)
   at android.os.Handler.dispatchMessage(Handler.java:99)
   at android.os.Looper.loopOnce(Looper.java:205)
   at android.os.Looper.loop(Looper.java:294)
   at android.app.ActivityThread.main(ActivityThread.java:8173)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:554)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

Device Info:
App version: 3.1.3
App version code: 426
Android build version: 1700807130
Android release version: 14
Android SDK version: 34
Android build ID: evolution_spes-userdebug 14 UP1A.231105.003 1700807130 release-keys
Device brand: Redmi
Device manufacturer: Xiaomi
Device name: spes
Device model: 2201122G
Device product name: spes_global
Device hardware name: qcom
ABIs: [arm64-v8a]
ABIs (32bit): []
ABIs (64bit): [arm64-v8a]
System language: en-US-u-fw-mon-mu-celsius
In-App Language: auto
Mode: root
Inferred Mode: root

### Device info

- Device: Redmi Note 11 (4/128 variant)
- OS Version: Evolution X v8.0.3_COMMUNITY 
- App Manager Version: 3.1.3
- Mode: Root

### Additional context

unusable if grant root permission, but work if not, kinda useless for me

**Comment by MuntashirAkon** [comment] 2023-12-10 11:34
Duplicate of #948

**Closed by MuntashirAkon** 2023-12-10 11:34 UTC
Labels: Bug, Duplicate
