### ISSUE TITLE
2.6.2 fallback to non root

### ISSUE THREAD

**Issue by NSTAdventure** [MuntashirAkon/AppManager#517] opened 2021-07-18 00:35 UTC
- [√ ] I know what my device, OS and App Manager versions are
- [ √] I know how to take logs
- [ √] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**
App always request to fallback to non root mode

**To Reproduce**
Steps to reproduce the behaviour:
1. Open AM change mode to non root then adb again
2. Relaunch AM
3. AM will request fallback to non root mode

**Expected behavior**
AM work on ADB over TCP 

**Screenshots**

**Crash logs**
[logs-2021-07-18-07-29-39.zip](https://github.com/MuntashirAkon/AppManager/files/6835479/logs-2021-07-18-07-29-39.zip)

**Device info**
 - Device: Realme 5i
 - OS Version:Android 10
 - App Manager Version: 2.6.2
 - Mode: ADB

**Additional context**
Restarting? Sometime work sometime don't
Notifications? No there is no such notifications asking for keystroke like before

Delete data? Yes this one work perfectly 
*Tired*

**Comment by MuntashirAkon** [comment] 2021-07-18 02:00
Duplicate of #502

**Closed by MuntashirAkon** 2021-07-18 02:00 UTC
Labels: P3, S3, bug

**Comment by NSTAdventure** [comment] 2021-07-18 03:44
> Duplicate of #502

Bruh...... 🗿

**Comment by BigNdets** [comment] 2021-07-22 11:17
I'm experiencing this same problem. I don't know how to take logs or any other special operations. What's the solution?

**Comment by MuntashirAkon** [comment] 2021-07-22 12:20
> What's the solution?

See #502.
