### ISSUE TITLE
installation popup crashes

### ISSUE THREAD

**Issue by hakaishi** [MuntashirAkon/AppManager#621] opened 2021-11-12 16:31 UTC
- [x] I know what my device, OS and App Manager versions are
    - Google Pixel 4a (5G)
    - Android 12
    - AM version 2.6.4
- [x] I know how to take logs
- [x] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**
When trying to install something from f-droid, the conformation popup shows for the blink of an eye and crashes. The crash started after updating the device to Android 12.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to f-droid and try to install any app using the AppManager
2. Crash

**Expected behavior**
Conformation dialog with version information etc should popup.

**Crash logs**
```
java.lang.NoSuchMethodError: No interface method createSession(Landroid/content/pm/PackageInstaller$SessionParams;Ljava/lang/String;I)I in class Landroid/content/pm/IPackageInstaller; or its super classes (declaration of 'android.content.pm.IPackageInstaller' appears in /system/framework/framework.jar)
    at io.github.muntashirakon.AppManager.apk.installer.PackageInstallerCompat.openSession(PackageInstallerCompat.java:665)
    at io.github.muntashirakon.AppManager.apk.installer.PackageInstallerCompat.install(PackageInstallerCompat.java:527)
    at io.github.muntashirakon.AppManager.apk.installer.PackageInstallerService.onHandleIntent(PackageInstallerService.java:122)
    at io.github.muntashirakon.AppManager.types.ForegroundService$ServiceHandler.handleMessage(ForegroundService.java:40)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.os.HandlerThread.run(HandlerThread.java:67)

Device Info:
App version: 2.6.4
App version code: 394
Android build version: 7757856
Android release version: 12
Android SDK version: 31
Android build ID: SP1A.211105.003
Device brand: google
Device manufacturer: Google
Device name: bramble
Device model: Pixel 4a (5G)
Device product name: bramble
Device hardware name: bramble
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: de-DE
In-App Language: auto
Mode: auto
````

**Device info**
 - Device: Google Pixel 4a (5G)
 - OS Version: Android 12
 - App Manager Version: 2.6.4
 - Mode: stock rom

**Comment by MuntashirAkon** [comment] 2021-11-15 09:22
This occurred due to API changes in the Android framework in A12 and has already been fixed. (I was about to make a new release but then I've become too sick to look at the screen.)

**Comment by MuntashirAkon** [comment] 2021-11-15 09:23
Duplicate of #600

**Closed by MuntashirAkon** 2021-11-15 09:23 UTC
Labels: bug, S3, P3
