### ISSUE TITLE
`IndexOutOfBoundsException` in Receiver-View

### ISSUE THREAD

**Issue by joeftiger** [MuntashirAkon/AppManager#204] opened 2020-12-28 15:17 UTC
**Describe the bug**
Selecting `Receivers` or `App-Ops` on any app crashes the application.
It seems to be an `IndexOutOfBoundsException`

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to any app
2. Click on `Receivers` or `App-Ops`
3. Crash

**Expected behavior**
Show receivers or app-ops.

**Crash logs**
<details>
<summary>Log</summary>

```java
java.lang.ExceptionInInitializerError
    at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.loadAppOps(AppDetailsViewModel.java:897)
    at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.lambda$l0EWUQ8pwSEwIOu4g2r5od7Q6Ks(Unknown Source:0)
    at io.github.muntashirakon.AppManager.details.-$$Lambda$AppDetailsViewModel$l0EWUQ8pwSEwIOu4g2r5od7Q6Ks.run(Unknown Source:2)
    at java.lang.Thread.run(Thread.java:923)
 Caused by: java.lang.ArrayIndexOutOfBoundsException: length=100; index=100
   at io.github.muntashirakon.AppManager.appops.AppOpsManager.<clinit>(AppOpsManager.java:1286)
   at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.loadAppOps(AppDetailsViewModel.java:897)
   at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.lambda$l0EWUQ8pwSEwIOu4g2r5od7Q6Ks(Unknown Source:0)
   at io.github.muntashirakon.AppManager.details.-$$Lambda$AppDetailsViewModel$l0EWUQ8pwSEwIOu4g2r5od7Q6Ks.run(Unknown Source:2)
   at java.lang.Thread.run(Thread.java:923)

Device Info:
App version: 2.5.19-PRE
App version code: 373
Android build version: eng.rayste.20201220.113432
Android release version: 11
Android SDK version: 30
Android build ID: RQ1A.201205.008
Device brand: Xiaomi
Device manufacturer: Xiaomi
Device name: cepheus
Device model: Mi 9
Device product name: lineage_cepheus
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-GB
In-App Language: auto
```
</details>

**Device info**
 - Device: Xiaomi Mi 9
 - OS Version: CrDroid 7 (Android 11)
 - App Manager Version: 2.5.19-PRE 
 - Mode: root (Magisk)

**Additional context**
Happenes on the stable and prerelease on F-Droid

**Comment by MuntashirAkon** [comment] 2020-12-28 17:57
Duplicate of #194

**Closed by MuntashirAkon** 2020-12-28 17:57 UTC
Labels: P3, S3, bug
