### ISSUE TITLE
Support setting app to inactive mode

### ISSUE THREAD

**Issue by NSTAdventure** [MuntashirAkon/AppManager#414] opened 2021-04-28 08:52 UTC
**Is your feature request related to a problem? Please describe.**
No Issues Except Battery Hogging Apps

**Describe the solution you'd like**
Make App Manager Able To Put App In Stand By Mode

**Describe alternatives you've considered**
No Alternative Except Auto Force Stop Or Disable Background Behavior

**Additional context**
Additional Request:
-Allow AM To Auto Force Stop Apps

**Comment by MuntashirAkon** [comment] 2021-04-28 10:39
Duplicate of #342

**Comment by NSTAdventure** [comment] 2021-05-20 09:05
> Duplicate of #342

i mean i want am have ability to change app ops:
android.permission.CHANGE_APP_IDLE_STATE

like this sir 🙏

**Comment by MuntashirAkon** [comment] 2021-05-20 16:03
It seems Bravent actually meant **inactive mode** (or idle mode) rather than standby mode. Standby mode helps prioritise an app which is automatically handled by the system.

**Comment by MuntashirAkon** [comment] 2021-05-20 17:28
Standby mode is automatically handled by the OS. I don't see why this is necessary.

**Comment by NSTAdventure** [comment] 2021-05-21 05:21
> Standby mode is automatically handled by the OS. I don't see why this is necessary.

because android handling are bad sorry before 
i make you confused 🙏

**Comment by MuntashirAkon** [comment] 2021-05-21 06:51
> because android handling are bad

It doesn't work that way. The `pm set-inactive` is for debugging purpose only. Even if you set an app to inactive mode, the system will turn it off based on its usage. This behaviour cannot be controlled by a third-party app.

**Comment by NSTAdventure** [comment] 2021-05-22 13:02
> > because android handling are bad
> 
> It doesn't work that way. The `pm set-inactive` is for debugging purpose only. Even if you set an app to inactive mode, the system will turn it off based on its usage. This behaviour cannot be controlled by a third-party app.

even using service? but at least add those feature pls :( i don't want to pay any apps for it

**Comment by MuntashirAkon** [comment] 2021-05-22 13:39
> even using service?

The amount of energy the service will take to process the information is much more than amount of energy it saves. It's better to use force-stop or prevent the app from running in background in its entirety.

> but at least add those feature pls

I'm currently very busy, I am not working on any new feature as a result.

> i don't want to pay any apps for it

Paying is actually good. It makes one appreciative of the amount of effort a developer put in building an app. However, it's doesn't go with my no-string-attached model.

**Comment by NSTAdventure** [comment] 2021-05-23 01:15
> > even using service?
> 
> The amount of energy the service will take to process the information is much more than amount of energy it saves. It's better to use force-stop or prevent the app from running in background in its entirety.

but google android isn't that good the point i cannot believe on google anymore

> > but at least add those feature pls
> 
> I'm currently very busy, I am not working on any new feature as a result.

when you have free time sir no one will force you to add it now while you busy

> Paying is actually good. It makes one appreciative of the amount of effort a developer put in building an app. However, it's doesn't go with my no-string-attached model.

yeah? but i am not working yet :(

**Comment by MuntashirAkon** [comment] 2021-05-23 03:39
> but google android isn't that good the point

What you're in is called the [xy problem](https://en.wikipedia.org/wiki/XY_problem): Instead of trying to solve the real problem, you're trying to solve a problem that you think would help you solve the real problem.

> i cannot believe on google anymore

But last time I checked, you were still using Google services.

> when you have free time sir no one will force you to add it now while you busy

So, stop spamming about it everywhere. I know that it's an important feature. But as you can see in the README, I prioritise issues based on my own feelings about them, not based on what the community thinks about them.

> yeah? but i am not working yet :(

That's not an excuse. If you're capable of using a smartphone, you're capable of that too.

**Closed** 2023-01-19 06:02 UTC
Labels: Feature, Status: Pending, Priority: 5
