### ISSUE TITLE
Incorrect operation on Android 13 in root mode

### ISSUE THREAD

**Issue by Bladius2022** [MuntashirAkon/AppManager#1002] opened 2023-02-18 17:53 UTC
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

When the operating mode is set to Auto or Root (root permissions granted in Magisk), the program is stuck in the Initialization stage and does not start.  The same happens when you try to install some apk or apks file.  After many attempts, the program starts with the error that it is not able to work in the current mode and the previous settings have been restored.  Despite such a message, no settings in the program have changed.  On the other hand, selecting the no-root mode setting, the installer does not start at all when trying to install an apk or apks file.  Tested on Android 13 (ArrowOS 13 for Redmi Note 10)

### To Reproduce

1. Set the operating mode to Root.  
2. Give root permissions in Magisk.  
3. Try to run the program or some apk or apks installer

### Expected behavior

Normally the program should start or the installer should start.  However, the program and the installer are stuck at the Initialization or Authentication stage.  After several attempts, there is an error that the program is unable to work in the current mode and the previous one was restored.  However, after disabling root privileges in Magisk and going into the operating mode settings, you can see that the mode is still set to root.  I think that the program has a problem with correctly reading the root permissions granted in Magisk for Android 13

### Logs

https://mega.nz/file/Fw5VmABb#1UUyyvPPW8ObMfQJHylTsUrefML6v3ikSLn-0oumnKk

### Device info

- Device: Redmi Note 10 
- OS Version: Android 13
- App Manager Version: Any version
- Mode: Root

**Comment by Bladius2022** [comment] 2023-02-22 00:04
on a phone without root on Android 13, the program starts, but the installation of any apk or apks file goes on endlessly

**Comment by MuntashirAkon** [comment] 2023-02-22 06:28
> Despite such a message, no settings in the program have changed.

It does not alter any settings. It only falls back to the no-root mode for that session.

> Tested on Android 13 (ArrowOS 13 for Redmi Note 10)

We do have rooted users from ArrowOS 13. According to a recent poll, 52% of the users use App Manager in Android 13 (and later). So, I don't think the issues you're facing are universal.

> https://mega.nz/file/Fw5VmABb#1UUyyvPPW8ObMfQJHylTsUrefML6v3ikSLn-0oumnKk

Can you access this folder?

```
/storage/emulated/0/Android/data/io.github.muntashirakon.AppManager/cache
```

**Comment by MuntashirAkon** [comment] 2023-02-22 06:31
Could be a duplicate of #948.

**Comment by Bladius2022** [comment] 2023-02-22 10:47
I'll check when I get home.  However, I noticed that the installation of APKS files still does not work, the installer does not even start.

**Comment by MuntashirAkon** [comment] 2023-02-22 12:25
Nothing will work properly if App Manager cannot access its cache directory.

**Comment by Bladius2022** [comment] 2023-02-22 17:50
Folder cache missing, I have acces /storage/emulated/0/Android/data/io.github.muntashirakon.AppManager

**Comment by MuntashirAkon** [comment] 2023-02-23 08:48
> Folder cache missing, I have acces /storage/emulated/0/Android/data/io.github.muntashirakon.AppManager. i created it manually but it didn't help. In Magisk, root permissions are granted, the program is set in root mode, but it still suggests me to work without root

App Manager will not work if it cannot store anything. Make sure that the cache folder exists and it has proper permissions.

**Comment by MuntashirAkon** [comment] 2023-02-23 08:49
Duplicate of #948

**Closed by MuntashirAkon** 2023-02-23 08:49 UTC
Labels: Bug

**Comment by Bladius2022** [comment] 2023-02-23 13:43
a manually created folder has the same permissions as the files folder automatically created by App Manager.  Nothing has changed

**Comment by Bladius2022** [comment] 2023-02-23 13:45
![Uploading Screenshot_20230223-144350_Solid Explorer.png…]()

**Comment by Bladius2022** [comment] 2023-02-23 13:46
![Screenshot_20230223-144350_Solid Explorer](https://user-images.githubusercontent.com/112637245/220925029-50d222e2-e2e9-45d2-9623-a3d4cc94605d.png)

**Comment by MuntashirAkon** [comment] 2023-02-23 18:46
> a manually created folder has the same permissions as the files folder automatically created by App Manager. Nothing has changed

Check for UID-GID, not just these, and please post your updates to the linked issue instead of here.
