### ISSUE TITLE
Running apps no working 

### ISSUE THREAD

**Issue by zkollz** [MuntashirAkon/AppManager#1138] opened 2023-08-01 07:57 UTC
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

the running apps manager not working, is very bugged

### To Reproduce

open 3dots menu, open running Apps option

### Expected behavior

only the appmanager process is shown and when refreshing later nothing is shown

### Screenshots

![Screenshot_2023-07-31-21-37-43-282_io github muntashirakon AppManager](https://github.com/MuntashirAkon/AppManager/assets/97865793/a0dc78a6-c26c-4164-a5f9-0a77a3e0e860)
![Screenshot_2023-07-31-19-29-50-518_io github muntashirakon AppManager](https://github.com/MuntashirAkon/AppManager/assets/97865793/6786ff21-55e5-4dee-9638-b5d93df5769f)

### Device info

- Device: Xiaomi Poco F3 (alioth)
- OS Version: A13
- App Manager Version: 4.0.0-alpha01
- Mode: Root

**Comment by hirenshah** [comment] 2023-08-23 22:06
I've found that it works the first time, but as soon as you actually do something it ends up only showing App Manger. 

To get it working again, you have to force close the app and start again. 

https://github.com/MuntashirAkon/AppManager/assets/418112/fc4651c1-f6e6-4d87-9a5c-54aa40c2f339

**Comment by vordx** [comment] 2023-09-01 13:46
I came to report this bug also.

I noticed that if you change anything it breaks and doesn't work anymore until you force close the app.

**Comment by MuntashirAkon** [comment] 2023-09-02 09:38
> I've found that it works the first time, but as soon as you actually do something it ends up only showing App Manger.

Thanks for your report. I was able to reproduce your video. I'll fix it before the next alpha.

**Comment by MuntashirAkon** [comment] 2023-09-02 10:37
It appears the issue I faced (916331fc870ffbef34e8b1b65fed9c0223a7a93b) might not be the same as yours. But there's no reason not to test it.

**Comment by hirenshah** [comment] 2023-09-03 18:41
> It appears the issue I faced (916331fc870ffbef34e8b1b65fed9c0223a7a93b) might not be the same as yours. But there's no reason not to test it.

Do I have to uninstall the alpha version first? Struggling to get past the Wireless ADB pairing with the debug build (installed alongside the alpha).

**Comment by MuntashirAkon** [comment] 2023-09-05 19:43
> Do I have to uninstall the alpha version first?

No.

> Struggling to get past the Wireless ADB pairing with the debug build (installed alongside the alpha).

Create a new issue with logs. I'll look into it.

**Comment by BigKananga** [comment] 2023-09-21 22:48
I had the same problem on my Samsung GT-N5110 on unofficial LineageOS 16 (Android 9) and Magisk 24.1 with versions 3.1.1 and 3.1.2. The current alpha is working fine.

**Comment by MuntashirAkon** [comment] 2023-09-22 15:01
> I had the same problem on my Samsung GT-N5110 on unofficial LineageOS 16 (Android 9) and Magisk 24.1 with versions 3.1.1 and 3.1.2. The current alpha is working fine.

Thanks for testing. @zkollz: Can you confirm whether it is also fixed for you in the latest alpha (v4.0.0-alpha02)?

**Comment by hirenshah** [comment] 2023-09-26 13:10
All good with the latest alpha 👍

**Comment by hirenshah** [comment] 2023-09-26 21:42
Spoke too soon. Just opened the app which was cached / running in the background and was greeting with:
![Screenshot_20230926_223854_App Manager](https://github.com/MuntashirAkon/AppManager/assets/418112/041e3c10-4082-405c-8f3c-79d55ca5b8dd)

**Comment by hirenshah** [comment] 2023-09-27 00:54
https://github.com/MuntashirAkon/AppManager/assets/418112/a7743288-cb75-4556-aaa0-2cfdfa48588e

**Comment by MuntashirAkon** [comment] 2023-09-27 10:27
@hirenshah: I need logs from a debug release, videos won't do any help since it's no longer reproducible on my side.

**Comment by hirenshah** [comment] 2023-09-28 01:26
> @hirenshah: I need logs from a debug release, videos won't do any help since it's no longer reproducible on my side.

I've just installed the latest v4 debug build and only managed to replicate the issue once. Have tried to reproduce it again but it seems to be working as expected.

I've uploaded the log file here:
https://hirenshah.co.uk/am.log

**Comment by hirenshah** [comment] 2023-09-30 04:32
@MuntashirAkon Was that file at all useful?

**Comment by MuntashirAkon** [comment] 2023-09-30 08:44
> Was that file at all useful?

It doesn't contain anything unexpected.

**Comment by MuntashirAkon** [comment] 2024-07-06 18:07
Maybe fixed by 544d92746f5166e822e3564b0115f467126417b7. Can anybody check?

**Comment by zkollz** [comment] 2024-07-06 23:00
> Maybe fixed by 544d92746f5166e822e3564b0115f467126417b7. Can anybody check?

I noticed it was fixed at least two versions ago.

**Closed** 2024-07-07 04:23 UTC
Labels: Bug, Status: Pending, Severity: 1, Priority: 1
