### ISSUE TITLE
Shizuku

### ISSUE THREAD

**Issue by Jak2k** [MuntashirAkon/AppManager#1385] opened 2024-05-27 13:24 UTC
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

Get elevated rights using shizuku.

**Comment by shuvashish76** [comment] 2024-05-30 07:05
https://muntashirakon.github.io/AppManager/en/#subsec:faq:shizuku-support
https://github.com/amcommunity/TipsAndTricks/issues/14

Duplicate of #55

**Comment by shuvashish76** [comment] 2024-05-30 19:27
@Jak2k Duplicate request of #892
https://github.com/MuntashirAkon/AppManager/commit/42c316fd501771699f55d2bcd0e9f2882d405c7a Already available for v4.0.0-beta01

**Closed** 2024-05-30 21:08 UTC
Labels: Duplicate, Feature

**Comment by MuntashirAkon** [comment] 2024-06-02 05:43
Duplicate of #55
