### ISSUE TITLE
Backup in latest debug seems broken [ExtSDCard]

### ISSUE THREAD

**Issue by Cyberavater** [MuntashirAkon/AppManager#615] opened 2021-11-01 07:40 UTC
All apps I tried failed to backup on the latest debug

Log:

```
E/BatchOpsManager
io.github.muntashirakon.AppManager.backup.BackupException: Failed to backup data directory at /data/user/0/com.nordvpn.android
 at io.github.muntashirakon.AppManager.backup.BackupOp.backupData(BackupOp.java:295)
 at io.github.muntashirakon.AppManager.backup.BackupOp.runBackup(BackupOp.java:168)
 at io.github.muntashirakon.AppManager.backup.BackupManager.backup(BackupManager.java:89)
 at io.github.muntashirakon.AppManager.batchops.BatchOpsManager.lambda$opBackupRestore$0$BatchOpsManager(BatchOpsManager.java:288)
 at io.github.muntashirakon.AppManager.batchops.-$$Lambda$BatchOpsManager$fRbL-cOU1e30grqu_qUYfkugpEc.run(Unknown Source:10)
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
 at
```

Note: I haven't tried on phone storage.

**Comment by MuntashirAkon** [comment] 2021-11-01 08:01
Related issue #614.

This is a known issue. Downgrade to a working version until it is fixed.

**Comment by Cyberavater** [comment] 2021-11-01 08:57
Last working version, for those who might come across this issue;

https://t.me/AppManagerDebug/1944

**Comment by MuntashirAkon** [comment] 2021-11-03 02:48
Duplicate of #614

**Closed by MuntashirAkon** 2021-11-03 02:48 UTC
Labels: bug, S3, P3
