### ISSUE TITLE
App Manager Crash when trying to edit DANA

### ISSUE THREAD

**Issue by IndividualZenbo21** [MuntashirAkon/AppManager#1403] opened 2024-07-09 20:10 UTC
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

It crashes App Manager when pressing DANA

### To Reproduce

1. Search DANA
2. Click DANA
3. App Manager Crashes

### Logs

java.lang.RuntimeException: Unable to start activity ComponentInfo{io.github.muntashirakon.AppManager/io.github.muntashirakon.AppManager.details.AppDetailsActivity}: java.lang.RuntimeException: Cannot create an instance of class io.github.muntashirakon.AppManager.details.AppDetailsViewModel
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3984)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4164)
    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:114)
    at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:231)
    at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:152)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:93)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2595)
    at android.os.Handler.dispatchMessage(Handler.java:107)
    at android.os.Looper.loopOnce(Looper.java:232)
    at android.os.Looper.loop(Looper.java:317)
    at android.app.ActivityThread.main(ActivityThread.java:8586)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:585)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
 Caused by: java.lang.RuntimeException: Cannot create an instance of class io.github.muntashirakon.AppManager.details.AppDetailsViewModel
   at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:320)
   at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:304)
   at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:278)
   at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.kt:128)
   at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:187)
   at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:153)
   at io.github.muntashirakon.AppManager.details.AppDetailsActivity.onAuthenticated(AppDetailsActivity.java:96)
   at io.github.muntashirakon.AppManager.BaseActivity.onCreate(BaseActivity.java:87)
   at android.app.Activity.performCreate(Activity.java:8984)
   at android.app.Activity.performCreate(Activity.java:8962)
   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1535)
   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3966)
   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4164)
   at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:114)
   at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:231)
   at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:152)
   at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:93)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2595)
   at android.os.Handler.dispatchMessage(Handler.java:107)
   at android.os.Looper.loopOnce(Looper.java:232)
   at android.os.Looper.loop(Looper.java:317)
   at android.app.ActivityThread.main(ActivityThread.java:8586)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:585)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
 Caused by: java.lang.reflect.InvocationTargetException
   at java.lang.reflect.Constructor.newInstance0(Native Method)
   at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
   at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:312)
   at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:304)
   at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:278)
   at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.kt:128)
   at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:187)
   at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:153)
   at io.github.muntashirakon.AppManager.details.AppDetailsActivity.onAuthenticated(AppDetailsActivity.java:96)
   at io.github.muntashirakon.AppManager.BaseActivity.onCreate(BaseActivity.java:87)
   at android.app.Activity.performCreate(Activity.java:8984)
   at android.app.Activity.performCreate(Activity.java:8962)
   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1535)
   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3966)
   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4164)
   at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:114)
   at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:231)
   at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:152)
   at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:93)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2595)
   at android.os.Handler.dispatchMessage(Handler.java:107)
   at android.os.Looper.loopOnce(Looper.java:232)
   at android.os.Looper.loop(Looper.java:317)
   at android.app.ActivityThread.main(ActivityThread.java:8586)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:585)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
 Caused by: java.lang.NoSuchMethodError: No interface method grantRuntimePermission(Ljava/lang/String;Ljava/lang/String;II)V in class Landroid/permission/IPermissionManager; or its super classes (declaration of 'android.permission.IPermissionManager' appears in /system/framework/framework.jar!classes3.dex)
   at io.github.muntashirakon.AppManager.compat.PermissionCompat.grantPermission(PermissionCompat.java:354)
   at io.github.muntashirakon.AppManager.compat.AppOpsManagerCompat.<init>(AppOpsManagerCompat.java:629)
   at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.<init>(AppDetailsViewModel.java:668)
   at java.lang.reflect.Constructor.newInstance0(Native Method)
   at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
   at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:312)
   at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:304)
   at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:278)
   at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.kt:128)
   at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:187)
   at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:153)
   at io.github.muntashirakon.AppManager.details.AppDetailsActivity.onAuthenticated(AppDetailsActivity.java:96)
   at io.github.muntashirakon.AppManager.BaseActivity.onCreate(BaseActivity.java:87)
   at android.app.Activity.performCreate(Activity.java:8984)
   at android.app.Activity.performCreate(Activity.java:8962)
   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1535)
   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3966)
   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4164)
   at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:114)
   at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:231)
   at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:152)
   at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:93)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2595)
   at android.os.Handler.dispatchMessage(Handler.java:107)
   at android.os.Looper.loopOnce(Looper.java:232)
   at android.os.Looper.loop(Looper.java:317)
   at android.app.ActivityThread.main(ActivityThread.java:8586)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:585)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)

Device Info:
App version: 3.1.6
App version code: 429
Android build version: eng.sambas.20240708.165732
Android release version: 14
Android SDK version: 34
Android build ID: AP2A.240705.005.A1
Device brand: POCO
Device manufacturer: Xiaomi
Device name: marble
Device model: 23049PCD8G
Device product name: marble_global
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-US
In-App Language: auto
Mode: auto
Inferred Mode: root

### Device info

- Device: Poco F5
- OS Version: Android 14
- App Manager Version: 3.1.6
- Mode: Root

**Comment by MuntashirAkon** [comment] 2024-07-09 21:41
Duplicate of #1397

**Closed by MuntashirAkon** 2024-07-09 21:41 UTC
Labels: Bug, Duplicate
