### ISSUE TITLE
App info keeps loading for some apps

### ISSUE THREAD

**Issue by shifoc** [MuntashirAkon/AppManager#820] opened 2022-08-04 07:18 UTC
- [x] I know what my device, OS and App Manager versions are
- [ ] I know how to take logs
- [x] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**
App info keeps loading for some apps. In my case it's WhatsApp

**To Reproduce**
Steps to reproduce the behaviour:
1. Click on an app

**Screenshots**
![Screenshot_20220804-101415_App Manager](https://user-images.githubusercontent.com/32818143/182787495-c49fa722-a7f3-446a-b4b5-24a95eb24216.jpg)

**Device info**
 - Device: S22 Ultra
 - OS Version: Android 12
 - App Manager Version: v3.0.0
 - Mode: auto (no-root)

**Comment by MuntashirAkon** [comment] 2022-08-04 08:09
The issue isn't reproducible on my device (Android 11). So, it could be an A12-specific issue. Can you take some logs using the log viewer and post here?

**Comment by MuntashirAkon** [comment] 2022-09-11 06:51
Closed due to lack of response. Feel free to open it again if you're still facing the issue.

**Comment by shifoc** [comment] 2022-09-11 06:58
> Closed due to lack of response. Feel free to open it again if you're still facing the issue.

I sent the log by mail at the time

**Comment by MuntashirAkon** [comment] 2022-09-11 07:44
You have to take logs using the debug variants. Release variants do not print debug logs.

**Comment by shifoc** [comment] 2022-09-21 07:56
It seems to be working after reinstalling although it can take some time to retrieve the info

**Comment by MuntashirAkon** [comment] 2022-09-21 08:05
> It seems to be working after reinstalling although it can take some time to retrieve the info

Yes, it's stated in the changelogs. This will be fixed after #866, you can watch the issue if you want.

Closing for now.

**Closed by MuntashirAkon** 2022-09-21 08:05 UTC
Labels: Bug, Status: Pending, More Info Needed
