### ISSUE TITLE
The application does not start when recovering a working or other profile

### ISSUE THREAD

**Issue by mrwhaler** [MuntashirAkon/AppManager#671] opened 2022-02-05 20:56 UTC
- [x] I know what my device, OS and App Manager versions are
- [x] I know how to take logs
- [x] I know how to reproduce the issue which may not be specific to my device

**The application does not start when recovering a working or other profile.** 

**To Reproduce**
1. Create a backup (any depth).
2. Restore to a working or other profile.
3. Detect that the application does not work. It seems to not find a way to its data.
Creating a backup tried to do from both the main and the worker. From the working to the worker, it also does not work (I only managed to make LACKYPATCHER (bad)).

**Device info**
 - Lineage OS
 - OS Version: 11
 - App Manager Version: last
 - Mode: root

**Comment by MuntashirAkon** [comment] 2022-03-15 03:54
Not reproducible in the latest version on Android 10. You have to share some logs.

**Comment by mrwhaler** [comment] 2022-03-24 17:47
Android 11

**Comment by MuntashirAkon** [comment] 2022-03-28 07:49
It also works in Android 11 (from the apps I've tested). It might be applicable for only a few app, I think. So, you should start by trying the apps that failed in the past (or you can name those apps so that I or one of the testers might try).

**Comment by mrwhaler** [comment] 2022-04-01 07:15
This is applicable to all applications that have a challenging organization, external data, media and obb, games, a reservation application copy of which was made on Android 10.

**Comment by MuntashirAkon** [comment] 2022-06-25 04:16
There seems to be some unprecedented consequences in restoring backups in other profiles. This feature will be disabled until I find a proper way of addressing the issue.

**Comment by MuntashirAkon** [comment] 2023-02-15 10:33
Fixed in 4b23278761f73689d618b5856b4cb25b03285ad0

**Closed by MuntashirAkon** 2023-02-15 10:33 UTC
Labels: Bug, Priority: 3, Severity: 0, Feature: Backup, Status: Accepted
