### ISSUE TITLE
Force-close on providers tab

### ISSUE THREAD

**Issue by divyansh10101** [MuntashirAkon/AppManager#306] opened 2021-03-04 10:06 UTC
**To Reproduce**
Steps to reproduce the behaviour:
1. Select an app from list
2. Click on providers tab

**Crash logs**
java.lang.ExceptionInInitializerError
    at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.loadAppOps(AppDetailsViewModel.java:917)
    at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.lambda$l0EWUQ8pwSEwIOu4g2r5od7Q6Ks(Unknown Source:0)
    at io.github.muntashirakon.AppManager.details.-$$Lambda$AppDetailsViewModel$l0EWUQ8pwSEwIOu4g2r5od7Q6Ks.run(Unknown Source:2)
    at java.lang.Thread.run(Thread.java:923)
 Caused by: java.lang.ArrayIndexOutOfBoundsException: length=100; index=100
   at io.github.muntashirakon.AppManager.appops.AppOpsManager.<clinit>(AppOpsManager.java:1410)
   at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.loadAppOps(AppDetailsViewModel.java:917)
   at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.lambda$l0EWUQ8pwSEwIOu4g2r5od7Q6Ks(Unknown Source:0)
   at io.github.muntashirakon.AppManager.details.-$$Lambda$AppDetailsViewModel$l0EWUQ8pwSEwIOu4g2r5od7Q6Ks.run(Unknown Source:2)
   at java.lang.Thread.run(Thread.java:923)

Device Info:
App version: 2.5.20
App version code: 375
Android build version: 583158c61f
Android release version: 11
Android SDK version: 30
Android build ID: RQ1A.210105.003
Device brand: Xiaomi
Device manufacturer: Xiaomi
Device name: whyred
Device model: Redmi Note 5 Pro
Device product name: whyred
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-US
In-App Language: auto

**Comment by MuntashirAkon** [comment] 2021-03-05 02:59
Duplicate of #194

**Closed by MuntashirAkon** 2021-03-05 02:59 UTC
Labels: P3, S3, bug, duplicate
