### ISSUE TITLE
Change ssaid not working 

### ISSUE THREAD

**Issue by QPLAYid** [MuntashirAkon/AppManager#932] opened 2022-11-16 10:49 UTC
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

I change ssaid not working not happenin

### Device info

- Device:
- OS Version:
- App Manager Version:
- Mode: Root/ADB/NonRoot

**Comment by QPLAYid** [comment] 2022-11-16 10:50
I try mode root

**Comment by QPLAYid** [comment] 2022-11-16 10:50
Android 12

**Comment by MuntashirAkon** [comment] 2022-11-16 10:53
Duplicate of #457

**Closed by MuntashirAkon** 2022-11-16 10:53 UTC
Labels: Bug, Duplicate
