### ISSUE TITLE
JSON format for exporting app list

### ISSUE THREAD

**Issue by balporig** [MuntashirAkon/AppManager#1375] opened 2024-05-09 08:56 UTC
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

Option to export app list in JSON format

**Comment by shuvashish76** [comment] 2024-05-10 00:39
> Option to export app list in JSON format

https://github.com/MuntashirAkon/AppManager/issues/1233#issuecomment-1773866634

Duplicate of #122

**Comment by MuntashirAkon** [comment] 2024-05-12 04:54
Duplicate of #122

**Closed by MuntashirAkon** 2024-05-12 04:54 UTC
Labels: Duplicate, Feature
