### ISSUE TITLE
bug always Force stop 

### ISSUE THREAD

**Issue by Shylent1** [MuntashirAkon/AppManager#666] opened 2022-02-03 10:50 UTC
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 3(offset:3).state:5 io.github.muntashirakon.widget.RecyclerViewWithEmptyView{8c5f51 VFED..... ......ID 0,0-1000,1801 #7f09022b app:id/recycler_view}, adapter:io.github.muntashirakon.AppManager.details.AppDetailsFragment$AppDetailsRecyclerAdapter@c1c6d3e, layout:androidx.recyclerview.widget.LinearLayoutManager@d57979f, context:io.github.muntashirakon.AppManager.details.AppDetailsActivity@948606
    at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6364)
    at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6300)
    at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6296)
    at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2330)
    at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1631)
    at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
    at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:668)
    at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4309)
    at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4012)
    at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4578)
    at android.view.View.layout(View.java:22488)
    at android.view.ViewGroup.layout(ViewGroup.java:6303)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
    at android.view.View.layout(View.java:22488)
    at android.view.ViewGroup.layout(ViewGroup.java:6303)
    at androidx.appcompat.widget.LinearLayoutCompat.setChildFrame(LinearLayoutCompat.java:1669)
    at androidx.appcompat.widget.LinearLayoutCompat.layoutVertical(LinearLayoutCompat.java:1523)
    at androidx.appcompat.widget.LinearLayoutCompat.onLayout(LinearLayoutCompat.java:1431)
    at android.view.View.layout(View.java:22488)
    at android.view.ViewGroup.layout(ViewGroup.java:6303)
    at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:688)
    at android.view.View.layout(View.java:22488)
    at android.view.ViewGroup.layout(ViewGroup.java:6303)
    at androidx.viewpager.widget.ViewPager.onLayout(ViewPager.java:1775)
    at android.view.View.layout(View.java:22488)
    at android.view.ViewGroup.layout(ViewGroup.java:6303)
    at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:148)
    at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
    at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:2122)
    at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)
    at android.view.View.layout(View.java:22488)
    at android.view.ViewGroup.layout(ViewGroup.java:6303)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
    at android.view.View.layout(View.java:22488)
    at android.view.ViewGroup.layout(ViewGroup.java:6303)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
    at android.view.View.layout(View.java:22488)
    at android.view.ViewGroup.layout(ViewGroup.java:6303)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
    at android.view.View.layout(View.java:22488)
    at android.view.ViewGroup.layout(ViewGroup.java:6303)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
    at android.view.View.layout(View.java:22488)
    at android.view.ViewGroup.layout(ViewGroup.java:6303)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
    at com.android.internal.policy.DecorView.onLayout(DecorView.java:779)
    at android.view.View.layout(View.java:22488)
    at android.view.ViewGroup.layout(ViewGroup.java:6303)
    at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3157)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2614)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1745)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7781)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:967)
    at android.view.Choreographer.doCallbacks(Choreographer.java:791)
    at android.view.Choreographer.doFrame(Choreographer.java:726)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
    at android.os.Handler.handleCallback(Handler.java:883)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:7356)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:925)

Device Info:
App version: 2.7.0-1673-DEBUG
App version code: 395
Android build version: eng.ademir.20200725.133218
Android release version: 10
Android SDK version: 29
Android build ID: QQ3A.200705.002
Device brand: Xiaomi
Device manufacturer: Xiaomi
Device name: daisy
Device model: SM-G965F
Device product name: havoc_daisy
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-US
In-App Language: auto
Mode: auto

**Comment by MuntashirAkon** [comment] 2022-02-05 13:58
Should be fixed in 7a19572c. Since I cannot reproduce the issue. It's up to you to report back to me.

**Closed** 2022-02-05 14:06 UTC
Labels: bug, S3, P3
