### ISSUE TITLE
SSAID Android 12 support

### ISSUE THREAD

**Issue by Rexadev** [MuntashirAkon/AppManager#870] opened 2022-09-16 09:05 UTC
- [x] I am using the latest version of App Manager
- [x] I have searched the issues and haven't found anything relevant
- [x] I have read the docs

**Is your feature request related to a problem? Please describe.**

I need to fix safetynet on microG device. That feature which changes the UUID for the app that when changed appManager  asks to reboot immediately 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by MuntashirAkon** [comment] 2022-09-16 09:07
Sorry, but what is **App Code/ID**?

**Comment by Rexadev** [comment] 2022-09-16 09:12
> That feature which changes the UUID for the app that when changed appManager asks to reboot immediately

That feature which changes the UUID for the app that when changed appManager asks to reboot immediately

**Comment by MuntashirAkon** [comment] 2022-09-16 09:12
You mean SSAID? SSAID is not currently supported on Android 12 and later. See #631.

**Comment by MuntashirAkon** [comment] 2022-09-16 09:43
Duplicate of #457

**Closed by MuntashirAkon** 2022-09-16 09:43 UTC
Labels: Feature
