### ISSUE TITLE
Unable to obtain root permissions in the latest version of magisk alpha

### ISSUE THREAD

**Issue by E3GhostDv** [MuntashirAkon/AppManager#1231] opened 2023-10-21 08:38 UTC
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Magisk 15e13a8d-alpha 26302
https://github.com/LSPosed/Magisk/commits/0ead0d33274fa8e382cd372f90b7db7a02cc463d
put suffix .zip delete that is apk 
[app-release.apk.zip](https://github.com/MuntashirAkon/AppManager/files/13060284/app-release.apk.zip)

This version abandons riru compatibility because it hides internal mount points.
Magisk Alpha Root permissions can be granted normally, but App Manager cannot pass.

### Device info

- Device: Samsung Galaxy Note20 Ultra 
- OS Version: Android 13 One UI 5.1
- App Manager Version: AppManager_v4.0.0-alpha02 , AppManager_v3.1.3
- Mode: Root

**Comment by frayos** [comment] 2023-10-21 10:54
I have the same problem

**Comment by MuntashirAkon** [comment] 2023-10-21 17:04
I don't think we can do anything about it unless they document what's changed. (The link to commit above does not exist.)

**Comment by Yoongdeer** [comment] 2023-10-22 04:54
Facing this issue also any feedback appreciated

**Comment by Yoongdeer** [comment] 2023-10-22 05:35
> I don't think we can do anything about it unless they document what's changed. (The link to commit above does not exist.)

https://install.appcenter.ms/users/vvb2060/apps/magisk/distribution_groups/public

This but in Chinese

**Comment by Yoongdeer** [comment] 2023-10-22 10:56
> > I have the same problem
> 
> What I do is use fallback to use the old version. Because of this alpha version, several of my apps cannot be used normally.

U mean i have to download the older ver for alpha apk and it will work ?? any issue?

**Comment by Yoongdeer** [comment] 2023-10-22 17:09
> > > > I have the same problem
> > > 
> > > 
> > > What I do is use fallback to use the old version. Because of this alpha version, several of my apps cannot be used normally.
> > 
> > 
> > U mean i have to download the older ver for alpha apk and it will work which ver?? any issue?
> 
> 26301 There are no issues with this version. But! Please remember that you cannot downgrade directly, you must fully back up all data, format it, and finally flash the modified image.

Too headache guess i will wait or something hopefully have a way

**Comment by fgjaee** [comment] 2023-10-24 18:43
I did not have this problem. P6P Magisk Alpha 26203.

**Comment by Yoongdeer** [comment] 2023-10-25 03:59
> Latest magisk alpha bb39a524-alpha 26302 fixed this issue.

Just updated the magisk app confirm its working this version thanks

**Comment by C4RP3N0CT3M** [comment] 2023-10-27 18:31
This is still happening to me on the latest Alpha.

**Comment by omegavschaos** [comment] 2024-01-30 13:22
I still reproduce this since i'm on the canary version 65207f96 (26404).
But it happen on other app that request root too. Like Tasker.
To **workaround** I can deny during the magisk popup instead of according the root.
And then the denied app are listed in the magisk manager and you can toggle to accord SuperSU.
You can restart the app to let it retry the root access request that normally will pass.

**Comment by MuntashirAkon** [comment] 2024-03-19 09:43
I think the issue was fixed in the stable branch v27.0 (27000)

**Closed by MuntashirAkon** 2024-03-19 09:43 UTC
Labels: Bug, Third-party Issue
