### ISSUE TITLE
App 3.0.1 regularly crashes on Android 11, oneplus3, msm-xtended custom ROM 

### ISSUE THREAD

**Issue by tmstaedt** [MuntashirAkon/AppManager#869] opened 2022-09-16 03:50 UTC
- [x] I know what my device, OS and App Manager versions are
- [z] I know how to take logs
- [ x I know how to reproduce the issue which may not be specific to my device

**Describe the bug**
crash

java.lang.RuntimeException: Parcel android.os.Parcel@8d734cd: Unmarshalling unknown type code 6881398 at offset 728
    at android.os.Parcel.readValue(Parcel.java:3253)
    at android.os.Parcel.readSparseArrayInternal(Parcel.java:3650)
    at android.os.Parcel.readSparseArray(Parcel.java:2792)
    at android.os.Parcel.readValue(Parcel.java:3231)
    at android.os.Parcel.readArrayMapInternal(Parcel.java:3567)
    at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
    at android.os.BaseBundle.unparcel(BaseBundle.java:236)
    at android.os.Bundle.getSparseParcelableArray(Bundle.java:1079)
    at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2207)
    at android.app.Activity.onRestoreInstanceState(Activity.java:1679)
    at android.app.Activity.performRestoreInstanceState(Activity.java:1632)
    at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1356)
    at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3474)
    at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
    at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2067)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:223)
    at android.app.ActivityThread.main(ActivityThread.java:7670)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)

Device Info:
App version: 3.0.1
App version code: 412
Android build version: 3339
Android release version: 11
Android SDK version: 30
Android build ID: RQ3A.211001.001
Device brand: OnePlus
Device manufacturer: OnePlus
Device name: OnePlus3T
Device model: ONEPLUS A3003
Device product name: xtended_oneplus3
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: de-DE
In-App Language: auto
Mode: auto
Inferred Mode: root

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behavior**

**Screenshots**

**Crash logs**
If applicable, add crash logs to help us figure out the problem.

**Device info**
 - Device: [e.g. One Plus 8 Pro]
 - OS Version: [e.g. Android 10]
 - App Manager Version: [e.g. v2.5.13]
 - Mode: root/adb/no-root

**Additional context**

**Comment by MuntashirAkon** [comment] 2022-09-16 04:06
Duplicate of #656

**Closed by MuntashirAkon** 2022-09-16 04:06 UTC
Labels: Bug, Duplicate
