### ISSUE TITLE
3.1.0 not showing installed apps for user #0

### ISSUE THREAD

**Issue by 0xlne** [MuntashirAkon/AppManager#861] opened 2022-09-06 09:29 UTC
- [x] I know what my device, OS and App Manager versions are
- [x] I know how to take logs
- [x] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**
The debug builds (tested some sub#2000), but also tested today, v3.1.0 build 2001, do not display user apps (example: installed for user #0. If I select "display installed apps", only App Manager is shown. If I deselect this, I'm shown only App Manager & apps installed in the work profile. Not selecting any filters shows all system apps replicated for the proper functioning of the work profile.
For the sake of clarity, App Manager has been installed in the main profile (user #0).
**v3.0 stable works correctly.**

**To Reproduce**
Steps to reproduce the behaviour:
1. Install App Manager (tested builds 199x up to 2001).
2. click on filter - user apps

**Expected behavior**
List of all user #0 apps to be displayed.

**Crash logs**
N/A

**Device info**
 - Device: Xiaomi Mix Fold 2, Red Magic 6
 - OS Version: Android 12, Android 11
 - App Manager Version: v3.1.0 build #2001
 - Mode: auto & wireless debugging

**Additional context**
N/A

**Comment by MuntashirAkon** [comment] 2022-09-11 03:02
Have you tried clearing data?

**Comment by 0xlne** [comment] 2022-09-14 00:55
Yes & I also tried reinstalling from scratch.
I noticed this behaviour on 2 separate devices; stable v3.0.0 & 3.0.1 are OK, debug versions from Telegram v3.1.0 are not.

**Comment by NSTAdventure** [comment] 2022-09-18 01:26
> Yes & I also tried reinstalling from scratch (i.e. uninstall, & install again). I noticed this behaviour on 2 separate devices; stable v3.0.0 & 3.0.1 are OK, debug versions from Telegram v3.1.0 are not.

I can confirm this on 3.x.x version
Especially adb user
This one is horsemen of annoyance 
Because adb always stuck even after clearing cache or data or rebooting causing app list will stuck in loading forever 🤦

**Comment by MuntashirAkon** [comment] 2022-09-20 11:41
Should be fixed in 3ec50c83839fb169335b78a82af665e171303bc3. Please check.

**Closed by MuntashirAkon** 2022-09-20 11:41 UTC
Labels: Bug, Severity: 1, Status: Accepted

**Comment by 0xlne** [comment] 2022-11-28 22:49
Confirmed fixed.
