### ISSUE TITLE
Crash app installer work profile

### ISSUE THREAD

**Issue by userkilled** [MuntashirAkon/AppManager#1205] opened 2023-09-28 14:14 UTC
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

java.lang.SecurityException: createSession: Neither user 1210145 nor current process has android.permission.INTERACT_ACROSS_USERS_FULL.
    at android.os.Parcel.createException(Parcel.java:2071)
    at android.os.Parcel.readException(Parcel.java:2039)
    at android.os.Parcel.readException(Parcel.java:1987)
    at android.content.pm.IPackageInstaller$Stub$Proxy.createSession(IPackageInstaller.java:426)
    at io.github.muntashirakon.AppManager.apk.installer.PackageInstallerCompat.openSession(PackageInstallerCompat.java:727)
    at io.github.muntashirakon.AppManager.apk.installer.PackageInstallerCompat.install(PackageInstallerCompat.java:574)
    at io.github.muntashirakon.AppManager.apk.installer.PackageInstallerService.onHandleIntent(PackageInstallerService.java:168)
    at io.github.muntashirakon.AppManager.types.ForegroundService$ServiceHandler.handleMessage(ForegroundService.java:53)
    at android.os.Handler.dispatchMessage(Handler.java:107)
    at android.os.Looper.loop(Looper.java:214)
    at android.os.HandlerThread.run(HandlerThread.java:67)

Device Info:
App version: 3.1.2
App version code: 425
Android build version: 1596015452
Android release version: 10
Android SDK version: 29
Android build ID: BV6300Pro_S1_200729
Device brand: Blackview
Device manufacturer: wheatek
Device name: BV6300Pro
Device model: BV6300Pro
Device product name: BV6300Pro_RU
Device hardware name: mt6771
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: ru-RU
In-App Language: auto
Mode: auto
Inferred Mode: no_root.

### Device info

- Device:
- OS Version:
- App Manager Version:
- Mode: Root/ADB/NonRoot

**Comment by MuntashirAkon** [comment] 2023-09-29 05:17
Duplicate of #1089

**Comment by MuntashirAkon** [comment] 2023-09-29 05:18
It appears I forgot to backport this particular patch to v3.1.x. This will be fixed in the next release.

**Closed** 2023-09-29 09:05 UTC
Labels: Bug, Duplicate
