### ISSUE TITLE
App list not available in > 4.0 bld 2705

### ISSUE THREAD

**Issue by 0xlne** [MuntashirAkon/AppManager#1409] opened 2024-07-14 09:14 UTC
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

On app startup, the list of apps is no longer visible on app versions 4.0 beta builds 2705+.
The last know working build is 2705.
The app starts fine, but the list is blank. Toggling any of the filters doesn't help.
Tried both dirty upgrades & clean installs with the same result.
Reverting to 2705 results in the proper display of apps again.

I am available on TG for troubleshooting if needed.

### To Reproduce

1: install App Manager (any builds up to & including v4.0 bld 2705
2: execute basic configuration (example: choose app mode - I use wireless adb)
3: await loading of apps

### Screenshots

![Screenshot_2024-07-14-11-06-08-916_io github muntashirakon AppManager debug](https://github.com/user-attachments/assets/a1101c81-e5e5-4990-bd9f-d6560d6b2bdb)

### Device info

- Device: Xiaomi Mix Fold 2
- OS Version: MIUI 14.0.14 / Android 13
- App Manager Version: OK = 4.0 bld 2705; Not OK = any subsequent build
- Mode: ADB

**Comment by CobalTitan** [comment] 2024-11-16 14:08
I have now the same problem with the new version 4.0.0-beta02 with android 14. Is there a solution to this problem?

**Comment by MuntashirAkon** [comment] 2024-11-16 18:50
Duplicate of #1432

**Closed by MuntashirAkon** 2024-11-16 18:50 UTC
Labels: Bug
