### ISSUE TITLE
Use shizuku instead of adb connection

### ISSUE THREAD

**Issue by Kimphunh** [MuntashirAkon/AppManager#987] opened 2023-02-03 10:23 UTC
Shizuku is an adb connection portal
It's convenient because
1,as long as shizuku is activated, other apps will also be able to send the adb command
2,The pairing method is extremely easy and there is no need to split the screen.When reconnecting, no need to enter the port 
3,A lot of apps are using shizuk, so it's good to add this method

**Comment by MuntashirAkon** [comment] 2023-02-03 21:21
Duplicate of #983

**Closed by MuntashirAkon** 2023-02-03 21:21 UTC
Labels: Duplicate, Status: Rejected

**Comment by Kimphunh** [comment] 2023-02-04 04:36
@MuntashirAkon That's not what I mean! 
1.Shizuku let the "APPS" connect to it using the command adb.
That mean just enable shizuku,then AM and other apps can connect to adb
AM still has a lot of errors and has to enter the port to connect again
Try using shizuku to understand what I'm talking about!!!
2.many apps are supporting shizuku,plsss add it

**Comment by MuntashirAkon** [comment] 2023-02-04 05:58
If you've read the docs (given in the linked issue), I've clearly explained why I couldn't add Shizuku support when I had the chance. Now, there are already three modes of operation that I need to worry about, I cannot add any more as things would be too complicated to handle for me. If you encounter any issues connecting ADB, you should report them instead. It would help others too since libAdb is used by many other apps whose users might be facing similar issues as well.

But it might be possible, in the recent versions of Shizuku (API 11+), to actually implement it entirely in Shizuku. If any developer is interested, they can help add another mode of operation that would allow connecting and operating through Shizuku (although you know, in the last two years, no developer has tried to make any contribution to the project which is quite sad to be honest). But I have no plan to develop such feature as it's quite complicated to maintain so many modes of operations. For example, the startup checks are already very complicated and incredibly difficult to understand the logic even if it's documented so well. I hope you've understood the problem.
