### ISSUE TITLE
Delete empty backup folders

### ISSUE THREAD

**Issue by FixItKit** [MuntashirAkon/AppManager#1438] opened 2024-08-23 21:21 UTC
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

App Manager should delete empty backup folders.

### Describe the solution you'd like

Delete an app's empty folder from the selected backup location after deleting an app's backup(s).

**Comment by MuntashirAkon** [comment] 2024-08-24 10:00
Duplicate of #1189

**Closed by MuntashirAkon** 2024-08-24 10:00 UTC
Labels: Duplicate, Feature, Feature: Backup
