### ISSUE TITLE
Ability to filter apps by installation source (e.g. "Google Play" vs. "Sideloaded")

### ISSUE THREAD

**Issue by Coldblackice** [MuntashirAkon/AppManager#1232] opened 2023-10-21 13:50 UTC
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

I often need to determine the install source of apps I'm testing, namely whether an app was installed via Google Play Store or sideloaded manually.

### Describe the solution you'd like

The new feature would merely be an additional filter added to the list on the master app list, to filter by app install source, in particular filtering for apps "sideloaded" outside of Google Play Store.

Of course, being able to further filter by separate sources such as:

- Google Play Store
- Samsung App Store
- F-Droid
- Neo Store
- Droid-ify
- IzzyOnDroid
- Sideloaded manually/via file manager

...would be extra awesome. But the primary need is seeing the list of apps installed via Google Play Store or outside of Play Store ("sideloaded").

### Describe alternatives you've considered

Currently, the only quick solution I know of is having to manually dive into an individual app's system info page, scrolling down to the bottom where the final line says where it was installed from.

**Comment by MuntashirAkon** [comment] 2023-10-21 17:14
Duplicate of #923

**Closed by MuntashirAkon** 2023-10-21 17:14 UTC
Labels: Feature
