### ISSUE TITLE
Impossible uninstallation

### ISSUE THREAD

**Issue by fabastrid** [MuntashirAkon/AppManager#282] opened 2021-02-14 19:06 UTC
Hello.
I am on Xiaomi Redmi Note 7  with Lineageos 17.1 Android 10, I'm trying to uninstall in every possible way, nothing to do. Any suggestions?

**Comment by Atrate** [comment] 2021-02-14 22:53
Uninstall what? What "every possible way"? Please be more specific.

**Comment by MuntashirAkon** [comment] 2021-02-15 01:40
Duplicate of #159

**Comment by MuntashirAkon** [comment] 2021-02-15 01:41
It's a ROM bug. Follow the issue above or contact your ROM developer.

**Closed by MuntashirAkon** 2021-02-15 01:40 UTC

**Comment by MuntashirAkon** [comment] 2021-06-03 08:50
**Update:** The issue has been addressed and fixed by Lineage OS. Here's the issue: https://gitlab.com/LineageOS/issues/android/-/issues/3030
