### ISSUE TITLE
App Inoperable

### ISSUE THREAD

**Issue by scruel** [MuntashirAkon/AppManager#1388] opened 2024-05-30 17:38 UTC
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Consider this issue caused by #1387, the large amount of log output may hang the app.

https://github.com/MuntashirAkon/AppManager/assets/16933298/d0a02255-ec41-44f8-b598-0538ab2cd46c

### Device info

- Device: Xiaomi cas
- OS Version: Android 13
- App Manager Version: 3.1.6
- Mode: NonRoot

**Comment by MuntashirAkon** [comment] 2024-06-02 05:51
Thanks for the video.

**Comment by MuntashirAkon** [comment] 2024-06-03 08:46
Related issue: #1317

**Comment by MuntashirAkon** [comment] 2024-07-06 09:33
Related issue: #1173

**Comment by MuntashirAkon** [comment] 2024-07-06 10:35
The issue does not seem to be reproducible after fixing #1173. Did you deny the notification permission earlier before making the video?

**Comment by scruel** [comment] 2024-07-11 09:12
App should hasn't been granted with any permissions

**Comment by MuntashirAkon** [comment] 2024-07-11 09:23
Duplicate of #1173

**Closed by MuntashirAkon** 2024-07-11 09:23 UTC
Labels: Bug, Duplicate, Severity: 2, Priority: 2
