### ISSUE TITLE
App initialising for ever on Android 7.0

### ISSUE THREAD

**Issue by Sami32** [MuntashirAkon/AppManager#474] opened 2021-06-10 11:37 UTC
Hello,

It seem that a regression bug affect your App (v2.6.1 from F-Droid), with Android 7.0 at least, that make the start initializing for ever.

**Comment by MuntashirAkon** [comment] 2021-06-10 12:18
Possible duplicate of #466

**Comment by MuntashirAkon** [comment] 2021-06-10 12:18
Closed because no template was used.

**Closed by MuntashirAkon** 2021-06-10 12:18 UTC

**Comment by Sami32** [comment] 2021-06-10 12:57
That could be because i'm using a Xiomi Redmi Note 4. Also i only get an endless initializing message at start.
I can confirm that v2.6.0 work fine.

**Comment by MuntashirAkon** [comment] 2021-06-10 14:22
> That could be because i'm using a Xiaomi Redmi Note 4.

I'm currently downloading Android 7 ISO file to test it myself. (I'm currently living in a village, so the Internet speed is way too slow here.)

**Comment by MuntashirAkon** [comment] 2021-06-10 17:12
Duplicate of #466

**Comment by MuntashirAkon** [comment] 2021-06-10 17:13
The issue has been fixed as mentioned in the linked issue.
