### ISSUE TITLE
Crashes whenever I tap an apps name 

### ISSUE THREAD

**Issue by xxlm47** [MuntashirAkon/AppManager#1115] opened 2023-07-05 20:38 UTC
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Each time I select an app from the main screen it continuously crashes.

### Device info

- Device:
- OS Version:
- App Manager Version:
- Mode: Root/ADB/NonRoot
Pixel 6a running android 14

**Comment by MuntashirAkon** [comment] 2023-07-07 18:56
No crash logs are provided.

**Comment by TheGamer1002** [comment] 2023-08-13 13:05
Having the same issue.
```
java.lang.RuntimeException: java.lang.NoSuchMethodError: No interface method getInstallSourceInfo(Ljava/lang/String;)Landroid/content/pm/InstallSourceInfo; in class Landroid/content/pm/IPackageManager; or its super classes (declaration of 'android.content.pm.IPackageManager' appears in /system/framework/framework.jar)
    at io.github.muntashirakon.AppManager.details.info.AppInfoViewModel.lambda$loadAppInfo$1(AppInfoViewModel.java:330)
    at io.github.muntashirakon.AppManager.details.info.AppInfoViewModel$$ExternalSyntheticLambda1.run(Unknown Source:2)
    at android.os.Handler.handleCallback(Handler.java:958)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:205)
    at android.os.Looper.loop(Looper.java:294)
    at android.app.ActivityThread.main(ActivityThread.java:8177)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
 Caused by: java.lang.NoSuchMethodError: No interface method getInstallSourceInfo(Ljava/lang/String;)Landroid/content/pm/InstallSourceInfo; in class Landroid/content/pm/IPackageManager; or its super classes (declaration of 'android.content.pm.IPackageManager' appears in /system/framework/framework.jar)
   at io.github.muntashirakon.AppManager.compat.PackageManagerCompat.getInstallSourceInfo(PackageManagerCompat.java:223)
   at io.github.muntashirakon.AppManager.compat.PackageManagerCompat.getInstallerPackageName(PackageManagerCompat.java:210)
   at io.github.muntashirakon.AppManager.details.info.AppInfoViewModel.loadAppInfo(AppInfoViewModel.java:301)
   at io.github.muntashirakon.AppManager.details.info.AppInfoFragment.loadPackageInfo(AppInfoFragment.java:1610)
   at io.github.muntashirakon.AppManager.details.info.AppInfoFragment.$r8$lambda$oxlKbqiAsxIkEG69gntC-jrgnXk(Unknown Source:0)
   at io.github.muntashirakon.AppManager.details.info.AppInfoFragment$$ExternalSyntheticLambda63.run(Unknown Source:2)
   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
   at java.util.concurrent.FutureTask.run(FutureTask.java:264)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
   at java.lang.Thread.run(Thread.java:1012)

Device Info:
App version: 3.1.1
App version code: 424
Android build version: 10531303
Android release version: 14
Android SDK version: 34
Android build ID: UPB4.230623.007
Device brand: google
Device manufacturer: Google
Device name: raven
Device model: Pixel 6 Pro
Device product name: raven_beta
Device hardware name: raven
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-US
In-App Language: auto
Mode: adb_wifi
Inferred Mode: ADB
```
This happens no matter what app I choose. @MuntashirAkon

**Comment by MuntashirAkon** [comment] 2023-08-16 11:38
Duplicate of #1135

**Closed by MuntashirAkon** 2023-08-16 11:38 UTC
Labels: Bug, Status: Invalid
