### ISSUE TITLE
Crash while going back to AM from a launched app

### ISSUE THREAD

**Issue by kgursu** [MuntashirAkon/AppManager#855] opened 2022-09-01 15:08 UTC
- [x] I know what my device, OS and App Manager versions are
- [x] I know how to take logs
- [ ] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**
I'm not sure, if this issue is device specific or not. I need to make sure, what the source of the problem is.

**To Reproduce**
Steps to reproduce the behaviour:
1. Launch an app
2. Done with it
3. Switch to AM Debug
4. Crash

**Expected behavior**
I expect the app resumes where I left off.

**Screenshots**
None

**Crash logs**
java.lang.RuntimeException: Parcel android.os.Parcel@33ec251: Unmarshalling unknown type code 6881398 at offset 644
    at android.os.Parcel.readValue(Parcel.java:3253)
    at android.os.Parcel.readSparseArrayInternal(Parcel.java:3650)
    at android.os.Parcel.readSparseArray(Parcel.java:2792)
    at android.os.Parcel.readValue(Parcel.java:3231)
    at android.os.Parcel.readArrayMapInternal(Parcel.java:3567)
    at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
    at android.os.BaseBundle.unparcel(BaseBundle.java:236)
    at android.os.Bundle.getSparseParcelableArray(Bundle.java:1079)
    at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2181)
    at android.app.Activity.onRestoreInstanceState(Activity.java:1679)
    at android.app.Activity.performRestoreInstanceState(Activity.java:1632)
    at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1356)
    at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3473)
    at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
    at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:223)
    at android.app.ActivityThread.main(ActivityThread.java:7664)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

Device Info:
App version: 3.1.0-alpha01-DEBUG
App version code: 411
Android build version: eng.joel16.20220120.132941
Android release version: 11
Android SDK version: 30
Android build ID: lineage_satsuki-userdebug 11 RQ3A.211001.001 eng.joel16.20220120.132941 test-keys
Device brand: Sony
Device manufacturer: Sony
Device name: satsuki
Device model: E6853
Device product name: E6853
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: tr-TR
In-App Language: auto
Mode: auto

**Device info**
 - Device: Sony Xperia Z5 Premium (E6853)
 - OS Version: Android 11
 - App Manager Version: 3.1.0-alpha01-DEBUG
 - Mode: root

**Additional context**
Nothing I could think of.

**Comment by MuntashirAkon** [comment] 2022-09-02 04:32
Duplicate of #656

**Closed** 2022-09-02 04:32 UTC
Labels: Bug
