### ISSUE TITLE
Ability to add a note in "App Info"

### ISSUE THREAD

**Issue by EvilSoldier666** [MuntashirAkon/AppManager#1338] opened 2024-04-08 12:44 UTC
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

Hello, this app is really amazing and I use it for years but one thing I think would be really useful is the ability to add a note to the "App Info" of certain apps.

It would be really helpful to write some information about the apps that have different releasers or have different versions so we know where to go when we need to update.
This way it would also be possible to add the link to go straight for it.
I will leave an image so it's easier to understand what I mean.

Thank you very much, I hope it's something that can be done! I already searched in the app an docs and couldn't find anything that can help me.

![PSX_20240408_134108](https://github.com/MuntashirAkon/AppManager/assets/20204018/ef1f64da-0138-46ba-9392-d8993729be6e)

### Describe the solution you'd like

Already described and added an image to the description.

**Comment by MuntashirAkon** [comment] 2024-04-08 13:16
Duplicate of #1269

**Closed by MuntashirAkon** 2024-04-08 13:16 UTC
Labels: Duplicate, Feature
