### ISSUE TITLE
Cannot uninstall the application

### ISSUE THREAD

**Issue by IHateTheProgrammingClass** [MuntashirAkon/AppManager#651] opened 2021-12-29 17:04 UTC
- [x] I know what my device, OS and App Manager versions are
- [ ] I know how to take logs
- [x] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**
When I try to uninstall the app it stays installed.

**To Reproduce**
Steps to reproduce the behaviour:
1. Exit app
2. Hold application icon
3. Click uninstall

**Expected behavior**
The app uninstalls.

**Screenshots**

**Crash logs**

**Device info**
 - Device: Samsung Galaxy A52s tG
 - OS Version: Android 11
 - App Manager Version: 2.6.5.1 (397)
 - Mode: no-root

**Additional context**
I cannot remove the application.

**Comment by MuntashirAkon** [comment] 2021-12-29 18:33
Duplicate of #159

**Comment by MuntashirAkon** [comment] 2021-12-29 18:33
See also https://github.com/MuntashirAkon/AppManager/issues/159#issuecomment-744013026

**Closed by MuntashirAkon** 2021-12-29 18:33 UTC
Labels: duplicate, 3rd-party-issue
