### ISSUE TITLE
Enable disabled services and activities

### ISSUE THREAD

**Issue by DaviDoodlez951** [MuntashirAkon/AppManager#1163] opened 2023-09-01 13:08 UTC
### Describe your problem(s)

Hey, I disabled some the google play services and when I rebooted my device it triggered bootloop. when I enter the password, as soon it is unlocked it restarts. I wanted to know if there is any way I can remove those rules and restore it back again not in app because I can't access the app but by twrp recovery. Is there any location where you save those rules. I was thinking by deleting those files I would restore it back again.

**Comment by vordx** [comment] 2023-09-01 13:44
I'm not sure exactly what could fix this but if I were u I would try :-

-Remove magisk so it doesn't give app manager the ability to disable the apps.

-reinstall the Google play services?

-enable them with ADB if you can remember?

**Comment by MuntashirAkon** [comment] 2023-09-01 15:15
This has been asked before. Read https://github.com/MuntashirAkon/AppManager/issues/619#issuecomment-961708350 and the linked comment to solve your issue.

**Comment by MuntashirAkon** [comment] 2023-09-01 15:15
Duplicate of #363

**Closed by MuntashirAkon** 2023-09-01 15:15 UTC
Labels: Duplicate, Help Wanted
