### ISSUE TITLE
Frozen apps not showing properly via filter and on the list, too.

### ISSUE THREAD

**Issue by v4lkyr** [MuntashirAkon/AppManager#1241] opened 2023-11-03 02:27 UTC
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

I have frozen multiple apps via multiple selection. When I click on those apps and see their details, I see that each of them are properly frozen too, with the label "Disabled".  However, when I use the filter option "Frozen first" under Sort section, it doesn't work, frozen apps do not come on top of the app list.

Also, there isn't any dark brown tab color on the left side of each app. (as to indicate they are frozen)

### To Reproduce

1- Freeze a few apps via multiple selection (can be done via one by one too)
2- Pull down and refresh the app list
3- Tap on the button with tick and cross next to three dots menu in top right of screen.
4- Tap on "Frozen first" under sort section.
5- Observe that those frozen apps do not appear on top of the list. 

### Expected behavior

The expect behaviour would be, the frozen apps appears on top of the list in alphabetical order regarding to their app label (not package label) ascending order. Then, would come rest of the apps (both user and system apps with again same order.

And the dark brown tab color indicating that app is frozen should appear.

### Device info

- Device: realme GT Neo 3 80W - RMX3560
- OS Version: 13.0.0
- App Manager Version: 3.1.3
- Mode: Root

**Comment by v4lkyr** [comment] 2023-11-03 02:33
Also, when I tap on "Frozen apps" under Filter section, only one app shows. Rest of the frozen apps do not show.

**Comment by tew42** [comment] 2023-11-04 20:13
I just switched over from a magisk debloat module to using AppManager to eliminate system/vendor apps, and I'm facing the same issue. Sorting and filtering by "frozen" only shows ~10 apps that I had originally "disabled" before switching the methodology to "hide" (and unfreeze/refreezing them); new apps that I'm adding to my freeze list don't sort or filter correctly.


Galaxy A40 (SM-405FN) running FeatherProject v9.1 S22 OneUI port
OS Version: 13
App Manager Version: 3.1.3
Mode: Root (KSU 0.7)

**Comment by MuntashirAkon** [comment] 2023-11-05 06:22
Duplicate of #1160

**Closed by MuntashirAkon** 2023-11-05 06:22 UTC
Labels: Bug, Duplicate
