### ISSUE TITLE
AM crashes when left idle in the background and re opened again

### ISSUE THREAD

**Issue by Ashcine** [MuntashirAkon/AppManager#792] opened 2022-06-29 18:07 UTC
- [x] I know what my device, OS and App Manager versions are
- [x] I know how to take logs
- [ ] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**
AM crashes whenever I re open it after being left in the background for too long or maybe if there's no enough ram. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Open it for the first time. 
2. Go home and leave it running in the backgrounmfd or do something that overloads the ram.s (app must be on background not killed)
3. Re open the app again. 
4. Get notified that AM had crashed. 

**Expected behavior**
Will work again if you force stop the app. 

**Crash logs, Device info and Additional context**
 java.lang.RuntimeException: Parcel android.os.Parcel@f2e91fd: Unmarshalling unknown type code 6881399 at offset 1612
    at android.os.Parcel.readValue(Parcel.java:3305)
    at android.os.Parcel.readSparseArrayInternal(Parcel.java:3706)
    at android.os.Parcel.readSparseArray(Parcel.java:2844)
    at android.os.Parcel.readValue(Parcel.java:3283)
    at android.os.Parcel.readArrayMapInternal(Parcel.java:3623)
    at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
    at android.os.BaseBundle.unparcel(BaseBundle.java:236)
    at android.os.Bundle.getSparseParcelableArray(Bundle.java:1080)
    at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2199)
    at android.app.Activity.onRestoreInstanceState(Activity.java:1722)
    at android.app.Activity.performRestoreInstanceState(Activity.java:1675)
    at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1396)
    at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3748)
    at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
    at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7866)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

Device Info:
App version: 3.0.0-rc02-DEBUG
App version code: 404
Android build version: 1651659096
Android release version: 12
Android SDK version: 32
Android build ID: aosp_mi439-userdebug 12 SP2A.220405.004 1651659096 release-keys
Device brand: Xiaomi
Device manufacturer: Xiaomi
Device name: pine
Device model: Redmi 7A
Device product name: aosp_mi439
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-US
In-App Language: auto
Mode: auto

**Comment by MuntashirAkon** [comment] 2022-06-30 10:36
Duplicate of #656

**Closed by MuntashirAkon** 2022-06-30 10:36 UTC
Labels: Bug, Duplicate
