### ISSUE TITLE
can't instal apk

### ISSUE THREAD

**Issue by NSTAdventure** [MuntashirAkon/AppManager#367] opened 2021-04-11 04:28 UTC
**Describe the bug**
crash while trying to instal apk from mt manager

**To Reproduce**
Steps to reproduce the behaviour:
1. open mt manager browser apk file
2. click the apk choose instal 
3. choose Instal (Am Icon)

**Expected behavior**
It Should Working

**Screenshots**
...

**Crash logs**
on reply

**Device info**
 - Device: Realme 5i
 - OS Version: Android Q (10)
 - App Manager Version: v.2.5.20
 - Mode: adb

**Additional context**
bruh

**Comment by NSTAdventure** [comment] 2021-04-11 04:28
crash log:
android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@5a3f8c1 is not valid; is your activity running?
    at android.view.ViewRootImpl.setView(ViewRootImpl.java:1058)
    at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:411)
    at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:96)
    at android.app.Dialog.show(Dialog.java:349)
    at androidx.appcompat.app.AlertDialog$Builder.show(AlertDialog.java:1009)
    at io.github.muntashirakon.AppManager.apk.installer.PackageInstallerActivity.lambda$null$5$PackageInstallerActivity(PackageInstallerActivity.java:162)
    at io.github.muntashirakon.AppManager.apk.installer.-$$Lambda$PackageInstallerActivity$UFMh3s6tCJc1v0UQeX_qFqNlU5k.run(Unknown Source:4)
    at android.os.Handler.handleCallback(Handler.java:899)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loop(Looper.java:238)
    at android.app.ActivityThread.main(ActivityThread.java:7853)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:984)

Device Info:
App version: 2.5.20
App version code: 375
Android build version: 1608537052
Android release version: 10
Android SDK version: 29
Android build ID: RMX2030EX_11_C.67
Device brand: realme
Device manufacturer: realme
Device name: RMX2030
Device model: RMX2030
Device product name: RMX2030
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: id-ID
In-App Language: auto

**Comment by MuntashirAkon** [comment] 2021-05-09 15:09
This issue should be fixed in v2.6.0.

**Closed by MuntashirAkon** 2021-05-09 15:09 UTC
Labels: P3, S3, bug

**Comment by shuvashish76** [comment] 2023-09-23 09:16
Duplicate of #701
