### ISSUE TITLE
Crashes on Selecting Intent to Get package info or any other  from Mixplorer or any File explorer of Apk file.

### ISSUE THREAD

**Issue by Genxster1998** [MuntashirAkon/AppManager#343] opened 2021-03-28 17:10 UTC
```
java.lang.NullPointerException: Attempt to invoke interface method 'android.os.ParcelFileDescriptor io.github.muntashirakon.AppManager.IRemoteFile.getPipedOutputStream()' on a null object reference
    at io.github.muntashirakon.io.ProxyOutputStream.<init>(ProxyOutputStream.java:43)
    at io.github.muntashirakon.AppManager.utils.IOUtils.saveZipFile(IOUtils.java:163)
    at io.github.muntashirakon.AppManager.utils.IOUtils.saveZipFile(IOUtils.java:154)
    at io.github.muntashirakon.AppManager.apk.ApkFile$Entry.getRealCachedFile(ApkFile.java:703)
    at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.setPackage(AppDetailsViewModel.java:128)
    at io.github.muntashirakon.AppManager.details.AppDetailsActivity.lambda$onAuthenticated$5$AppDetailsActivity(AppDetailsActivity.java:104)
    at io.github.muntashirakon.AppManager.details.-$$Lambda$AppDetailsActivity$N44Vyz4IkC88KWOwbq04gs3biVs.run(Unknown Source:14)
    at java.lang.Thread.run(Thread.java:919)

Device Info:
App version: 2.5.24-PRE
App version code: 383
Android build version: eng.vishwa.20210122.113105
Android release version: 10
Android SDK version: 29
Android build ID: rr_violet-userdebug 10 QQ3A.200905.001 eng.vishwa.20210122.113105 release-keys
Device brand: Xiaomi
Device manufacturer: Xiaomi
Device name: violet
Device model: Redmi Note 7 Pro
Device product name: violet
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-IN
In-App Language: auto
Mode: root
```

**Comment by MuntashirAkon** [comment] 2021-03-29 11:21
Duplicate of #341

**Closed by MuntashirAkon** 2021-03-29 11:21 UTC

**Comment by Genxster1998** [comment] 2021-03-30 05:43
@MuntashirAkon it's not duplicate (or could be if you think) but this is happening on selecting App Manager to open apk file from Mixplorer while other one was in-app App manager selecting system config from menu .

**Comment by MuntashirAkon** [comment] 2021-03-30 05:44
It _is_ a duplicate (if you look at the logs).
