### ISSUE TITLE
Export/Import app list

### ISSUE THREAD

**Issue by Megver83** [MuntashirAkon/AppManager#556] opened 2021-08-14 02:01 UTC
- [x] I am using the latest version of App Manager
- [x] I have searched the issues and haven't found anything relevant
- [x] I have read the docs

**Is your feature request related to a problem? Please describe.**
When migrating ROMs/phones, a typical issue is to loose all apps and data. AM allows restoring whole apps with its data, but uses much more space than creating an app list to import them from, e.g. F-Droid

**Describe the solution you'd like**
Add an option to export an app list in plain text and import them by installing from F-Droid or Play Store. The advantage of this, over backing up apks, is that it saves much more storage, doesn't rely on specific versions of apps (this may be a disadvantage in some cases, but the idea is to have this feature as an alternative to traditional back ups to use its advantages, of course) but on the latest one found in the chosen app store.

**Describe alternatives you've considered**
As of now, there's [My App List](https://f-droid.org/packages/com.projectsexception.myapplist.open/) which does exactly what I say, but it's too old and obsolete.

**Comment by MuntashirAkon** [comment] 2021-08-14 02:03
Duplicate of #122

**Comment by MuntashirAkon** [comment] 2021-08-14 02:06
> Play Store

App Manager neither supports nor promotes Google Play Store (or any other proprietary apps/services for that matter). But we do support Aurora Store, an alternative to Google Play Store.

**Closed by MuntashirAkon** 2021-08-14 02:06 UTC
Labels: duplicate, feature, P3
