### ISSUE TITLE
Crashing again

### ISSUE THREAD

**Issue by Raif1** [MuntashirAkon/AppManager#705] opened 2022-03-14 13:48 UTC
- [x] I know what my device, OS and App Manager versions are
- [x] I know how to take logs
- [x] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**
App crashes and slows down

**To Reproduce**
Steps to reproduce the behaviour:
1. Select an app
2. Click on click scanner
3. See error

**Expected behavior**
I should be able to scan my app 

**Screenshots**

**Crash logs**
java.lang.AssertionError: Binder ProxyMap has too many entries: 21148 (total), 20050 (uncleared), 75 (uncleared after GC). BinderProxy leak?
    at android.os.BinderProxy$ProxyMap.set(BinderProxy.java:230)
    at android.os.BinderProxy.getInstance(BinderProxy.java:432)
    at android.os.Parcel.nativeReadStrongBinder(Native Method)
    at android.os.Parcel.readStrongBinder(Parcel.java:2483)
    at io.github.muntashirakon.AppManager.IAMService$Stub$Proxy.getFile(IAMService.java:295)
    at io.github.muntashirakon.io.ProxyFile.getRemoteFile(ProxyFile.java:324)
    at io.github.muntashirakon.io.ProxyFile.<init>(ProxyFile.java:35)
    at io.github.muntashirakon.io.ProxyFile.getParentFile(ProxyFile.java:101)
    at io.github.muntashirakon.io.ProxyFile.getParentFile(ProxyFile.java:21)
    at androidx.documentfile.provider.ProxyDocumentFile.getParentDocumentFile(ProxyDocumentFile.java:206)
    at androidx.documentfile.provider.ProxyDocumentFile.<init>(ProxyDocumentFile.java:27)
    at androidx.documentfile.provider.ProxyDocumentFile.getParentDocumentFile(ProxyDocumentFile.java:208)
    at androidx.documentfile.provider.ProxyDocumentFile.<init>(ProxyDocumentFile.java:27)
    at androidx.documentfile.provider.ProxyDocumentFile.getParentDocumentFile(ProxyDocumentFile.java:208)
    at androidx.documentfile.provider.ProxyDocumentFile.<init>(ProxyDocumentFile.java:27)
    at io.github.muntashirakon.io.Path.<init>(Path.java:107)
    at io.github.muntashirakon.AppManager.utils.AppPref.getAppManagerDirectory(AppPref.java:249)
    at io.github.muntashirakon.AppManager.backup.BackupFiles.getBackupDirectory(BackupFiles.java:35)
    at io.github.muntashirakon.AppManager.backup.BackupFiles.getPackagePath(BackupFiles.java:47)
    at io.github.muntashirakon.AppManager.backup.MetadataManager.getBackupFiles(MetadataManager.java:221)
    at io.github.muntashirakon.AppManager.backup.MetadataManager.getMetadata(MetadataManager.java:205)
    at io.github.muntashirakon.AppManager.backup.BackupUtils.storeAllAndGetLatestBackupMetadata(BackupUtils.java:74)
    at io.github.muntashirakon.AppManager.main.MainViewModel.getNewApplicationItem(MainViewModel.java:654)
    at io.github.muntashirakon.AppManager.main.MainViewModel.updateInfoForPackages(MainViewModel.java:489)
    at io.github.muntashirakon.AppManager.main.MainViewModel.access$100(MainViewModel.java:62)
    at io.github.muntashirakon.AppManager.main.MainViewModel$PackageIntentReceiver.onPackageChanged(MainViewModel.java:722)
    at io.github.muntashirakon.AppManager.types.PackageChangeReceiver$ReceiverHandler.handleMessage(PackageChangeReceiver.java:103)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:223)
    at android.os.HandlerThread.run(HandlerThread.java:67)

Device Info:
App version: 3.0.0-alpha01
App version code: 400
Android build version: eng.crossg.20220120.182016
Android release version: 11
Android SDK version: 30
Android build ID: lineage_treble_a64_bvS-userdebug 11 RQ3A.211001.001 eng.crossg.20220120.182016 test-keys
Device brand: Phh
Device manufacturer: unknown
Device name: phhgsi_a64_ab
Device model: Phh-Treble vanilla
Device product name: lineage_treble_a64_bvS
Device hardware name: exynos7904
ABIs: [armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): []
System language: en-GB
In-App Language: auto
Mode: root

**Device info**
 - Device: [e.g. One Plus 8 Pro]
 - OS Version: [e.g. Android 10]
 - App Manager Version: [e.g. v2.5.13]
 - Mode: root/adb/no-root

**Additional context**

**Comment by MuntashirAkon** [comment] 2022-03-14 14:53
Duplicate of #470

**Closed by MuntashirAkon** 2022-03-14 14:53 UTC
Labels: bug, S3, P3
