### ISSUE TITLE
Problems with App Manager and doubt autostars

### ISSUE THREAD

**Issue by gallegonovato** [MuntashirAkon/AppManager#862] opened 2022-09-09 18:50 UTC
Good afternoon:

I apologize if I open a blank topic. But I was confused with the other options. 

It turns out that in some applications, inside app manager and in it under Application operations. It does not allow to disable or access the last options. Since it interferes the buttons ( back, home, and background). I upload screenshot https://ibb.co/jMydbg3

I do not know if I could adjust so that it does not come out like this. Since without buttons I do not adapt well.

Then if I may I would like to ask about android-autostarts. Is there any way to make a backup without losing the things you have locked. Since a friend wants to change and does not know how (he has the version before his). I made the change with photos of the app with everything extended inside android-autostarts. But I don't know if there is any other option. 

Best regards and thanks for your help and time.

**Comment by MuntashirAkon** [comment] 2022-09-09 19:17
> But I was confused with the other options.

This appears to be a bug. Create a new issue with appropriate temple as you have missing a lot of information (e.g. the issue is likely device specific).

> Then if I may I would like to ask about android-autostarts. Is there any way to make a backup without losing the things you have locked. Since a friend wants to change and does not know how (he has the version before his). I made the change with photos of the app with everything extended inside android-autostarts. But I don't know if there is any other option.

Autostarts is basically a legacy software that I have modified to support the latest operating systems. It offers exactly the same features as the original, and since the features will be merged with App Manager, no feature requests are accepted. However, anything that you've blocked in Autostarts would be displayed as light red (in light mode) in App Manager in the components tabs (because the components are disabled using Package Manager). One way to export them would be to re-block them in App Manager and export the rules in the App Info tab which your friend can import.

**Comment by gallegonovato** [comment] 2022-09-11 16:19
Good evening @MuntashirAkon

I tried to follow the bugs guide, have I filled it in correctly.


- [ x ] I know my device, OS and App Manager versions.
- [ ] I know how to take logs
- [ x ] I know how to reproduce the problem, which may not be specific to my device.

**Describe the bug**

It turns out that in some apps, inside the app manager and in app operations. It does not allow to disable or access the last options. Since it interferes with the buttons (back, home and background apps).

**Replay**
Steps to reproduce the behavior:
1. Go to For example Updater.
2. Click on Application Operations
3. Scroll down to and disallow uncheck or check the last option.
4. View error

**Expected behavior

Be able to uncheck the last version

**Screenshots**

https://ibb.co/YkfZNvr
https://ibb.co/3yxZM93

**Bug logs**
If applicable, add crash logs to help us understand the problem.

**Device information
 - Device: Huawei Nexus 6p , Lg Nexus 5
 - Operating System Version: Lineageos 18.1 and 17.1
 - App Manager version: App Manager v3.0.1 Stable
Latest
 - Mode: root

**Additional context
Add here any other context about the problem.

**Closed** 2023-01-18 19:11 UTC
Labels: Help Wanted
