### ISSUE TITLE
Crash when going back from log screen

### ISSUE THREAD

**Issue by assembleDebug** [MuntashirAkon/AppManager#786] opened 2022-06-23 11:22 UTC
- [x] I know what my device, OS and App Manager versions are
- [x] I know how to take logs
- [x] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**
There is an option for "view log" in "Running Apps" section to view each running app's log. AM Crashes when we go back from the log viewer screen. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Long press on any running process/app
2. Select "view log"
3. You will see the log screen with process number filter.
4. Just press/swipe back, application will crash.

**Expected behavior**
Shouldn't crash and go back to running app's screen.

**Crash logs**
`java.lang.RuntimeException: Parcel android.os.Parcel@38cafdf: Unmarshalling unknown type code 6881399 at offset 1696
    at android.os.Parcel.readValue(Parcel.java:3306)
    at android.os.Parcel.readSparseArrayInternal(Parcel.java:3707)
    at android.os.Parcel.readSparseArray(Parcel.java:2845)
    at android.os.Parcel.readValue(Parcel.java:3284)
    at android.os.Parcel.readArrayMapInternal(Parcel.java:3624)
    at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
    at android.os.BaseBundle.unparcel(BaseBundle.java:236)
    at android.os.Bundle.getSparseParcelableArray(Bundle.java:1080)
    at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2199)
    at android.app.Activity.onRestoreInstanceState(Activity.java:1725)
    at android.app.Activity.performRestoreInstanceState(Activity.java:1678)
    at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1394)
    at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3748)
    at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
    at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7871)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

Device Info:
App version: 3.0.0-rc03-DEBUG
App version code: 405
Android build version: 1655886293
Android release version: 12
Android SDK version: 32
Android build ID: SQ3A.220605.009.B1
Device brand: Redmi
Device manufacturer: Xiaomi
Device name: sweetin
Device model: M2101K6P
Device product name: sweetin
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-US
In-App Language: auto
Mode: auto`

**Device info**
 - Device: Note 10 Pro
- AM version - Debug #1862
 - OS Version: Android 12.1
 - Mode: root

**Comment by MuntashirAkon** [comment] 2022-06-23 11:23
Duplicate of #656

**Closed by MuntashirAkon** 2022-06-23 11:23 UTC
Labels: Bug
