### ISSUE TITLE
automated blocking for new apps

### ISSUE THREAD

**Issue by solnyshok** [MuntashirAkon/AppManager#200] opened 2020-12-23 11:22 UTC
my use case: kid's tablet, rooted. kid installs games everyday, all of them full of trackers and ads. I want AppManager to apply automatic tracker blocking to every app within 1 minute from installation, unless I enter admin password.

**Comment by MuntashirAkon** [comment] 2020-12-23 11:37
Duplicate of #40

**Closed by MuntashirAkon** 2020-12-23 11:37 UTC
Labels: P3, duplicate, feature
