### ISSUE TITLE
Crashing when opening permissions settings

### ISSUE THREAD

**Issue by Pahomk** [MuntashirAkon/AppManager#998] opened 2023-02-15 01:08 UTC
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [x] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

AppManager crashing when i open permissions app settings

### To Reproduce

1. Open AppManager
2. Select any user app
3. Open permissions settings on nav bar
4. Crashed

### Expected behavior

Permissions settings opened 

### Logs

java.lang.NoClassDefFoundError: io.github.muntashirakon.AppManager.appops.AppOpsManager
at io.github.muntashirakon.AppManager.details.AppDetailsFragment.permAppOp(AppDetailsFragment.java:526)
at io.github.muntashirakon.AppManager.details.AppDetailsFragment.access$1000(AppDetailsFragment.java:99)
at io.github.muntashirakon.AppManager.details.AppDetailsFragment$AppDetailsRecyclerAdapter.getPermissionsView(AppDetailsFragment.java:1047)
at io.github.muntashirakon.AppManager.details.AppDetailsFragment$AppDetailsRecyclerAdapter.onBindViewHolder(AppDetailsFragment.java:696)
at io.github.muntashirakon.AppManager.details.AppDetailsFragment$AppDetailsRecyclerAdapter.onBindViewHolder(AppDetailsFragment.java:530)
at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7254)
at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7337)
at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6194)
at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6460)
at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6300)
at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6296)
at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2330)
at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1631)
at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:668)
at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4309)
at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4012)
at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4578)
at android.view.View.layout(View.java:23718)
at android.view.ViewGroup.layout(ViewGroup.java:6435)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at android.view.View.layout(View.java:23718)
at android.view.ViewGroup.layout(ViewGroup.java:6435)
at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
at android.view.View.layout(View.java:23718)
at android.view.ViewGroup.layout(ViewGroup.java:6435)
at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:688)
at android.view.View.layout(View.java:23718)
at android.view.ViewGroup.layout(ViewGroup.java:6435)
at androidx.viewpager.widget.ViewPager.onLayout(ViewPager.java:1775)
at android.view.View.layout(View.java:23718)
at android.view.ViewGroup.layout(ViewGroup.java:6435)
at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:149)
at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:2253)
at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)
at android.view.View.layout(View.java:23718)
at android.view.ViewGroup.layout(ViewGroup.java:6435)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at android.view.View.layout(View.java:23718)
at android.view.ViewGroup.layout(ViewGroup.java:6435)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
at android.view.View.layout(View.java:23718)
at android.view.ViewGroup.layout(ViewGroup.java:6435)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at android.view.View.layout(View.java:23718)
at android.view.ViewGroup.layout(ViewGroup.java:6435)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
at android.view.View.layout(View.java:23718)
at android.view.ViewGroup.layout(ViewGroup.java:6435)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at com.android.internal.policy.DecorView.onLayout(DecorView.java:818)
at android.view.View.layout(View.java:23718)
at android.view.ViewGroup.layout(ViewGroup.java:6435)
at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4028)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3405)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2353)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9131)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1319)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1327)
at android.view.Choreographer.doCallbacks(Choreographer.java:985)
at android.view.Choreographer.doFrame(Choreographer.java:916)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1302)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:241)
at android.os.Looper.loop(Looper.java:358)
at android.app.ActivityThread.main(ActivityThread.java:8120)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
Caused by: java.lang.ExceptionInInitializerError
at io.github.muntashirakon.AppManager.appops.AppOpsManager.permissionToOpCode(AppOpsManager.java:1865)
at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.loadAppOps(AppDetailsViewModel.java:1355)
at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.lambda$load$22$io-github-muntashirakon-AppManager-details-AppDetailsViewModel(AppDetailsViewModel.java:914)
at io.github.muntashirakon.AppManager.details.AppDetailsViewModel$$ExternalSyntheticLambda35.run(Unknown Source:4)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
at java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.IllegalStateException: sOpToSwitch length 121 should be 126
at io.github.muntashirakon.AppManager.appops.AppOpsManager.<clinit>(AppOpsManager.java:1748)
at io.github.muntashirakon.AppManager.appops.AppOpsManager.permissionToOpCode(AppOpsManager.java:1865)
at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.loadAppOps(AppDetailsViewModel.java:1355)
at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.lambda$load$22$io-github-muntashirakon-AppManager-details-AppDetailsViewModel(AppDetailsViewModel.java:914)
at io.github.muntashirakon.AppManager.details.AppDetailsViewModel$$ExternalSyntheticLambda35.run(Unknown Source:4)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
at java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
at java.lang.Thread.run(Thread.java:1012)

### Device info

- Device: Asus RogPhone 6
- OS Version: Android 13
- App Manager Version: 3.0.3 - 3.1.0 beta01 
- Mode: Root

**Comment by MuntashirAkon** [comment] 2023-02-15 01:31
Duplicate of #994

**Closed by MuntashirAkon** 2023-02-15 01:31 UTC
Labels: Bug, Duplicate
