### ISSUE TITLE
App Manager is incapable of launching all activities that can be launched

### ISSUE THREAD

**Issue by k3n01** [MuntashirAkon/AppManager#744] opened 2022-05-05 17:42 UTC
- [x] I know what my device, OS and App Manager versions are
- [x] I know how to take logs
- [x] I know how to reproduce the issue which may not be specific to my device

Sorry if it's been complained about before, I wasn't able to find it.
Some activities are having a red fade (not sure why) and they are unable to be activated while other similar apps (like [Activity Launcher](https://play.google.com/store/apps/details?id=de.szalkowski.activitylauncher)) are perfectly capable of that. Additionally, App Manager doesn't fully detect their id.

**To Reproduce**
1. Open App Manager
2. Find com.android.systemui
3. Select Activities tab
4. Try to find .tuner.NavBarTuner activity
5. Where it should be, you see a .tuner.TunerActivity

**Expected behavior**
The activity is launchable and has a proper id.

**Additional information**
Android version: 10 (LineageOS 17.1)
App Manager version: 2.6.5.1 (397)

**Comment by MuntashirAkon** [comment] 2022-05-05 17:49
Issues must be reported from the latest release.

**Comment by k3n01** [comment] 2022-05-05 17:49
> Issues must be reported from the latest release.

That's latest F-Droid release.

**Comment by MuntashirAkon** [comment] 2022-05-05 17:54
> That's latest F-Droid release.

Try alpha or debug releases. Patches to the stable releases are backported from the current branch. So, this could be an issue due to a backported patch.

**Comment by MuntashirAkon** [comment] 2022-05-05 18:04
Hmm, seems to be reproducible in latest debug as well.

**Comment by k3n01** [comment] 2022-05-05 18:08
> Hmm, seems to be reproducible in latest debug as well.

I just reproduced it too from your latest CI artifact.

**Comment by MuntashirAkon** [comment] 2022-05-05 18:23
Fixed in 8b815851921497b7434a4cc4bcf1bd925f345424

**Closed by MuntashirAkon** 2022-05-05 18:23 UTC
Labels: Bug, S3, P3, Unsupported Version
