### ISSUE TITLE
ADB serverity

### ISSUE THREAD

**Issue by NSTAdventure** [MuntashirAkon/AppManager#871] opened 2022-09-18 01:57 UTC
- [ ✓] I know what my device, OS and App Manager versions are
- [ ✓] I know how to take logs
- [ ✓] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**
ADB over TCP is causing app manager stuck in initializing or app list forever

**To Reproduce**
Steps to reproduce the behaviour:
1. Download and install latest app manager (3.0.1)

2. Grant ADB over TCP and change operation mode to ADB instead of auto or non root
3. App will stuck in initializing or loading app list forever 
**Expected behavior**
It should work :-/

**Screenshots**

**Crash logs**
This isn't crash log but just general log from app manager itself 
[logs-2022-09-18-09-10-45.zip](https://github.com/MuntashirAkon/AppManager/files/9592917/logs-2022-09-18-09-10-45.zip)

**Device info**
 - Device: Realne 5i
 - OS Version: Android 10
 - App Manager Version: 3.0 1 stable
 - Mode: adb

**Additional context**
All general tips such as clearing caches or data or both and rebooting is done but app are still stuck forever 🙏

**Comment by osjasmine** [comment] 2022-09-19 05:46
I had the same issue. AM was stuck on initialising so after sometime I closed AM from the recent list then reopened it.

Somehow AM was actually in adb over tcp mode now because when I clicked on system apps in the applist, I could disable them. So even though it seems like the process failed, it actually is sucessful but AM gets stuck.

**Comment by NSTAdventure** [comment] 2022-09-20 09:04
> I had the same issue. AM was stuck on initialising so after sometime I closed AM from the recent list then reopened it.

1. This horsement of annoyance already happened on older release the only difference is on latest version is getting worst or more annoying
I just wondering how ADB over TCP is actually work on app manager?
When it will fixed? 
No offensive but other app with adb over tcp are easy to use adb without annoyance

> Somehow AM was now in adb over tcp mode because when I clicked on system apps in the applist, I could disable them. So even though it seems like the process failed, it is actually sucessful.

Oh this one are interesting 🤔

**Comment by NSTAdventure** [comment] 2022-09-20 09:13
> I had the same issue. AM was stuck on initialising so after sometime I closed AM from the recent list then reopened it.

1. This bug is already exist since old build / release
But old release still can fixed temporarily using general tips like restart devices clear cache etc²
Latest 3.x.x release is really horsemen of the annoyance because there is no way to fix that currently 
Idk why  bug is not solved yet?

**Comment by MuntashirAkon** [comment] 2022-09-20 12:22
You have to take logs using the debug build: https://t.me/AppManagerDebug/2938

**Comment by NSTAdventure** [comment] 2022-09-20 12:44
> You have to take logs using the debug build: https://t.me/AppManagerDebug/2938

Wait can you upload the debug apk here?
I didn't have telegram and i won't create account

**Comment by MuntashirAkon** [comment] 2022-09-20 16:10
https://github.com/MuntashirAkon/AppManager/actions/runs/3091667453

**Comment by NSTAdventure** [comment] 2022-09-20 23:47
> https://github.com/MuntashirAkon/AppManager/actions/runs/3091667453

Debug log:

**Comment by MuntashirAkon** [comment] 2022-09-21 08:24
> Debug log:
> [2022-09-21-06-43-52.am.log](https://github.com/MuntashirAkon/AppManager/files/9611888/2022-09-21-06-43-52.am.log)

Not from logcat. Find them at `/sdcard/Android/data/io.github.muntashirakon.AppManager.debug/cache/am.log`.

**Comment by NSTAdventure** [comment] 2022-09-21 12:04
> > Debug log:
> > [2022-09-21-06-43-52.am.log](https://github.com/MuntashirAkon/AppManager/files/9611888/2022-09-21-06-43-52.am.log)
> 
> Not from logcat. Find them at `/sdcard/Android/data/io.github.muntashirakon.AppManager.debug/cache/am.log`.



> > Debug log:
> > [2022-09-21-06-43-52.am.log](https://github.com/MuntashirAkon/AppManager/files/9611888/2022-09-21-06-43-52.am.log)
> 
> Not from logcat. Find them at `/sdcard/Android/data/io.github.muntashirakon.AppManager.debug/cache/am.log`.

Yes sir previous comment has been updated:
https://github.com/MuntashirAkon/AppManager/issues/871#issuecomment-1253026156

🙏

**Comment by MuntashirAkon** [comment] 2022-09-21 13:28
It appears that a binder connection could not be made. Did you follow the guide properly? Realme devices often need special debugging options to be enabled before it can make any Binder connection.

**Comment by NSTAdventure** [comment] 2022-09-21 13:36
> It appears that a binder connection could not be made. Did you follow the guide properly?

Yes sir i do my best to follow the guide properly:
1. On laptop windows 10 i prepared latest adb zip file from official android source
2. On realme devices i enabled dev option and USB debugging then i follow general step to activating ADB over TCP via pc

> Realme devices often need special debugging options to be enabled before it can make any Binder connection.

3. I disabled permission monitoring
(This are only one additional step that i found on internet)

🙏

**Comment by NSTAdventure** [comment] 2022-09-21 14:43
> On your pc, open an ADB Shell by running `adb shell` and then run the following and send me the output:
> 
> ```
> ps -A | grep shell
> ```

shell         7756     1  143328   3816 0                   0 S adbd
shell        10747     1 4272284 115004 SyS_epoll_wait      0 S am_local_server
shell        11044  7756   27512   2616 SyS_rt_sigsuspend   0 S sh
shell        11055 11044   30064   3264 0                   0 R ps
shell        11056 11044   27272   2320 pipe_read           0 S grep

disclaimer:
before i use respective command i try to do general tips:
1. i clearing am debug cache and data then uninstall it
2. I disable USB debugging and developer option then using devices manager to clear all system cache
3. Reboot device
4. Turn dev option USB debugging and ADB over TCP back Then reinstall am debugg
5. Open AM debug then grant usb debugging access and now am debug is working 
(Maybe only work temporary official release have same thing only work temporary will stuck again after sometime)
7. Then i do that command and provide to output above
🙏

**Comment by MuntashirAkon** [comment] 2022-09-21 14:49
Closing for now. Next time you reproduce the issue, send me the output of the same command without following the steps.

**Closed by MuntashirAkon** 2022-09-21 14:49 UTC
Labels: Bug, Severity: 1, Priority: 0, Status: Accepted

**Comment by NSTAdventure** [comment] 2022-09-21 15:16
> Closing for now. Next time you reproduce the issue, send me the output of the same command without following the steps.

attempting to reproduce issues and this happenned:
DNS server not authoritative for zone.

**Comment by NSTAdventure** [comment] 2022-09-21 15:27
> Closing for now. Next time you reproduce the issue, send me the output of the same command without following the steps.

hi sir i manage to reproduce issues again where am stuck in initializing cannot use ADB over TCP and this are output now:
shell        16167     1  160760   4016 0                   0 S adbd
shell        16330     1 4272284  85812 SyS_epoll_wait      0 S am_local_server
shell        19635 16167   27512   2656 SyS_rt_sigsuspend   0 S sh
shell        19693 19635   30064   3284 0                   0 R ps
shell        19694 19635   27272   2320 pipe_read           0 S grep

**Comment by MuntashirAkon** [comment] 2022-09-21 15:28
Logs?

**Comment by NSTAdventure** [comment] 2022-09-21 15:31
> Logs?

Yes i already upload logs in previous comment:
https://github.com/MuntashirAkon/AppManager/issues/871#issuecomment-1253871496.

🙏

**Comment by MuntashirAkon** [comment] 2022-09-21 15:46
Yes, it will not remain stuck forever as there is a timeout of 45 seconds. Also, take the output of the command _after_ taking the logs.

**Comment by NSTAdventure** [comment] 2022-09-21 15:55
> take the output of the command _after_ taking the logs.

The output command after i take log from am is still like this:
https://github.com/MuntashirAkon/AppManager/issues/871#issuecomment-1253871496

**Comment by MuntashirAkon** [comment] 2022-09-21 16:16
> I just realize something
> Am public release can't fully detect adb
> Meanwhile am debug that you shared is still can detect adb but app list not appear
> The only same thing is both release is sometime can stuck initializing forever

Software development is not some kind of dark magic, they are based on pure logic. Both debug and release builds are identical, except that release builds contains no debug symbols. However, you cannot simultaneously use both builds. When you use debug builds, you cannot use release builds without a reboot, and vice versa.

**Comment by NSTAdventure** [comment] 2022-09-21 16:31
> > I just realize something
> > Am public release can't fully detect adb
> > Meanwhile am debug that you shared is still can detect adb but app list not appear
> > The only same thing is both release is sometime can stuck initializing forever
> 
> Software development is not some kind of dark magic, they are based on pure logic. Both debug and release builds are identical, except that release builds contains no debug symbols. However, you cannot simultaneously use both builds. When you use debug builds, you cannot use release builds without a reboot, and vice versa.

Yes sir i was do that long time ago before 3.x.x release?
Anyway did you able to figure out what happened with adb connections? Is that bug from my devices?
