### ISSUE TITLE
Include features from android-autostarts (miracle2k)

### ISSUE THREAD

**Issue by Rexadev** [MuntashirAkon/AppManager#1279] opened 2024-01-28 07:37 UTC
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

https://github.com/miracle2k/android-autostarts
Tool to manage autostarts (broadcast receivers) on an Android device.

![image](https://github.com/MuntashirAkon/AppManager/assets/62152714/46e279c9-e885-4bc0-82d7-d98122e577df)

**Comment by MuntashirAkon** [comment] 2024-01-28 11:36
Duplicate of #309

**Closed by MuntashirAkon** 2024-01-28 11:36 UTC
Labels: Duplicate, Feature
