### ISSUE TITLE
Add ability to filter/search apps by permission/app ops

### ISSUE THREAD

**Issue by kryptobolt200528** [MuntashirAkon/AppManager#714] opened 2022-03-30 02:08 UTC
Please add the ability to filter/search apps by permission/app ops...eg filtering apps with ACCESS_ACCESSBILITY app ops/permission

**Comment by MuntashirAkon** [comment] 2022-03-30 04:10
Duplicate of #321

**Closed by MuntashirAkon** 2022-03-30 04:10 UTC
Labels: P3

**Comment by MuntashirAkon** [comment] 2022-05-01 09:49
Locked due to https://github.com/MuntashirAkon/AppManager/issues/730#issuecomment-1114186327
