### ISSUE TITLE
App crash 

### ISSUE THREAD

**Issue by NSTAdventure** [MuntashirAkon/AppManager#852] opened 2022-08-27 05:58 UTC
- [✓ ] I know what my device, OS and App Manager versions are
- [ ✓] I know how to take logs
- [ X ] I know how to reproduce the issue which may not be specific to my device

**Describe the bug**
App manager crash upon starting or initializing 

**To Reproduce**
Steps to reproduce the behaviour:
1. make sure app not running yet
2. launch the app manager
3. app crash 

**Expected behavior**
App shouldn't crash

**Screenshots**

**Crash logs**
java.lang.RuntimeException: Parcel android.os.Parcel@7823fa6: Unmarshalling unknown type code 6881398 at offset 716
    at android.os.Parcel.readValue(Parcel.java:2961)
    at android.os.Parcel.readSparseArrayInternal(Parcel.java:3343)
    at android.os.Parcel.readSparseArray(Parcel.java:2500)
    at android.os.Parcel.readValue(Parcel.java:2939)
    at android.os.Parcel.readArrayMapInternal(Parcel.java:3260)
    at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
    at android.os.BaseBundle.unparcel(BaseBundle.java:236)
    at android.os.Bundle.getSparseParcelableArray(Bundle.java:1029)
    at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2164)
    at android.app.Activity.onRestoreInstanceState(Activity.java:1631)
    at android.app.Activity.performRestoreInstanceState(Activity.java:1577)
    at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1367)
    at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3551)
    at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:237)
    at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:217)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:189)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:113)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2213)
    at android.os.Handler.dispatchMessage(Handler.java:107)
    at android.os.Looper.loop(Looper.java:238)
    at android.app.ActivityThread.main(ActivityThread.java:7853)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:984)

Device Info:
App version: 3.0.0
App version code: 410
Android build version: 1608537052
Android release version: 10
Android SDK version: 29
Android build ID: RMX2030EX_11_C.67
Device brand: realme
Device manufacturer: realme
Device name: RMX2030
Device model: RMX2030
Device product name: RMX2030
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: id-ID
In-App Language: auto
Mode: adb_tcp

**Device info**
 - Device: Realme 5i
 - OS Version: Android 10
 - App Manager Version: 3.0.0
 - Mode: adb

**Additional context**
app manager using ADB mode
all required permission is also granted

**Comment by MuntashirAkon** [comment] 2022-08-27 07:04
Duplicate of #656

**Closed by MuntashirAkon** 2022-08-27 07:04 UTC
Labels: Bug, Duplicate
