### ISSUE TITLE
java.io.FileNotFoundException: No available shared storage found.

### ISSUE THREAD

**Issue by iambeingtracked** [MuntashirAkon/AppManager#1087] opened 2023-06-05 10:27 UTC
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

I recently updated to crdroid Android 13 on my Realme 6 Pro. And now App Manager doesn't launch with root mode but it crashes, although it works with no root.

On 2 earlier version available on F-droid it just didn't go past initializing

### To Reproduce

- 1. Get a Realme 6 Pro
- 2. Install crdroid Android 13 on it
- 3. Install App Manager from F-Droid on it.

### Expected behavior

It should launch

### Logs

https://paste.crdroid.net/Y1xJEt

### Device info

- Device: Realme 6 Pro
- OS Version: crDroid Android 13 grabbed from crdroid.net
- App Manager Version: 3.1.0
- Mode: Root

### Additional context

I did a full new install, so the previous data was wiped, so it is all new. And it launches with no root mode

Root was obtained by Magisk

**Comment by MuntashirAkon** [comment] 2023-06-05 10:31
Duplicate of #948

**Comment by MuntashirAkon** [comment] 2023-06-05 10:31
Please go through the linked issue to understand the issue.

**Closed by MuntashirAkon** 2023-06-05 10:31 UTC
Labels: Bug

**Comment by MuntashirAkon** [comment] 2023-06-05 10:33
https://github.com/MuntashirAkon/AppManager/issues/948#issuecomment-1556151496
