### ISSUE TITLE
Directry style class viewer like Dexplorer

### ISSUE THREAD

**Issue by gnuhead-chieb** [MuntashirAkon/AppManager#334] opened 2021-03-23 22:32 UTC
https://play.google.com/store/apps/details?id=com.dexplorer&hl=en_US&gl=US

Example:

https://user-images.githubusercontent.com/41156994/112227413-8b15b180-8c27-11eb-9f21-9dd7e11ce81b.mp4

**Comment by MuntashirAkon** [comment] 2021-03-24 02:11
Duplicate of #138

**Closed by MuntashirAkon** 2021-03-24 02:11 UTC
Labels: P3, feature
