### ISSUE TITLE
Unable to use the current mode of operation 

### ISSUE THREAD

**Issue by Kero309x** [MuntashirAkon/AppManager#1010] opened 2023-02-23 16:55 UTC
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

My device is running custom ROM based on AOSP Android 13 SDK 33, I installed App Manager v3.1.0 beta 01/02 and have Root Privilege and granted the app root access then in Mode of operation in settings layout cannot use the Root Mode and a toast message appears " unable to use the current mode of operation" and inferred mode is non root.

### Screenshots

![Screenshot_20230223-185305](https://user-images.githubusercontent.com/55901942/220975464-883dc3f8-e46b-4d5a-9654-e4e8f1678df7.png)

### Device info

- Device: Redmi Note 9 Pro ( Custom ROM )
- OS Version: 13
- App Manager Version: 3.1.0 Beta 02
- Mode: Root/ADB/NonRoot (Root)

**Comment by MuntashirAkon** [comment] 2023-02-24 06:16
Logs?

**Comment by nickel3000** [comment] 2023-03-01 20:13
Have the same device and same issue.
[logs-2023-03-01-23-04-01.zip](https://github.com/MuntashirAkon/AppManager/files/10864936/logs-2023-03-01-23-04-01.zip)

**Comment by MuntashirAkon** [comment] 2023-03-01 20:18
Duplicate of #948

**Closed by MuntashirAkon** 2023-03-01 20:18 UTC
Labels: Bug
