### ISSUE TITLE
Crash when opening any app info

### ISSUE THREAD

**Issue by FloofyWoo** [MuntashirAkon/AppManager#1301] opened 2024-03-02 08:50 UTC
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Whenever i try to open any app's infos, the app crashes.

### To Reproduce

Step one, launch app.
Step 2, click any app.
Crash.

### Expected behavior

Not crashing

### Logs

java.lang.RuntimeException: Unable to start activity ComponentInfo{io.github.muntashirakon.AppManager/io.github.muntashirakon.AppManager.details.AppDetailsActivity}: java.lang.RuntimeException: Cannot create an instance of class io.github.muntashirakon.AppManager.details.AppDetailsViewModel
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3958)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4138)
    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:110)
    at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:230)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:186)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2556)
    at android.os.Handler.dispatchMessage(Handler.java:107)
    at android.os.Looper.loopOnce(Looper.java:232)
    at android.os.Looper.loop(Looper.java:317)
    at android.app.ActivityThread.main(ActivityThread.java:8516)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
 Caused by: java.lang.RuntimeException: Cannot create an instance of class io.github.muntashirakon.AppManager.details.AppDetailsViewModel
   at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:320)
   at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:304)
   at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:278)
   at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.kt:128)
   at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:187)
   at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:153)
   at io.github.muntashirakon.AppManager.details.AppDetailsActivity.onAuthenticated(AppDetailsActivity.java:96)
   at io.github.muntashirakon.AppManager.BaseActivity.onCreate(BaseActivity.java:87)
   at android.app.Activity.performCreate(Activity.java:8766)
   at android.app.Activity.performCreate(Activity.java:8744)
   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1519)
   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3940)
   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4138)
   at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:110)
   at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:230)
   at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:186)
   at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2556)
   at android.os.Handler.dispatchMessage(Handler.java:107)
   at android.os.Looper.loopOnce(Looper.java:232)
   at android.os.Looper.loop(Looper.java:317)
   at android.app.ActivityThread.main(ActivityThread.java:8516)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
 Caused by: java.lang.reflect.InvocationTargetException
   at java.lang.reflect.Constructor.newInstance0(Native Method)
   at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
   at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:312)
   at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:304)
   at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:278)
   at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.kt:128)
   at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:187)
   at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:153)
   at io.github.muntashirakon.AppManager.details.AppDetailsActivity.onAuthenticated(AppDetailsActivity.java:96)
   at io.github.muntashirakon.AppManager.BaseActivity.onCreate(BaseActivity.java:87)
   at android.app.Activity.performCreate(Activity.java:8766)
   at android.app.Activity.performCreate(Activity.java:8744)
   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1519)
   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3940)
   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4138)
   at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:110)
   at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:230)
   at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:186)
   at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2556)
   at android.os.Handler.dispatchMessage(Handler.java:107)
   at android.os.Looper.loopOnce(Looper.java:232)
   at android.os.Looper.loop(Looper.java:317)
   at android.app.ActivityThread.main(ActivityThread.java:8516)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
 Caused by: java.lang.NoSuchMethodError: No interface method grantRuntimePermission(Ljava/lang/String;Ljava/lang/String;I)V in class Landroid/permission/IPermissionManager; or its super classes (declaration of 'android.permission.IPermissionManager' appears in /system/framework/framework.jar!classes3.dex)
   at io.github.muntashirakon.AppManager.compat.PermissionCompat.grantPermission(PermissionCompat.java:333)
   at io.github.muntashirakon.AppManager.compat.AppOpsManagerCompat.<init>(AppOpsManagerCompat.java:629)
   at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.<init>(AppDetailsViewModel.java:668)
   at java.lang.reflect.Constructor.newInstance0(Native Method)
   at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
   at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:312)
   at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:304)
   at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:278)
   at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.kt:128)
   at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:187)
   at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:153)
   at io.github.muntashirakon.AppManager.details.AppDetailsActivity.onAuthenticated(AppDetailsActivity.java:96)
   at io.github.muntashirakon.AppManager.BaseActivity.onCreate(BaseActivity.java:87)
   at android.app.Activity.performCreate(Activity.java:8766)
   at android.app.Activity.performCreate(Activity.java:8744)
   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1519)
   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3940)
   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4138)
   at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:110)
   at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:230)
   at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:186)
   at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2556)
   at android.os.Handler.dispatchMessage(Handler.java:107)
   at android.os.Looper.loopOnce(Looper.java:232)
   at android.os.Looper.loop(Looper.java:317)
   at android.app.ActivityThread.main(ActivityThread.java:8516)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)

Device Info:
App version: 3.1.4
App version code: 427
Android build version: 11395453
Android release version: 14
Android SDK version: 34
Android build ID: AP21.240119.009
Device brand: google
Device manufacturer: Google
Device name: shiba
Device model: Pixel 8
Device product name: shiba_beta
Device hardware name: shiba
ABIs: [arm64-v8a]
ABIs (32bit): []
ABIs (64bit): [arm64-v8a]
System language: en-CA
In-App Language: auto
Mode: auto
Inferred Mode: root

### Device info

- Device: Google Pixel 8
- OS Version: Android 14
- App Manager Version: v3.1.4
- Mode: Root

**Comment by FloofyWoo** [comment] 2024-03-02 08:57
When i try to alpha 4.0.0 version i get a different crash


java.lang.RuntimeException: java.lang.NoSuchMethodError: No interface method getActiveSubscriptionInfoList(Ljava/lang/String;Ljava/lang/String;)Ljava/util/List; in class Lcom/android/internal/telephony/ISub; or its super classes (declaration of 'com.android.internal.telephony.ISub' appears in /system/framework/framework.jar!classes5.dex)
    at io.github.muntashirakon.AppManager.details.info.AppInfoViewModel.lambda$loadAppInfoInternal$5(AppInfoViewModel.java:386)
    at io.github.muntashirakon.AppManager.details.info.AppInfoViewModel$$ExternalSyntheticLambda5.run(Unknown Source:2)
    at android.os.Handler.handleCallback(Handler.java:959)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loopOnce(Looper.java:232)
    at android.os.Looper.loop(Looper.java:317)
    at android.app.ActivityThread.main(ActivityThread.java:8516)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
 Caused by: java.lang.NoSuchMethodError: No interface method getActiveSubscriptionInfoList(Ljava/lang/String;Ljava/lang/String;)Ljava/util/List; in class Lcom/android/internal/telephony/ISub; or its super classes (declaration of 'com.android.internal.telephony.ISub' appears in /system/framework/framework.jar!classes5.dex)
   at io.github.muntashirakon.AppManager.compat.SubscriptionManagerCompat.getActiveSubscriptionInfoList(SubscriptionManagerCompat.java:31)
   at io.github.muntashirakon.AppManager.usage.AppUsageStatsManager.getSubscriberIds(AppUsageStatsManager.java:432)
   at io.github.muntashirakon.AppManager.usage.AppUsageStatsManager.getDataUsageForPackage(AppUsageStatsManager.java:384)
   at io.github.muntashirakon.AppManager.details.info.AppInfoViewModel.loadAppInfoInternal(AppInfoViewModel.java:352)
   at io.github.muntashirakon.AppManager.details.info.AppInfoViewModel.lambda$loadAppInfo$4$io-github-muntashirakon-AppManager-details-info-AppInfoViewModel(AppInfoViewModel.java:316)
   at io.github.muntashirakon.AppManager.details.info.AppInfoViewModel$$ExternalSyntheticLambda4.run(Unknown Source:6)
   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
   at java.util.concurrent.FutureTask.run(FutureTask.java:264)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
   at java.lang.Thread.run(Thread.java:1012)

Device Info:
App version: 4.0.0-alpha02
App version code: 435
Android build version: 11395453
Android release version: 14
Android SDK version: 34
Android build ID: AP21.240119.009
Device brand: google
Device manufacturer: Google
Device name: shiba
Device model: Pixel 8
Device product name: shiba_beta
Device hardware name: shiba
ABIs: [arm64-v8a]
ABIs (32bit): []
ABIs (64bit): [arm64-v8a]
System language: en-CA
In-App Language: auto
Mode: root
Inferred Mode: Root

**Comment by FloofyWoo** [comment] 2024-03-09 06:02
Yeah qrp2 breaks a lot of shit. It breaks ls posed aswell :/

**Comment by MuntashirAkon** [comment] 2024-03-09 07:04
Already fixed in the master branch. Will be back ported to the stable release next week.

**Comment by festum** [comment] 2024-03-16 10:15
Awaiting for the new release 🙏

**Comment by FloofyWoo** [comment] 2024-03-18 14:35
It did fix for me. Im able to view app infos now.
![Screenshot_20240318-103510](https://github.com/MuntashirAkon/AppManager/assets/52764294/c96172e4-f227-4f04-b99f-53b077d2ef83)

**Comment by MuntashirAkon** [comment] 2024-03-18 15:13
Let me clear the situation: The issue is only partly fixed (hence, it's still open). Another fix will be available soon which will close the issue.

**Comment by MuntashirAkon** [comment] 2024-03-18 15:51
> Looks like #1308 did a bit more homework than I did

I agree. Closing this in favour of #1308, but not marked as duplicate since the original issue was different from yours.

**Closed by MuntashirAkon** 2024-03-18 15:51 UTC
Labels: Bug
