### ISSUE TITLE
[Feature Request] Startup Manager

### ISSUE THREAD

**Issue by dhammel** [MuntashirAkon/AppManager#1006] opened 2023-02-22 20:29 UTC
Hello,

there is one feature that I would like to see and it could replace another app I use which is to disable startup events of apps like permission RECEIVE_BOOT_COMPLETED to prevent apps from starting up with device. I know that some apps (very few in my case) end up re-enabling it somehow anyway, but it works great for most apps.

Would you consider this?

Thank you

**Comment by Pahomk** [comment] 2023-02-22 21:11
I support this idea

**Comment by MuntashirAkon** [comment] 2023-02-23 08:45
Duplicate of #309

**Closed by MuntashirAkon** 2023-02-23 08:45 UTC
