### ISSUE TITLE
how-to unset F-Droid defaulting to AppManager as default installer

### ISSUE THREAD

**Issue by darvari** [MuntashirAkon/AppManager#1442] opened 2024-08-30 11:45 UTC
### Describe the existing feature/documentation

F-Droid always installs everything using App Manager

### Describe your problem(s)

I want to unset this (especially for F-Droid) and set the default system 'Package Installer' as default.
If I install a local app from the filesystem with File app - I get to choose which installer I can use.

### Additional context

At some point I must have selected App Manager as default installer.
But I can't remember in which situation.
I've looked in the settings of F-Droid and AppManager, as well as in android settings checking each of the above apps for defaulted opening apps, but can't find anything.

**Comment by MuntashirAkon** [comment] 2024-09-02 05:01
1. Open the info page of App Manager in Android Settings app
2. Click “Open by default” item
3. Click “Clear default preferences” button if present

**Comment by MuntashirAkon** [comment] 2024-09-02 05:01
Duplicate of #1437

**Closed by MuntashirAkon** 2024-09-02 05:01 UTC
Labels: Help Wanted
