### ISSUE TITLE
Patching apps with frida and/or Xpatch

### ISSUE THREAD

**Issue by gnuhead-chieb** [MuntashirAkon/AppManager#278] opened 2021-02-08 19:39 UTC
This issue related to https://github.com/MuntashirAkon/AppManager/issues/138

It is low priority because it's very advanced feature,so this feature is maybe useless for most users.
But useful for some users who want to reverse engineering apps.

Xpatch:
https://github.com/WindySha/Xpatch/blob/master/README_en.md

Frida:
https://frida.re/docs/gadget/

**Comment by MuntashirAkon** [comment] 2021-02-09 02:36
Duplicate of #138

**Comment by MuntashirAkon** [comment] 2021-02-09 02:37
Discuss these options in the relevant issues instead of creating new ones.

**Closed by MuntashirAkon** 2021-02-09 02:36 UTC
Labels: P3, duplicate, feature
