### ISSUE TITLE
Application Manager Showing Incorrect Data for Usage Times

### ISSUE THREAD

**Issue by Deerp1976** [MuntashirAkon/AppManager#19] opened 2020-06-21 17:22 UTC
Phone Huawei Honor 8S
Android OS EMUI 9.1.0
Rooted - no
Usage Information Access permission given to Application Manager
Application version used 2.5.1 from Izzys Fdroid repo. 

Please see screenshot for what Application Manager states is my usage time for applications over 1 day, a week and 1 month. The monthly one is showing - 11 days usage!

![Screenshot_20200621_181057_io github muntashirakon AppManager](https://user-images.githubusercontent.com/61953306/85231034-f4903780-b3eb-11ea-92e9-fbef866f2db4.jpg)
![Screenshot_20200621_181104_io github muntashirakon AppManager](https://user-images.githubusercontent.com/61953306/85231035-f5c16480-b3eb-11ea-9a83-41997eab2d77.jpg)
![Screenshot_20200621_181049_io github muntashirakon AppManager](https://user-images.githubusercontent.com/61953306/85231036-f659fb00-b3eb-11ea-82d4-56dc18c3522d.jpg)

**Comment by MuntashirAkon** [comment] 2020-06-21 17:33
Thanks for informing me. The current implementation of App Usage is actually sort of broken (don't blame me, I copied it from other open source project :) ). See issue #15 for my in-depth plan on App Usage.

**Comment by Deerp1976** [comment] 2020-06-21 17:37
No problem. It's weird because some applications have duplicate information. Take Chrome for example from screenshot. It's. system app so I've not deleted it and installed again so not sure why it's showing 2 lots of usage data unless your app works out app usage from each update?

**Comment by MuntashirAkon** [comment] 2020-06-21 17:55
> I've not deleted it and installed again so not sure why it's showing 2 lots of usage data unless your app works out app usage from each update?

I'm not sure. Duplicate values appeared probably because the query that I've made produced duplicate results. The UsageStatsManager API is actually a bit difficult to work with and there's no documentation on how the default intervals actually work with `UsageStats`. I'll soon use `UsageEvents` which is a bit better than the current one.

**Comment by MuntashirAkon** [comment] 2020-06-22 12:04
Please check if this works for you: (Compressed since Github doesn't support apk uploading)
[AppManager_v2.5.3 (177).apk.zip](https://github.com/MuntashirAkon/AppManager/files/4813053/AppManager_v2.5.3.177.apk.zip)

**Comment by Deerp1976** [comment] 2020-06-22 12:37
I've downloaded it. When I check version it is not 2.5.3 but still 2.5.2.

I can see you have a new settings button with root already chose. If I choose to block global components on any app now, it does not come up with warning to say cannot block like it did before. It's as if it has worked but after testing blocking an activity, it will still launch. 

App usage the weekly usage has changed from 9 days to 3 days total. That works out at roughly 10 hours per day? If so that sounds about right as I use my phone a lot. The other times are still the same, the 1 day is coming up as 1 day and 5 hours, the monthly 1 is still - 11 days.

The screens where activity, permissions etc, last version 2.5.2 from Izzys repo, all the screen were blank data apart from activity. Now if I click refresh, it will show data for every screen apart from app ops which is what I expected. Obviously if there are no services it will not show data but signatures etc all showing now when refresh is clicked. No refresh = nothing showing apart from activity.

I deleted Solid Explorer so now if I try the folders option it just takes me to MiXplorer which is a disappointment as this file explorer cannot open or even view anything apart from the folder where the APK is stored. Not your fault you have explained it well. 

Have I missed anything out you needed me to test? Need any screenshots of anything? I'm a little busy this afternoon so it might be early evening I can fully analyse anything you need.

Just going on what you have done its certainly an improvement. It now needs a root checker if you select the root option and blocking global components or at least a pop up to say if you are not rooted these options will not work.

**Comment by MuntashirAkon** [comment] 2020-06-22 13:45
Thanks for the feedback. I used material design's ViewPager2, which is still very buggy. So, if you click on tabs instead of swiping, things may not work as expected.

Did you try other app usage viewers like usageDirect and AppsMonitor (available on F-Droid and IzzyOnDroid)? What results do they return for weeks/months/years?

> It now needs a root checker

Thanks. It's in my todo list. The problem is there's no perfect root checker. But I'll try one anyway.

**Comment by Deerp1976** [comment] 2020-06-22 14:08
I have installed both of those apps and compared to my system app from Huawei called Digital Balance. Apps Monitor seems to match Digital Balance perfectly whereas Usage Direct is way out. Not sure what they are check against but having 1 app matching a system app I think it would be logical to assume Apps Monitor is the one showing the correct usage. Hopefully that will help you to see how they achieve those results and add to your app.

Oh it mentions a dark mode on description here and on FDroid but I have not seen this option. Is it only for Android 10 and above? It would be great to have a dark mode although your use of colour might be affected.

**Comment by MuntashirAkon** [comment] 2020-06-22 15:01
> I have installed both of those apps and compared to my system app from Huawei called Digital Balance. Apps Monitor seems to match Digital Balance perfectly whereas Usage Direct is way out. Not sure what they are check against but having 1 app matching a system app I think it would be logical to assume Apps Monitor is the one showing the correct usage. Hopefully that will help you to see how they achieve those results and add to your app.

Thanks for checking. The difference is that **usageDirect** uses `UsageStats` and **AppsMonitor** uses `UsageEvents`. I'll eventually move to the latter.

> Oh it mentions a dark mode on description here and on FDroid but I have not seen this option. Is it only for Android 10 and above? It would be great to have a dark mode although your use of colour might be affected.

Yeah, it might require some testing. I'll keep that in my todo list.

**Comment by MuntashirAkon** [comment] 2020-06-22 15:01
> I have installed both of those apps and compared to my system app from Huawei called Digital Balance. Apps Monitor seems to match Digital Balance perfectly whereas Usage Direct is way out. Not sure what they are check against but having 1 app matching a system app I think it would be logical to assume Apps Monitor is the one showing the correct usage. Hopefully that will help you to see how they achieve those results and add to your app.

Thanks for checking. The difference is that **usageDirect** uses `UsageStats` and **AppsMonitor** uses `UsageEvents`. I'll eventually move to the latter.

> Oh it mentions a dark mode on description here and on FDroid but I have not seen this option. Is it only for Android 10 and above? It would be great to have a dark mode although your use of colour might be affected.

Yeah, it might require some testing. I'll keep that in my todo list.

**Comment by MuntashirAkon** [comment] 2020-06-22 19:19
Try this: 
[AppManager_v2.5.3 (182).apk.zip](https://github.com/MuntashirAkon/AppManager/files/4815169/AppManager_v2.5.3.182.apk.zip)

**Comment by Deerp1976** [comment] 2020-06-23 03:11
Many thanks for your update. It has been a most interesting and also most perplexing couple of hours I've had in quite a while trying to compare the data between the 4 apps tested for app usage - Apps Manager, Apps Monitor, Usage Direct and Huawei Digital Balance. 

Each app has different options of how long you can see app usage. Apps Monitor is only for today's and yesterday's data, all the others are for today, yesterday, weekly and monthly although Huawei Digital Balance has made my life difficult by correctly putting today's usage from midnight like the others but works out the % used over a 24 hour period which makes no sense at all.

One thing I have seen and can say with certainty is your app is not including system app usage like the others do. Apps such as Google Cbrome, Play Store etc do not show at all on your app. Interestingly Apps Monitor has an option to hide system apps and also disabled apps whereas yours and Usage Direct do not.

I am sending you over 4 screenshots, one for each app and the data is for today starting from midnight.

There are differences I cannot work out between all apps. 

I am not ready to send over results for yesterday as Apps Direct is showing extremely unusual data. Suffice to say Apps Direct believes I was on the system Contacts app from around 10am yesterday to 8pm and was on it constantly. All the others have the Contacts app for the past week at around 2 minutes total so I need to work out what is going on with it. My initial thoughts were the app is working out app usage from the actual app that Launched the ones I was using as I do sometimes use dialer codes to access parts of the phone I shouldnt! I do also have Lucky Patcher installed which I use frequently to launch other apps. Same reason I use yours to launch others as well.

Enjoy the screenshots

![Screenshot_20200623_035326_godau fynn usagedirect](https://user-images.githubusercontent.com/61953306/85356580-3530a380-b507-11ea-81fc-e541ed0cb468.jpg)
![Screenshot_20200623_035311_io github muntashirakon AppManager](https://user-images.githubusercontent.com/61953306/85356583-3661d080-b507-11ea-91b5-d07d160f4418.jpg)
![Screenshot_20200623_035318_timeline lizimumu com t](https://user-images.githubusercontent.com/61953306/85356584-36fa6700-b507-11ea-92a2-c3c320bfd65e.jpg)
![Screenshot_20200623_035348_com huawei parentcontrol](https://user-images.githubusercontent.com/61953306/85356585-3792fd80-b507-11ea-9f5e-9e269afa6c72.jpg)

**Comment by MuntashirAkon** [comment] 2020-06-23 03:36
> One thing I have seen and can say with certainty is your app is not including system app usage like the others do.

Yes, I've disabled them for some reason and forgot to enable them later. I'll enable them next time.

I would also like to know whether **Monthly** data are accurate (this shouldn't be). The underlying API is not well documented, and though support is there since API 21 (Lollipop), most features are added in API 28 (Pie) which, again, use separate data structures. The built-in app for your phone has the advantage of not worrying about this compatibility issue which I do in order to support Lollipop to Android Q.

**Comment by Deerp1976** [comment] 2020-06-23 05:07
I can give you the weekly app usage but if I requested monthly data, it will fully open the app meaning there will be a constant running service and notification that doesnt go away. This health balance app has its own security which stops any updates being uninstalled. Even Google Play Services app allows that. I cannot view the manifest via your app and only way I can is to view it via FX File Explorer by opening up the APK first. None of the activities will run. It has its own security certificates in the APK. It has permissions I have never seen before.

So if you don't mind, I would rather not give this app any further privileges than what it has now. At the moment it does not run constantly and I can view up to 7 days app usage which I am more than happy to do. Anymore than that I will have to give permission to the app to control screen management and I do not want to do that. This app also has the display over other apps but the difference between this one and all the others is you cannot take this permission off.

Let me know how I can give you the app usage data for the past week and I will send it to you. I would rather not post all my activities on here so everyone can see what apps I use, how often I use them and when. I have nothing to hide but I value my privacy a lot. 

I can send via email if you provide me with yours?

**Comment by Deerp1976** [comment] 2020-06-23 05:31
I have had an idea. I have just installed Google Wellbeing app to my phone by going on APK Mirror and getting apk that way. I will need to run the main activity from your app to manually open it and request the app icon to be viewed so I can open the app via normal means but this will work. The only difference with this app is I can only view the past 7 or 8 days of app usage and Google collates it by day rather than week but its a good alternative to giving a Huawei system app more permissions than it already should have.

Do you know why Apps Monitor needs access to phone permission for? Does it get usage data from that screen that's on the hidden test menu *#*#4636#*#' which also has an app usage statistic? There is also an updated version in Play Store but unless I uninstall Fdroid version I cannot install Google Play Store one. I may get the APK from APK Updater and compare the two.

Also I do not even have the option of viewing the data folders for any app now as the link to take you to a file explorer is now gone?

**Comment by MuntashirAkon** [comment] 2020-06-23 06:06
> I can send via email if you provide me with yours?

You should see my email address in my github profile since you're a registered user.

> Also I do not even have the option of viewing the data folders for any app now as the link to take you to a file explorer is now gone?

Yeah. It doesn't work for non-root users anyway. You can still copy the path though (text selection still works).

**Comment by MuntashirAkon** [comment] 2020-06-23 06:09
> Do you know why Apps Monitor needs access to phone permission for?

To read mobile data usage, I believe.

> The only difference with this app is I can only view the past 7 or 8 days of app usage

It's probably because usage stats are not kept for long period of time.

**Comment by MuntashirAkon** [comment] 2020-06-23 06:15
> It has permissions I have never seen before.

Custom permissions can be added. They may have customised the OS itself to give their product higher privileges. MITM is not impossible either since they can control everything via their system apps (even hosts file/dns blocking/vpn can be easily bypassed like what Microsoft did with Windows).

**Comment by MuntashirAkon** [comment] 2020-06-23 14:31
I'm removing monthly and yearly usage stats as Android doesn't keep usages events for such long period of time. The other option is to use `UsageStats` which doesn't seem to yield good results. I mean it does return some usage stats but by usage we usually mean screen time. That's being said, I think I might found out why Apps Direct is showing wrong results for some applications: they're algorithm to parse `UsageEvents` is wrong. I used similar approach but later found that I use Lawnchair (the luncher that I'm currently using) for 8 hours in last 20 hours or so. Then I ended up copying AppsMonitor's algorthim.

I also noticed that somewhat similarity between Digital Balance and usageDirect: it probably means that both use `UsageStats` (the former is probably using `INTERVAL_BEST` instead of `INTERVAL_DAILY`).

**Comment by Deerp1976** [comment] 2020-06-23 14:48
I am pleased you are gaining an understanding with usage stats because I was starting to get very confused with it.

I have been away from my phone for sever hours and it eventually ran out of battery. 

When I come to check my app usage now on yours and Digital Balance, it says that I have been using Digital Wellbeing for 4 hours. As this application can in normal means only be run in settings app in Pixel phones and I have to use your activity launcher to find secret launches (I found a way to add a quick tile for Digital Wellbeing via your app and even a way to configure it!), I struggle to understand how I have used this app for more than a few minutes. My initial thoughts were that these usage stats include running services that you can see in developer options but if that was the case, every app that has accessability and notification access and clearly they are not included in usage stats.

I did find something else that doesn't work with your app - being able to force stop an app. I always get a fail message. I know for a fact this works non root as 3c Toolbox Pro has a task manager where you could if you so wished, force stop every single app running. Greenify also works non root but 8 believe both rely on accessibility permission which causes no end of problems on my phone as Huawei has a hidden system app called Power Genius which can kill any app it wants that doesn't appear on its whitelist and its impossible to change this whitelist to include other apps. 

I don't like apps that rely on accessibility permission as they will be a constant running service.

**Comment by Deerp1976** [comment] 2020-06-23 15:50
Have you seen this app in the play store - https://play.google.com/store/apps/details?id=com.a0soft.gphone.uninstaller

It manages to get some very impressive stats such as what times you open apps, when you shut them, pie charts detailing high usage of apps but it does request the accessibility and notification permissions to do so which means I have to take the app off battery optimization and allow it to run all the time and also need to include this app on my whitelist for Huawei not to inform me it is a power intensive app so no doubt this app will use a lot of battery to properly run. 

I doubt this app is open source and to fully unlock all of its services there is a payment of nearly £20 to pay which clearly I will not be willing to do! It does have one interesting comment on the app description though - 'Due to the restriction of Android, the app usage can only be tracked when you are using the app and screen is on.'

If this is indeed true, I am really struggling to work out how I am supposed to have used Digital Wellbeing for 4 hours today because even if I left that open when I wasn't using my phone for several hours, my phones screen would have turned itself off after 15 minutes.

**Comment by MuntashirAkon** [comment] 2020-06-23 17:47
> If this is indeed true, I am really struggling to work out how I am supposed to have used Digital Wellbeing for 4 hours today because even if I left that open when I wasn't using my phone for several hours, my phones screen would have turned itself off after 15 minutes.

There's always a chance of false positive. If you open an app and keep it running for a long time without opening another app (this usually happens with apps having unusual permissions or privileges in which case the app can't be stopped by the system routine), there's a small but possible chance that the screen time of the app will be usual.

Let me explain how my screen time algorithm works which utilizes `UsageEvents` just like AppsMonitor. When you query events in a fixed interval (say last 24 hours), the system will return a list of apps with event number and the time when the event was fired in that interval. `ACTIVITY_RESUMED` event means that the app is running in the foreground which usually means the user is actively using it, and `ACTIVITY_PAUSED` event means that the app has gone from the foreground (either stopped or running in background). If you open an app, `ACTIVITY_RESUMED` is immediately called and time is logged (it doesn't no matter whether you're running for the first time or not) and when you close this app or switch to another app `ACTIVITY_PAUSED` is called and time is logged as usual. So, the time difference between these two events should be your screen time (for that period of time). However, things are not so simple. For instance, for launcher app, these events are called randomly, I mean, after `ACTIVITY_RESUMED` was called for the launcher app, say you opened App Manager (`ACTIVITY_RESUMED` called again, this time for App Manager) and closed it again (`ACTIVITY_PAUSED` was called for App Manager). There's a possibility that `ACTIVITY_PAUSED` was still not called for the launcher. However, this only happens if the launcher isn't running in the foreground (but still `ACTIVITY_RESUMED` is called for some reason). So, we just need to skip this event for the launcher. In general, the algorithm just considers the case where `ACTIVITY_RESUMED` and `ACTIVITY_PAUSED` are logged for an app in a sequential manner. This is so because you can't launch an app in the middle of running another app (the previously running app have to call `ACTIVITY_PAUSED` and the newly running app must call `ACTIVITY_RESUMED` *after* that event).

**Comment by MuntashirAkon** [comment] 2020-06-24 07:05
I'm closing this issue. I've still kept monthly and yearly options as I'll be experimenting with them later on. You can subscribe to issue #15 to keep up-to-date with the changes to this feature.

**Closed by MuntashirAkon** 2020-06-24 07:05 UTC
Labels: bug
