### ISSUE TITLE
Activities Shortcut open issue 

### ISSUE THREAD

**Issue by ParryShah** [MuntashirAkon/AppManager#1001] opened 2023-02-16 23:02 UTC
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Getting error after creating shortcut for app activities in version AppManager_v3.1.0-beta01-DEBUG#2237.apk
" Failed to read app data. Can not start the app."

### Screenshots

![Screenshot_2023-02-17-04-28-17-98_b783bf344239542886fee7b48fa4b892](https://user-images.githubusercontent.com/42093168/219507219-a12b404b-20fc-4509-a674-9451130f3358.jpg)

### Device info

- Device:
- OS Version:
- App Manager Version:
- Mode: Root/ADB/NonRoot

**Comment by MuntashirAkon** [comment] 2023-02-17 03:29
Does it open from the activities tab?

**Comment by ParryShah** [comment] 2023-02-17 13:04
> Does it open from the activities tab?

Yed its opening from tab

**Comment by ParryShah** [comment] 2023-02-18 18:32
> Does it open from the activities tab?

02-18 23:51:05.736 12611 12611 E AppLauncher: Unable to launch. tag=WorkspaceItemInfo(id=294 type=DEEPSHORTCUT container=154 targetComponent=ComponentInfo{io.github.muntashirakon.AppManager.debug/io.github.muntashirakon.AppManager.main.SplashActivity} screen=0 cell(1,2) span(1,1) minSpan(1,1) rank=7 user=UserHandle{0} title=Phone info, update=false, limit=false, runtime=0, status=0 intent=Intent { act=android.intent.action.MAIN cat=[com.android.launcher.DEEP_SHORTCUT] flg=0x10200000 pkg=io.github.muntashirakon.AppManager.debug cmp=io.github.muntashirakon.AppManager.debug/io.github.muntashirakon.AppManager.main.SplashActivity bnds=[406,1439][706,1754] (has extras) }) intent=Intent { act=android.intent.action.MAIN cat=[com.android.launcher.DEEP_SHORTCUT] flg=0x10200000 pkg=io.github.muntashirakon.AppManager.debug cmp=io.github.muntashirakon.AppManager.debug/io.github.muntashirakon.AppManager.main.SplashActivity bnds=[406,1439][706,1754] (has extras) }
02-18 23:51:05.736 12611 12611 E AppLauncher: android.content.ActivityNotFoundException: Shortcut could not be started
02-18 23:51:05.736 12611 12611 E AppLauncher: 	at android.content.pm.LauncherApps.startShortcut(LauncherApps.java:1594)
02-18 23:51:05.736 12611 12611 E AppLauncher: 	at android.content.pm.LauncherApps.startShortcut(LauncherApps.java:1559)
02-18 23:51:05.736 12611 12611 E AppLauncher: 	at com.android.launcher3.views.AppLauncher.startShortcut(:1)
02-18 23:51:05.736 12611 12611 E AppLauncher: 	at com.android.launcher3.views.AppLauncher.startShortcutIntentSafely(:8)
02-18 23:51:05.736 12611 12611 E AppLauncher: 	at com.android.launcher3.views.AppLauncher.startActivitySafely(:18)
02-18 23:51:05.736 12611 12611 E AppLauncher: 	at com.android.launcher3.Launcher.startActivitySafely(:7)
02-18 23:51:05.736 12611 12611 E AppLauncher: 	at com.android.launcher3.uioverrides.QuickstepLauncher.startActivitySafely(:2)
02-18 23:51:05.736 12611 12611 E AppLauncher: 	at com.android.launcher.Launcher.startActivitySafely(:1)
02-18 23:51:05.736 12611 12611 E AppLauncher: 	at com.android.launcher3.touch.ItemClickHandler.startAppShortcutOrInfoActivity(:25)
02-18 23:51:05.736 12611 12611 E AppLauncher: 	at com.android.launcher3.touch.ItemClickHandler.onClickAppShortcut(:10)
02-18 23:51:05.736 12611 12611 E AppLauncher: 	at com.android.launcher3.touch.OplusItemClickHandler.onClickAppShortcut(:4)
02-18 23:51:05.736 12611 12611 E AppLauncher: 	at com.android.launcher3.touch.OplusItemClickHandler.onClick(:34)
02-18 23:51:05.736 12611 12611 E AppLauncher: 	at com.android.launcher.guide.a.onClick(Unknown Source:14)
02-18 23:51:05.736 12611 12611 E AppLauncher: 	at android.view.View.performClick(View.java:7558)
02-18 23:51:05.736 12611 12611 E AppLauncher: 	at android.view.View.performClickInternal(View.java:7534)
02-18 23:51:05.736 12611 12611 E AppLauncher: 	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
02-18 23:51:05.736 12611 12611 E AppLauncher: 	at android.view.View$PerformClick.run(View.java:29661)
02-18 23:51:05.736 12611 12611 E AppLauncher: 	at android.os.Handler.handleCallback(Handler.java:942)
02-18 23:51:05.736 12611 12611 E AppLauncher: 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-18 23:51:05.736 12611 12611 E AppLauncher: 	at android.os.Looper.loopOnce(Looper.java:240)
02-18 23:51:05.736 12611 12611 E AppLauncher: 	at android.os.Looper.loop(Looper.java:351)
02-18 23:51:05.736 12611 12611 E AppLauncher: 	at android.app.ActivityThread.main(ActivityThread.java:8380)
02-18 23:51:05.736 12611 12611 E AppLauncher: 	at java.lang.reflect.Method.invoke(Native Method)
02-18 23:51:05.736 12611 12611 E AppLauncher: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
02-18 23:51:05.736 12611 12611 E AppLauncher: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)


This might help

> Does it open from the activities tab?

**Comment by MuntashirAkon** [comment] 2023-03-08 07:03
The error seems to be emitted from the launcher, rather than App Manager. Is there a way to reproduce the issue?

**Comment by ParryShah** [comment] 2023-03-18 19:10
> The error seems to be emitted from the launcher, rather than App Manager. Is there a way to reproduce the issue?

Tried from different launcher also
Like Nova launcher and in that showing app not installed 
![Screenshot_2023-03-19-00-39-10-73_3822ac0e29cfec8970059bb21d01f05e](https://user-images.githubusercontent.com/42093168/226131286-87882899-fca2-46bc-958e-c8dc91be181c.jpg)

**Comment by ParryShah** [comment] 2023-03-24 21:06
> The error seems to be emitted from the launcher, rather than App Manager. Is there a way to reproduce the issue?

Any update on this issue??

**Comment by Rokcy98** [comment] 2023-04-02 05:23
It happens to me too, some shortcuts aren't working (it says the shortcut is not available), while they work if I open the activity from the app and not from the launcher.

**Comment by MuntashirAkon** [comment] 2023-04-02 10:43
> It happens to me too, some shortcuts aren't working (it says the shortcut is not available), while they work if I open the activity from the app and not from the launcher.

Can you provide the steps to reproduce it, e.g. the name of the activity and app, launcher(s) used, etc.?

**Comment by Rokcy98** [comment] 2023-04-02 12:48
Sure, I don't think it depends on the launcher, since both Niagara (it says shourcut isn't available) and Stock ASUS launcher (it says app not installed) aren't working for some shortcuts.
I'll give you an example:
MEGA --> shortcut of main activity: it's not working
![Screenshot_20230402-144309](https://user-images.githubusercontent.com/62332789/229353754-65ebaa5f-3d93-41ed-8281-7760e005731e.jpg)
![Screenshot_20230402-144426](https://user-images.githubusercontent.com/62332789/229353762-bf670867-1ff2-42fb-af9a-b01e60c24ac8.jpg)

FatSecret --> shortcut of main activity: it works
![Screenshot_20230402-144420](https://user-images.githubusercontent.com/62332789/229353785-8cfdc63c-a602-4377-aa4c-15b0b9b95ab9.jpg)

**Comment by ParryShah** [comment] 2023-04-02 12:49
> > It happens to me too, some shortcuts aren't working (it says the shortcut is not available), while they work if I open the activity from the app and not from the launcher.
> 
> Can you provide the steps to reproduce it, e.g. the name of the activity and app, launcher(s) used, etc.?

com.android.phone.settings.RadioInfo
com.android.settings.Settings$MobileNetworkActivity

Trying this activity to add shortcut Home screen

**Comment by Rokcy98** [comment] 2023-04-02 12:51
> > > It happens to me too, some shortcuts aren't working (it says the shortcut is not available), while they work if I open the activity from the app and not from the launcher.
> > 
> > 
> > Can you provide the steps to reproduce it, e.g. the name of the activity and app, launcher(s) used, etc.?
> 
> com.android.phone.settings.RadioInfo com.android.settings.Settings$MobileNetworkActivity
> 
> Trying this activity to add shortcut Home screen

They are not working for me too, while they work if I open them from the app, or if I create a shortcut of them with another app (sd maid)

**Comment by MuntashirAkon** [comment] 2023-04-02 13:01
Which version of Android? Working perfectly fine in my device running Android 11 (Lineage OS 18.1).

**Comment by Rokcy98** [comment] 2023-04-02 13:02
> Which version of Android? Working perfectly fine in my device running Android 11 (Lineage OS 18.1).

A13 here

**Comment by ParryShah** [comment] 2023-04-02 13:07
> Which version of Android? Working perfectly fine in my device running Android 11 (Lineage OS 18.1).

A13 RUI

**Comment by MuntashirAkon** [comment] 2023-04-02 13:44
This is most probably caused by the new Intent requirements introduced in Android 13 (#794)

**Comment by Rokcy98** [comment] 2023-04-02 19:36
And, is it solvable?

**Comment by ParryShah** [comment] 2023-04-03 15:01
> This is most probably caused by the new Intent requirements introduced in Android 13 (#794)

And, is it solvable?

**Comment by MuntashirAkon** [comment] 2023-04-04 23:10
> is it solvable?

Yes. The issue shall be fixed before the next release.

**Comment by MuntashirAkon** [comment] 2023-04-23 10:59
Fixed in 98115c66c5f8719144944722afec5e0de2d20975

**Closed by MuntashirAkon** 2023-04-23 10:59 UTC
Labels: Bug, Priority: 1

**Comment by VA1DER** [comment] 2023-11-26 06:26
I now have an Android 13 device, and shortcuts created with version 3.0.4 of App Manager work on it just fine.  Can we revisit this and perhaps make the new way of creating shortcuts optional?
