### ISSUE TITLE
Cannot see all installed apps on main page

### ISSUE THREAD

**Issue by cafissimo** [MuntashirAkon/AppManager#976] opened 2023-01-14 20:13 UTC
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [x] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

When the app is opened not every installed application is listed.
No filters are applied, the issue is present also with a fresh installation.
An example app that is not shown is Google Chrome.
Device is Huawei Mate 20 Pro with Emui 12 that is supposed to be Android 10 based. 

Latest working release tested is 2.5.22. From 2.5.23 none works. 

### To Reproduce

- 1 Install the app
- 2 Open the app and explore applications list, some are missing 

### Expected behavior

1 - All installed apps should be in the main app list 

### Screenshots

![Screenshot_20230114_210616_io github muntashirakon AppManager](https://user-images.githubusercontent.com/11885368/212494261-f489bb90-542b-4546-9c88-4440beb11750.jpg)

Google Chrome is missing (just an example), also AppManager is missing. See below. 

![Screenshot_20230114_210840_io github muntashirakon AppManager](https://user-images.githubusercontent.com/11885368/212494329-c7e4badc-15f6-47b9-bcba-90a9998ad030.jpg)

### Logs

Device info
build.board: LYA
build.bootloader: unknown
build.brand: HUAWEI
build.cpu_abi: arm64-v8a
build.cpu_abi2: 
build.device: HWLYA
build.display: LYA-L29 10.1.0.289(C432E7R1P5)
build.fingerprint: HUAWEI/LYA-L29/HWLYA:10/HUAWEILYA-L29/10.1.0.289C432:user/release-keys
build.hardware: kirin980
build.host: cn-central-1b-d9aaf45301596181555256-3580069677-xx9nn
build.id: HUAWEILYA-L29
build.manufacturer: HUAWEI
build.model: LYA-L29
build.product: LYA-L29
build.radio: unknown
build.serial: unknown
build.tags: release-keys
build.time: 1596185479000
build.type: user
build.user: test
version.codename: REL
version.incremental: 10.1.0.289C432
version.release: 10
version.sdk_int: 29

Log
01-14 20:50:52.663 E/akon.AppManage(27876): LoadAppImageStartupCache enabled : 1
01-14 20:50:52.667 E/akon.AppManage(27876): Not starting debugger since process cannot load the jdwp agent.
01-14 20:50:52.695 E/BehaviorCollectManager(27876): Fail to acquire dataAnalyzerService...
01-14 20:50:52.735 E/AwareLog(27876): AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@ebeff78
01-14 20:50:53.108 E/HwViewGroupImpl(27876): parse speed value length error
01-14 20:50:53.221 E/JavaBinder(27876): !!! FAILED BINDER TRANSACTION !!!  (parcel size = 4)
01-14 20:50:59.076 E/SpannableStringBuilder(27876): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
01-14 20:50:59.082 E/SpannableStringBuilder(27876): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
01-14 20:51:03.623 E/SpannableStringBuilder(27876): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
01-14 20:51:03.704 E/SpannableStringBuilder(27876): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
01-14 20:51:20.030 E/SpannableStringBuilder(27876): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
01-14 20:51:20.032 E/SpannableStringBuilder(27876): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
01-14 20:51:57.942 E/SpannableStringBuilder(27876): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
01-14 20:51:57.961 E/SpannableStringBuilder(27876): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
01-14 20:52:00.368 E/JavaBinder(27876): !!! FAILED BINDER TRANSACTION !!!  (parcel size = 4)
01-14 20:52:02.759 E/JavaBinder(27876): !!! FAILED BINDER TRANSACTION !!!  (parcel size = 4)
01-14 20:52:18.009 E/SpannableStringBuilder(27876): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
01-14 20:52:18.022 E/SpannableStringBuilder(27876): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
01-14 20:52:41.361 E/SpannableStringBuilder(27876): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
01-14 20:52:41.365 E/SpannableStringBuilder(27876): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
01-14 20:52:45.375 E/RtgSchedManager(27876): endActivityTransaction: margin state not match
01-14 20:52:45.383 E/RtgSchedManager(27876): endActivityTransaction: margin state not match
01-14 20:52:45.415 E/RtgSchedManager(27876): endActivityTransaction: margin state not match
01-14 20:56:07.737 E/SpannableStringBuilder(27876): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
01-14 20:56:07.741 E/SpannableStringBuilder(27876): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
01-14 20:56:24.910 E/JavaBinder(27876): !!! FAILED BINDER TRANSACTION !!!  (parcel size = 4)
01-14 20:56:36.647 E/SpannableStringBuilder(27876): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
01-14 20:56:36.662 E/SpannableStringBuilder(27876): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
01-14 20:57:01.962 E/SpannableStringBuilder(27876): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
01-14 20:57:01.966 E/SpannableStringBuilder(27876): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
01-14 20:57:05.432 E/SpannableStringBuilder(27876): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
01-14 20:57:05.432 E/SpannableStringBuilder(27876): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
01-14 20:57:10.758 E/SpannableStringBuilder(27876): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
01-14 20:57:10.763 E/SpannableStringBuilder(27876): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
01-14 20:58:15.560 E/RtgSchedManager(27876): endActivityTransaction: margin state not match
01-14 20:58:15.564 E/RtgSchedManager(27876): endActivityTransaction: margin state not match
01-14 20:58:15.586 E/RtgSchedManager(27876): endActivityTransaction: margin state not match
01-14 21:06:25.439 E/RtgSchedManager(27876): endActivityTransaction: margin state not match
01-14 21:06:25.449 E/RtgSchedManager(27876): endActivityTransaction: margin state not match
01-14 21:06:25.477 E/RtgSchedManager(27876): endActivityTransaction: margin state not match
01-14 21:08:29.440 E/JavaBinder(27876): !!! FAILED BINDER TRANSACTION !!!  (parcel size = 4)
01-14 21:08:34.524 E/RtgSchedManager(27876): endActivityTransaction: margin state not match
01-14 21:08:34.528 E/RtgSchedManager(27876): endActivityTransaction: margin state not match
01-14 21:08:40.968 E/RtgSchedManager(27876): endActivityTransaction: margin state not match
01-14 21:11:03.588 E/JavaBinder(27876): !!! FAILED BINDER TRANSACTION !!!  (parcel size = 4)

### Device info

- Device: Huawei Mate 20 Pro 
- OS Version: Android 10 - Emui 12
- App Manager Version: 3.0.4
- Mode: NonRoot

### Additional context

Device not rooted, bootloader locked

**Comment by mrandreastoth** [comment] 2023-01-21 14:42
What are your filters?

**Comment by cafissimo** [comment] 2023-01-21 16:55
Hi,
I am attaching screenshots from 2.5.22 and latest 3.0.4416

![Screenshot_20230121_174524_io github muntashirakon AppManager](https://user-images.githubusercontent.com/11885368/213877826-5c85fb44-64b6-4ce4-936a-ca236cd01ee3.jpg)

![Screenshot_20230121_174820_io github muntashirakon AppManager](https://user-images.githubusercontent.com/11885368/213877829-05ae2b6c-c84d-48df-9765-1d4a4626e6a8.jpg)

But... The weird thing is that from 5 minutes ago when  I have updated to latest release no issue seem to be present anymore!

**Comment by MuntashirAkon** [comment] 2023-01-21 17:59
> The weird thing is that from 5 minutes ago when I have updated to latest release no issue seem to be present anymore!

You mean v3.1.0-alpha03?

**Comment by cafissimo** [comment] 2023-01-24 20:24
No, I have upgraded from 2.5.22 to 3.0.4416 and now all it's OK.
But last week it was not, I am sure, indeed I have tried older releases and
the one that started not to work was 2.5.23.
Weird, as I said, but there should be logs from my side.
Thanks.




Il sab 21 gen 2023, 19:00 Muntashir Al-Islam ***@***.***> ha
scritto:

**Comment by Tsyshiu** [comment] 2023-02-27 15:18
I encountered the same bug, huawei phone, magic UI 4.0.0, android 10, app version 3.0.4.

**Comment by Jesse205** [comment] 2023-05-19 20:00
Me,too.Most of the software installed on my phone does not display.For example, QQ,HUAWEI App Gallery.
![Screenshot_20230520_035453_io.github.muntashirakon.AppManager.jpg](https://github.com/MuntashirAkon/AppManager/assets/51242302/5084f7b3-d8a3-4536-ba83-58adad8cbde0)

**Comment by MuntashirAkon** [comment] 2023-09-14 11:43
Can anybody reproduce it via 3.1.1 or 4.0.0-alpha01? This is most likely due to the app containing too many components which exceeded the maximum transaction size. If that's the case, it will take some time to fix the issue as it requires a complete rewrite of logic related to package info.

**Comment by MuntashirAkon** [comment] 2023-09-14 15:44
> Do you need logs?

Yes. I need to ensure that this is happening due to the same issue that was reported at first.

**Comment by cafissimo** [comment] 2023-09-15 00:09
Here are logs

**Comment by cafissimo** [comment] 2023-09-15 00:11
[file_6863965719297722816.zip](https://github.com/MuntashirAkon/AppManager/files/12614409/file_6863965719297722816.zip)

Logs
Thanks

**Comment by MuntashirAkon** [comment] 2023-09-15 05:17
Can confirm that it's the same issue. Ref:

```
E/JavaBinder(15317): !!! FAILED BINDER TRANSACTION !!!  (parcel size = 4)
W/ParceledListSlice(15317): Failure retrieving array; only received 96 of 438
W/ParceledListSlice(15317): android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
W/ParceledListSlice(15317): 	at android.os.BinderProxy.transactNative(Native Method)
W/ParceledListSlice(15317): 	at android.os.BinderProxy.transact(BinderProxy.java:535)
W/ParceledListSlice(15317): 	at android.content.pm.BaseParceledListSlice.<init>(BaseParceledListSlice.java:100)
W/ParceledListSlice(15317): 	at android.content.pm.ParceledListSlice.<init>(ParceledListSlice.java:42)
W/ParceledListSlice(15317): 	at android.content.pm.ParceledListSlice.<init>(ParceledListSlice.java:35)
W/ParceledListSlice(15317): 	at android.content.pm.ParceledListSlice$1.createFromParcel(ParceledListSlice.java:80)
W/ParceledListSlice(15317): 	at android.content.pm.ParceledListSlice$1.createFromParcel(ParceledListSlice.java:78)
W/ParceledListSlice(15317): 	at android.content.pm.IPackageManager$Stub$Proxy.getInstalledPackages(IPackageManager.java:6280)
W/ParceledListSlice(15317): 	at io.github.muntashirakon.AppManager.compat.PackageManagerCompat.getInstalledPackages(PackageManagerCompat.java:146)
W/ParceledListSlice(15317): 	at io.github.muntashirakon.AppManager.db.utils.AppDb.updateApplications(AppDb.java:260)
W/ParceledListSlice(15317): 	at io.github.muntashirakon.AppManager.db.utils.AppDb.loadInstalledOrBackedUpApplications(AppDb.java:151)
W/ParceledListSlice(15317): 	at io.github.muntashirakon.AppManager.utils.PackageUtils.lambda$getInstalledOrBackedUpApplicationsFromDb$0(PackageUtils.java:243)
W/ParceledListSlice(15317): 	at io.github.muntashirakon.AppManager.utils.PackageUtils$$ExternalSyntheticLambda1.run(Unknown Source:6)
W/ParceledListSlice(15317): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
W/ParceledListSlice(15317): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/ParceledListSlice(15317): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/ParceledListSlice(15317): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/ParceledListSlice(15317): 	at java.lang.Thread.run(Thread.java:929)
```

**Comment by MuntashirAkon** [comment] 2023-09-17 08:05
Might be fixed by 78d3f25390e85d93756c7f8942f6505b982d5320

**Closed by MuntashirAkon** 2023-09-17 08:05 UTC
Labels: Bug, Severity: 2, Priority: 2

**Comment by Tsyshiu** [comment] 2023-09-18 08:10
still exists, when i tried to run with the latest code

<img width="821" alt="image" src="https://github.com/MuntashirAkon/AppManager/assets/38075786/bf7146e8-f362-40bd-a8da-5d08b5730cab">

> Might be fixed by [78d3f25](https://github.com/MuntashirAkon/AppManager/commit/78d3f25390e85d93756c7f8942f6505b982d5320)

**Comment by MuntashirAkon** [comment] 2023-09-18 08:59
> still exists, when i tried to run with the latest code

My mistake, it's difficult to fix something I can't reproduce. I shall try another fix.

**Comment by Tsyshiu** [comment] 2023-09-18 09:09
> > still exists, when i tried to run with the latest code
> 
> My mistake, it's difficult to fix something I can't reproduce. I shall try another fix.

Thank you for your support in developing☺️, i will try running the latest code on my mobile to make this app better whenever any fixes are committed.

**Comment by MuntashirAkon** [comment] 2023-09-18 09:34
Should be fixed by 094d327375721e32c0bb20d69576835b073b7c36

**Comment by Tsyshiu** [comment] 2023-09-19 01:24
> Should be fixed by [094d327](https://github.com/MuntashirAkon/AppManager/commit/094d327375721e32c0bb20d69576835b073b7c36)

I tried the latest code, 
it works fine. I think it is fixed. But the warning still exists in the log, maybe is only  a trivial problem now.

Log is posted below
[0919.log](https://github.com/MuntashirAkon/AppManager/files/12654669/0919.log)

**Comment by MuntashirAkon** [comment] 2023-09-19 01:53
> But the warning still exists in the log, maybe is only a trivial problem now.

Yes. First we try the usual way and then the workaround if it does not work.

**Comment by cafissimo** [comment] 2023-09-19 07:02
Fixed for Huawei mate 20 pro

Luca Caldiero

Il mar 19 set 2023, 03:53 Muntashir Al-Islam ***@***.***> ha
scritto:
