### ISSUE TITLE
AppManager Crashes when access certain tabs of any app

### ISSUE THREAD

**Issue by dhammel** [MuntashirAkon/AppManager#213] opened 2021-01-06 17:51 UTC
Hello,

AppManager crashes, and restarts automatically when accessing, Providers, App Ops, Uses Permissions Permissions, and Uses Features of any app. I first noticed on version v2.5.17. Updated to v2.5.20 same issue occurs. When updating to v2.5.20, it was a clean install as I had to switch from fdroid version to one here on github as its not yet updated on fdroid, i checked and confirmed issue was still present before attempting to restore my backup. I noticed this issue when updating to the Janurary 2021 security update of android 11. This issue didn't occur before this update of android, and its the only system level change I made.

Crash log below. Also, my device is actually a pixel 4. Im using a magisk module to bypass hardware based key attestation which is why it picked up as a nexus 5.

java.lang.ExceptionInInitializerError
    at io.github.muntashirakon.AppManager.appops.AppOpsManager.permissionToOpCode(AppOpsManager.java:1502)
    at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.loadUsesPermissions(AppDetailsViewModel.java:1007)
    at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.lambda$rcK05b73qPcOD8WauhT_GpajWOk(Unknown Source:0)
    at io.github.muntashirakon.AppManager.details.-$$Lambda$AppDetailsViewModel$rcK05b73qPcOD8WauhT_GpajWOk.run(Unknown Source:2)
    at java.lang.Thread.run(Thread.java:923)
 Caused by: java.lang.ArrayIndexOutOfBoundsException: length=100; index=100
   at io.github.muntashirakon.AppManager.appops.AppOpsManager.<clinit>(AppOpsManager.java:1410)
   at io.github.muntashirakon.AppManager.appops.AppOpsManager.permissionToOpCode(AppOpsManager.java:1502)
   at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.loadUsesPermissions(AppDetailsViewModel.java:1007)
   at io.github.muntashirakon.AppManager.details.AppDetailsViewModel.lambda$rcK05b73qPcOD8WauhT_GpajWOk(Unknown Source:0)
   at io.github.muntashirakon.AppManager.details.-$$Lambda$AppDetailsViewModel$rcK05b73qPcOD8WauhT_GpajWOk.run(Unknown Source:2)
   at java.lang.Thread.run(Thread.java:923)

Device Info:
App version: 2.5.20
App version code: 375
Android build version: 7005429
Android release version: 11
Android SDK version: 30
Android build ID: RQ1A.210105.003
Device brand: google
Device manufacturer: Google
Device name: flame
Device model: Nexus 5
Device product name: flame
Device hardware name: flame
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-US
In-App Language: auto

**Comment by MuntashirAkon** [comment] 2021-01-06 17:56
Duplicate of #194

**Closed by MuntashirAkon** 2021-01-06 17:56 UTC
