### ISSUE TITLE
Crashes when opening app info page in ADB mode

### ISSUE THREAD

**Issue by HemanthJabalpuri** [MuntashirAkon/AppManager#945] opened 2022-12-02 10:22 UTC
### Please check before submitting an issue

- [x] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Crashes when opening app info page in ADB mode

### To Reproduce

1. Connect device in ADB over TCP mode with `adb tcpip 5555`
2. Restart AM and it will detect ADB mode
3. Try to open any App Info page by clicking on one of the app in the app listing

### Expected behavior

App Info page should be shown

### Logs

[App Manager_Crash report.txt](https://github.com/MuntashirAkon/AppManager/files/10140210/App.Manager_Crash.report.txt)

### Device info

App version: 3.0.3
App version code: 414
Android build version: 1622100863
Android release version: 10
Android SDK version: 29
Android build ID: RMX2189_11_A.95
Device brand: realme
Device manufacturer: realme
Device name: RMX2189
Device model: RMX2189
Device product name: RMX2189
Device hardware name: mt6765
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-GB
In-App Language: auto
Mode: auto
Inferred Mode: ADB

**Comment by MuntashirAkon** [comment] 2022-12-02 10:29
Duplicate of #884

**Comment by MuntashirAkon** [comment] 2022-12-02 10:29
See the linked issue for the solution.

**Closed by MuntashirAkon** 2022-12-02 10:29 UTC
Labels: Bug, Duplicate

**Comment by HemanthJabalpuri** [comment] 2022-12-02 10:44
Thanks for quick solution, I thought it is not needed cause in guide it stated like optional thing(maybe my interpretation is wrong?)
![Screenshot_2022-12-02-16-06-52-19_1](https://user-images.githubusercontent.com/39197123/205274685-ec811766-8150-4771-b19d-307139a1f5c1.jpg)

https://muntashirakon.github.io/AppManager/en/#subsec:enable-usb-debugging

Also I have a question, is it possible to filter apps without splits in v3.0.3? Likewise filtering/searching apps having/not having specific permissions?

One feature request to add 'Save APK' to App Info options menu too.

Thanks

**Comment by MuntashirAkon** [comment] 2022-12-02 15:01
> Thanks for quick solution, I thought it is not needed cause in guide it stated like optional thing(maybe my interpretation is wrong?)

It states that you either have to disable **Permission Monitoring** or **USB Debugging (Security Settings)** with **Install via USB** depending on the version of operating system you have. I've never owned a Realme device myself, but according to the screenshots that I've seen the first two options are exclusive, only one of them is present in any version of the OS.

> is it possible to filter apps without splits in v3.0.3?

No, only _with_ splits.

> Likewise filtering/searching apps having/not having specific permissions?

No. See #321.

> One feature request to add 'Save APK' to App Info options menu too.

There's already a share button which can be used to export, share/save APK. This behaviour is different from the **Save APK** option in batch operations in the Main page because they have different use cases. But, of course, if you have valid arguments for your feature request, I can look into it.
