### ISSUE TITLE
Activities Shortcut open issue reference #1001

### ISSUE THREAD

**Issue by ParryShah** [MuntashirAkon/AppManager#1034] opened 2023-03-27 03:03 UTC
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

When i create App activity shortcut of user app its working but with system apps its not working.

### Device info

- Device:
- OS Version:
- App Manager Version:
- Mode: Root/ADB/NonRoot

**Comment by kryptobolt200528** [comment] 2023-03-28 01:03
Is the mode of operation root or adb ??

**Comment by MuntashirAkon** [comment] 2023-03-29 06:06
I don't understand. Is this related to #1001 or the same issue?

**Comment by ParryShah** [comment] 2023-04-02 05:35
> Is the mode of operation root or adb ??

Root mode

**Comment by ParryShah** [comment] 2023-04-02 05:36
> I don't understand. Is this related to #1001 or the same issue?

Same issue..
I am using activity launcher from play store if dev can check that app it could be help..
That app is working with activity shortcut

**Comment by MuntashirAkon** [comment] 2023-04-02 05:51
Duplicate of #1001

**Closed by MuntashirAkon** 2023-04-02 05:51 UTC
Labels: Bug, Duplicate
