### ISSUE TITLE
The "Screen Time" widget not displayed properly

### ISSUE THREAD

**Issue by shym3q** [MuntashirAkon/AppManager#1240] opened 2023-11-02 13:27 UTC
### Please check before submitting an issue

- [X] I know what my device, OS and App Manager versions are
- [X] I know how to take logs
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

The widget's title is cropped. The bottom circle is not fully visible.

### To Reproduce

- 1. Go to LineageOS default system launcher.
- 2. Tap and hold on the screen.
- 3. Go to widgets and add App Manager's "Screen Time" widget to the launcher.

### Expected behavior

The widget doesn't crop its contet.

### Screenshots

![Screenshot_20231102-122933_Trebuchet](https://github.com/MuntashirAkon/AppManager/assets/105586559/599ccaa5-a703-42ef-b635-79f714e67e64)

### Device info

- Device: Xiaomi Redmi Note 12 Pro+
- OS Version: LineageOS 20 on Android 13
- App Manager Version: 3.1.3 (426)
- Mode: Root

**Comment by MuntashirAkon** [comment] 2023-11-12 08:02
Duplicate of #812

**Closed by MuntashirAkon** 2023-11-12 08:02 UTC
Labels: Bug, Duplicate
