### ISSUE TITLE
Enhance search for components 

### ISSUE THREAD

**Issue by HyperCriSiS** [MuntashirAkon/AppManager#888] opened 2022-10-14 15:22 UTC
Hi,
Can you add the possibility to use the search bar to search in all apps for certain components?
Also it would be very convenient when selecting a component to be able to disable it globally.

Thanks for this awesome app!!

Best regards,
Hyper

**Comment by MuntashirAkon** [comment] 2022-10-14 15:49
Duplicate of #321

**Closed by MuntashirAkon** 2022-10-14 15:49 UTC
Labels: Duplicate
