### ISSUE TITLE
Expand App Usage functionality

### ISSUE THREAD

**Issue by NikunjKhangwal** [MuntashirAkon/AppManager#1332] opened 2024-04-01 09:03 UTC
### Please check before submitting an issue

- [X] I am using the latest version of App Manager
- [X] I have searched the issues and haven't found anything relevant
- [X] I have read the docs

### Describe a description of the new feature

Since this app already has usage access. Try to extended the functionality to also include device unlocks and apps notifications count if possible.

**Comment by MuntashirAkon** [comment] 2024-04-07 19:12
Duplicate of #458

**Closed by MuntashirAkon** 2024-04-07 19:12 UTC
Labels: Duplicate, Feature

**Comment by MuntashirAkon** [comment] 2024-04-07 19:13
The first part, that is, device unlocks is beyond the intended use of app usage feature. But it may be considered for #143.
