### ISSUE TITLE
Aurora AppWarden App - Similar "Suspend" function

### ISSUE THREAD

**Issue by StaggerLeee** [MuntashirAkon/AppManager#661] opened 2022-01-30 10:23 UTC
- [x] I am using the latest version of App Manager
- [x] I have searched the issues and haven't found anything relevant
- [x] I have read the docs

**Is your feature request related to a problem? Please describe.**

- Not really a problem, just a feature request. AppManager works as expected.

**Describe the solution you'd like**

- An option to "Suspend" Apps and make them "frozen" but still have icons at Apps list.

**Describe alternatives you've considered**

- Similar as AppWarden from AuroraOSS has.
[https://auroraoss.com/download/AppWarden/](https://auroraoss.com/download/AppWarden/)

Freeze (Suspend) Apps that are very rarely used, but still have icons of them in Apps list. In AppWarden case icons are greyed and clicking on suspended App icon popup with message is shown:

`App isn't available
xxxxxxxx isn't available right now. This is managed by root`

AppWarden make it easy and quick to suspend Apps this way. I don't know if there is a similar combination of clickings and options in AppManager. I could not achieve that anyway.
Normally AppWarden would be enough, but it is not maintained anymore (believe so, not 100% sure). Just matter of time before it stops working with new Android version.
Native in Android is "freeze" (force stop) option for all Apps, system or User not matter. From my own experience I know if I freeze an App this way I completely forget it exist in my system. Then I am not sure if updates for frozen Apps arrive, have not checked in last time. Before it was not possible.

Is it difficult to implement ? 
Would it be far away from AppManager philosophy ?

**Additional context**

- I do not have a picture. In Warden App Suspend option is open by clicking rounded button with "#" sign.

**Comment by MuntashirAkon** [comment] 2022-01-30 10:34
Duplicate of #413

**Comment by MuntashirAkon** [comment] 2022-01-30 10:42
While AM displays all the supported app states, namely force-stopped, suspended, hidden, disabled and uninstalled, it only features force-stop, enable/disable and install/uninstall for the sake of clarity and use. For example, **force-stop** (also advertised as freeze by apps such as Greenify and SuperFreezZ) is the most frequently used setting in Android and **disabled** is the most powerful state among suspended, hidden and disabled.

**Closed** 2022-01-30 11:05 UTC
Labels: duplicate, feature, P3
